

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "14", "39", "51", "52", "53", "54", "55", "56"],
		"CDFG" : "softmax_accel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "276",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_load_logits_and_find_max_fu_687", "Port" : "gmem", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "39", "SubInstance" : "grp_normalize_and_store_fu_720", "Port" : "gmem", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "mem", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_base", "Type" : "None", "Direction" : "I"},
			{"Name" : "prob_base", "Type" : "None", "Direction" : "I"},
			{"Name" : "dbg_base", "Type" : "None", "Direction" : "I"},
			{"Name" : "n", "Type" : "None", "Direction" : "I"},
			{"Name" : "RECIP_M_Q30", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "RECIP_B_Q30", "Type" : "Memory", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.RECIP_M_Q30_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.RECIP_B_Q30_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.logits_buf_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.logits_buf_1_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.logits_buf_2_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.logits_buf_3_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.exp_buf_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.exp_buf_1_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.exp_buf_2_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.exp_buf_3_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_load_logits_and_find_max_fu_687", "Parent" : "0", "Child" : ["12"],
		"CDFG" : "load_logits_and_find_max",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "17", "EstimateLatencyMax" : "80",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_load_logits_and_find_max_Pipeline_load_loop_fu_100", "Port" : "gmem", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "mem", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_l", "Type" : "None", "Direction" : "I"},
			{"Name" : "n", "Type" : "None", "Direction" : "I"},
			{"Name" : "logits_buf_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_load_logits_and_find_max_Pipeline_load_loop_fu_100", "Port" : "logits_buf_0", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "logits_buf_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_load_logits_and_find_max_Pipeline_load_loop_fu_100", "Port" : "logits_buf_1", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "logits_buf_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_load_logits_and_find_max_Pipeline_load_loop_fu_100", "Port" : "logits_buf_2", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "logits_buf_3", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_load_logits_and_find_max_Pipeline_load_loop_fu_100", "Port" : "logits_buf_3", "Inst_start_state" : "10", "Inst_end_state" : "11"}]}]},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_load_logits_and_find_max_fu_687.grp_load_logits_and_find_max_Pipeline_load_loop_fu_100", "Parent" : "11", "Child" : ["13"],
		"CDFG" : "load_logits_and_find_max_Pipeline_load_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "69",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "blocks", "Type" : "None", "Direction" : "I"},
			{"Name" : "n", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln204", "Type" : "None", "Direction" : "I"},
			{"Name" : "logits_buf_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "logits_buf_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "logits_buf_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "logits_buf_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "max_x_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "load_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_load_logits_and_find_max_fu_687.grp_load_logits_and_find_max_Pipeline_load_loop_fu_100.flow_control_loop_pipe_sequential_init_U", "Parent" : "12"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705", "Parent" : "0", "Child" : ["15", "34", "37", "38"],
		"CDFG" : "generate_exp_buffer",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "13", "EstimateLatencyMax" : "76",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "15", "Name" : "emit_exp_stream_U0"}],
		"OutputProcess" : [
			{"ID" : "34", "Name" : "cache_exp_stream_U0"}],
		"Port" : [
			{"Name" : "logits_buf_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "emit_exp_stream_U0", "Port" : "logits_buf_0"}]},
			{"Name" : "logits_buf_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "emit_exp_stream_U0", "Port" : "logits_buf_1"}]},
			{"Name" : "logits_buf_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "emit_exp_stream_U0", "Port" : "logits_buf_2"}]},
			{"Name" : "logits_buf_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "emit_exp_stream_U0", "Port" : "logits_buf_3"}]},
			{"Name" : "n", "Type" : "None", "Direction" : "I"},
			{"Name" : "max_x", "Type" : "None", "Direction" : "I"},
			{"Name" : "exp_buf_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "cache_exp_stream_U0", "Port" : "exp_buf_0"}]},
			{"Name" : "exp_buf_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "cache_exp_stream_U0", "Port" : "exp_buf_1"}]},
			{"Name" : "exp_buf_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "cache_exp_stream_U0", "Port" : "exp_buf_2"}]},
			{"Name" : "exp_buf_3", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "cache_exp_stream_U0", "Port" : "exp_buf_3"}]},
			{"Name" : "sum64_out", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "cache_exp_stream_U0", "Port" : "sum64_out"}]}]},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0", "Parent" : "14", "Child" : ["16"],
		"CDFG" : "emit_exp_stream",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "73",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "logits_buf_0", "Type" : "Stable", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64", "Port" : "logits_buf_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "logits_buf_1", "Type" : "Stable", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64", "Port" : "logits_buf_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "logits_buf_2", "Type" : "Stable", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64", "Port" : "logits_buf_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "logits_buf_3", "Type" : "Stable", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64", "Port" : "logits_buf_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "n", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "max_x", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "exp_stream", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["34"], "DependentChan" : "37", "DependentChanDepth" : "16", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "16", "SubInstance" : "grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64", "Port" : "exp_stream", "Inst_start_state" : "1", "Inst_end_state" : "2"}]}]},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64", "Parent" : "15", "Child" : ["17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33"],
		"CDFG" : "emit_exp_stream_Pipeline_exp_emit_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "9", "EstimateLatencyMax" : "72",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "trunc_ln", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "n", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "logits_buf_0", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "max_x", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "logits_buf_1", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "logits_buf_2", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "logits_buf_3", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "exp_stream", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "exp_stream_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "exp_emit_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter7", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter7", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "17", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_33_4_17_1_1_U18", "Parent" : "16"},
	{"ID" : "18", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_33_4_17_1_1_U19", "Parent" : "16"},
	{"ID" : "19", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_33_4_17_1_1_U20", "Parent" : "16"},
	{"ID" : "20", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_33_4_17_1_1_U21", "Parent" : "16"},
	{"ID" : "21", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_33_4_18_1_1_U22", "Parent" : "16"},
	{"ID" : "22", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.mul_12ns_18s_30_1_1_U23", "Parent" : "16"},
	{"ID" : "23", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_33_4_18_1_1_U24", "Parent" : "16"},
	{"ID" : "24", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.mul_12ns_18s_30_1_1_U25", "Parent" : "16"},
	{"ID" : "25", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_33_4_18_1_1_U26", "Parent" : "16"},
	{"ID" : "26", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.mul_12ns_18s_30_1_1_U27", "Parent" : "16"},
	{"ID" : "27", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_33_4_18_1_1_U28", "Parent" : "16"},
	{"ID" : "28", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.mul_12ns_18s_30_1_1_U29", "Parent" : "16"},
	{"ID" : "29", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_7_2_32_1_1_U30", "Parent" : "16"},
	{"ID" : "30", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_7_2_32_1_1_U31", "Parent" : "16"},
	{"ID" : "31", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_7_2_32_1_1_U32", "Parent" : "16"},
	{"ID" : "32", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.sparsemux_7_2_32_1_1_U33", "Parent" : "16"},
	{"ID" : "33", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.emit_exp_stream_U0.grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_64.flow_control_loop_pipe_sequential_init_U", "Parent" : "16"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.cache_exp_stream_U0", "Parent" : "14", "Child" : ["35"],
		"CDFG" : "cache_exp_stream",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "69",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "15",
		"StartFifo" : "start_for_cache_exp_stream_U0_U",
		"Port" : [
			{"Name" : "exp_stream", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["15"], "DependentChan" : "37", "DependentChanDepth" : "16", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_cache_exp_stream_Pipeline_cache_exp_loop_fu_71", "Port" : "exp_stream", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "n", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "exp_buf_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_cache_exp_stream_Pipeline_cache_exp_loop_fu_71", "Port" : "exp_buf_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "exp_buf_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_cache_exp_stream_Pipeline_cache_exp_loop_fu_71", "Port" : "exp_buf_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "exp_buf_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_cache_exp_stream_Pipeline_cache_exp_loop_fu_71", "Port" : "exp_buf_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "exp_buf_3", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_cache_exp_stream_Pipeline_cache_exp_loop_fu_71", "Port" : "exp_buf_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "sum64_out", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.cache_exp_stream_U0.grp_cache_exp_stream_Pipeline_cache_exp_loop_fu_71", "Parent" : "34", "Child" : ["36"],
		"CDFG" : "cache_exp_stream_Pipeline_cache_exp_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "67",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "trunc_ln", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "exp_buf_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "exp_buf_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "exp_buf_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "exp_buf_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "exp_stream", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "exp_stream_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sum64_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "cache_exp_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "36", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.cache_exp_stream_U0.grp_cache_exp_stream_Pipeline_cache_exp_loop_fu_71.flow_control_loop_pipe_sequential_init_U", "Parent" : "35"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.exp_stream_U", "Parent" : "14"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_generate_exp_buffer_fu_705.start_for_cache_exp_stream_U0_U", "Parent" : "14"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720", "Parent" : "0", "Child" : ["40", "47", "50"],
		"CDFG" : "normalize_and_store",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "7", "EstimateLatencyMax" : "92",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "40", "Name" : "emit_prob_stream_U0"},
			{"ID" : "47", "Name" : "write_prob_stream_U0"}],
		"OutputProcess" : [
			{"ID" : "47", "Name" : "write_prob_stream_U0"}],
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "47", "SubInstance" : "write_prob_stream_U0", "Port" : "gmem"}]},
			{"Name" : "mem", "Type" : "None", "Direction" : "I"},
			{"Name" : "pr_l", "Type" : "None", "Direction" : "I"},
			{"Name" : "n", "Type" : "None", "Direction" : "I"},
			{"Name" : "exp_buf_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "emit_prob_stream_U0", "Port" : "exp_buf_0"}]},
			{"Name" : "exp_buf_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "emit_prob_stream_U0", "Port" : "exp_buf_1"}]},
			{"Name" : "exp_buf_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "emit_prob_stream_U0", "Port" : "exp_buf_2"}]},
			{"Name" : "exp_buf_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "emit_prob_stream_U0", "Port" : "exp_buf_3"}]},
			{"Name" : "inv_sum_q30", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.emit_prob_stream_U0", "Parent" : "39", "Child" : ["41"],
		"CDFG" : "emit_prob_stream",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "69",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "exp_buf_0", "Type" : "Stable", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64", "Port" : "exp_buf_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "exp_buf_1", "Type" : "Stable", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64", "Port" : "exp_buf_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "exp_buf_2", "Type" : "Stable", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64", "Port" : "exp_buf_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "exp_buf_3", "Type" : "Stable", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64", "Port" : "exp_buf_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "n", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "inv_sum_q30", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "prob_stream", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["47"], "DependentChan" : "50", "DependentChanDepth" : "16", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64", "Port" : "prob_stream", "Inst_start_state" : "1", "Inst_end_state" : "2"}]}]},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.emit_prob_stream_U0.grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64", "Parent" : "40", "Child" : ["42", "43", "44", "45", "46"],
		"CDFG" : "emit_prob_stream_Pipeline_prob_emit_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "68",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "trunc_ln", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "n", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "exp_buf_0", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "zext_ln342", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "exp_buf_1", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "exp_buf_2", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "exp_buf_3", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "prob_stream", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "prob_stream_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "prob_emit_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "42", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.emit_prob_stream_U0.grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64.mul_32ns_31ns_62_1_1_U80", "Parent" : "41"},
	{"ID" : "43", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.emit_prob_stream_U0.grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64.mul_32ns_31ns_62_1_1_U81", "Parent" : "41"},
	{"ID" : "44", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.emit_prob_stream_U0.grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64.mul_32ns_31ns_62_1_1_U82", "Parent" : "41"},
	{"ID" : "45", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.emit_prob_stream_U0.grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64.mul_32ns_31ns_62_1_1_U83", "Parent" : "41"},
	{"ID" : "46", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.emit_prob_stream_U0.grp_emit_prob_stream_Pipeline_prob_emit_loop_fu_64.flow_control_loop_pipe_sequential_init_U", "Parent" : "41"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.write_prob_stream_U0", "Parent" : "39", "Child" : ["48"],
		"CDFG" : "write_prob_stream",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "89",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_write_prob_stream_Pipeline_prob_write_loop_fu_158", "Port" : "gmem", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "mem", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "pr_l", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "n", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "prob_stream", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["40"], "DependentChan" : "50", "DependentChanDepth" : "16", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "prob_stream_blk_n", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_write_prob_stream_Pipeline_prob_write_loop_fu_158", "Port" : "prob_stream", "Inst_start_state" : "1", "Inst_end_state" : "2"}]}]},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.write_prob_stream_U0.grp_write_prob_stream_Pipeline_prob_write_loop_fu_158", "Parent" : "47", "Child" : ["49"],
		"CDFG" : "write_prob_stream_Pipeline_prob_write_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "72",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "full_blocks", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "prob_stream", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "prob_stream_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "pr_l_cast", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "mem", "Type" : "Stable", "Direction" : "I"},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "prob_write_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter7", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter7", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "49", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.write_prob_stream_U0.grp_write_prob_stream_Pipeline_prob_write_loop_fu_158.flow_control_loop_pipe_sequential_init_U", "Parent" : "48"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_normalize_and_store_fu_720.prob_stream_U", "Parent" : "39"},
	{"ID" : "51", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "52", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U", "Parent" : "0"},
	{"ID" : "53", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_31s_16ns_47_1_1_U120", "Parent" : "0"},
	{"ID" : "54", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.partset_128ns_128ns_32ns_7ns_128_1_1_U121", "Parent" : "0"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.partset_128ns_128ns_32ns_7ns_128_1_1_U122", "Parent" : "0"},
	{"ID" : "56", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.partset_128ns_128ns_32s_7ns_128_1_1_U123", "Parent" : "0"}]}
