-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity prometheus_soc_emit_exp_stream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    logits_buf_0_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_18 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_19 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_20 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_21 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_22 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_23 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_24 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_25 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_26 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_27 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_28 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_29 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_30 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_31 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_32 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_33 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_34 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_35 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_36 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_37 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_38 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_39 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_40 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_41 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_42 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_43 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_44 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_45 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_46 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_47 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_48 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_49 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_50 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_51 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_52 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_53 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_54 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_55 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_56 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_57 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_58 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_59 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_60 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_61 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_62 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_63 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_18 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_19 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_20 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_21 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_22 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_23 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_24 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_25 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_26 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_27 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_28 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_29 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_30 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_31 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_32 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_33 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_34 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_35 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_36 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_37 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_38 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_39 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_40 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_41 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_42 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_43 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_44 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_45 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_46 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_47 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_48 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_49 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_50 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_51 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_52 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_53 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_54 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_55 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_56 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_57 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_58 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_59 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_60 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_61 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_62 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_63 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_18 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_19 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_20 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_21 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_22 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_23 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_24 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_25 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_26 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_27 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_28 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_29 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_30 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_31 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_32 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_33 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_34 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_35 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_36 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_37 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_38 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_39 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_40 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_41 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_42 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_43 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_44 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_45 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_46 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_47 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_48 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_49 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_50 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_51 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_52 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_53 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_54 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_55 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_56 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_57 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_58 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_59 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_60 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_61 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_62 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_63 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_18 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_19 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_20 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_21 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_22 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_23 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_24 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_25 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_26 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_27 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_28 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_29 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_30 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_31 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_32 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_33 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_34 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_35 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_36 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_37 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_38 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_39 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_40 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_41 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_42 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_43 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_44 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_45 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_46 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_47 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_48 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_49 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_50 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_51 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_52 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_53 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_54 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_55 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_56 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_57 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_58 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_59 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_60 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_61 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_62 : IN STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_3_63 : IN STD_LOGIC_VECTOR (31 downto 0);
    n : IN STD_LOGIC_VECTOR (8 downto 0);
    max_x : IN STD_LOGIC_VECTOR (31 downto 0);
    exp_stream_din : OUT STD_LOGIC_VECTOR (131 downto 0);
    exp_stream_full_n : IN STD_LOGIC;
    exp_stream_write : OUT STD_LOGIC;
    exp_stream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    exp_stream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of prometheus_soc_emit_exp_stream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv9_3 : STD_LOGIC_VECTOR (8 downto 0) := "000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal max_x_read_reg_2646 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal n_read_reg_2651 : STD_LOGIC_VECTOR (8 downto 0);
    signal blocks_cast_reg_2656 : STD_LOGIC_VECTOR (6 downto 0);
    signal logits_buf_0_0_read_reg_2661 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_1_read_reg_2666 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_2_read_reg_2671 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_3_read_reg_2676 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_4_read_reg_2681 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_5_read_reg_2686 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_6_read_reg_2691 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_7_read_reg_2696 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_8_read_reg_2701 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_9_read_reg_2706 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_10_read_reg_2711 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_11_read_reg_2716 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_12_read_reg_2721 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_13_read_reg_2726 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_14_read_reg_2731 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_15_read_reg_2736 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_16_read_reg_2741 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_17_read_reg_2746 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_18_read_reg_2751 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_19_read_reg_2756 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_20_read_reg_2761 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_21_read_reg_2766 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_22_read_reg_2771 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_23_read_reg_2776 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_24_read_reg_2781 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_25_read_reg_2786 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_26_read_reg_2791 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_27_read_reg_2796 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_28_read_reg_2801 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_29_read_reg_2806 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_30_read_reg_2811 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_31_read_reg_2816 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_32_read_reg_2821 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_33_read_reg_2826 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_34_read_reg_2831 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_35_read_reg_2836 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_36_read_reg_2841 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_37_read_reg_2846 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_38_read_reg_2851 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_39_read_reg_2856 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_40_read_reg_2861 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_41_read_reg_2866 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_42_read_reg_2871 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_43_read_reg_2876 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_44_read_reg_2881 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_45_read_reg_2886 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_46_read_reg_2891 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_47_read_reg_2896 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_48_read_reg_2901 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_49_read_reg_2906 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_50_read_reg_2911 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_51_read_reg_2916 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_52_read_reg_2921 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_53_read_reg_2926 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_54_read_reg_2931 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_55_read_reg_2936 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_56_read_reg_2941 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_57_read_reg_2946 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_58_read_reg_2951 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_59_read_reg_2956 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_60_read_reg_2961 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_61_read_reg_2966 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_62_read_reg_2971 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_0_63_read_reg_2976 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_0_read_reg_2981 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_1_read_reg_2986 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_2_read_reg_2991 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_3_read_reg_2996 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_4_read_reg_3001 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_5_read_reg_3006 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_6_read_reg_3011 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_7_read_reg_3016 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_8_read_reg_3021 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_9_read_reg_3026 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_10_read_reg_3031 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_11_read_reg_3036 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_12_read_reg_3041 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_13_read_reg_3046 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_14_read_reg_3051 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_15_read_reg_3056 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_16_read_reg_3061 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_17_read_reg_3066 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_18_read_reg_3071 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_19_read_reg_3076 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_20_read_reg_3081 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_21_read_reg_3086 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_22_read_reg_3091 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_23_read_reg_3096 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_24_read_reg_3101 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_25_read_reg_3106 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_26_read_reg_3111 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_27_read_reg_3116 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_28_read_reg_3121 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_29_read_reg_3126 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_30_read_reg_3131 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_31_read_reg_3136 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_32_read_reg_3141 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_33_read_reg_3146 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_34_read_reg_3151 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_35_read_reg_3156 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_36_read_reg_3161 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_37_read_reg_3166 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_38_read_reg_3171 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_39_read_reg_3176 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_40_read_reg_3181 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_41_read_reg_3186 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_42_read_reg_3191 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_43_read_reg_3196 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_44_read_reg_3201 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_45_read_reg_3206 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_46_read_reg_3211 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_47_read_reg_3216 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_48_read_reg_3221 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_49_read_reg_3226 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_50_read_reg_3231 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_51_read_reg_3236 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_52_read_reg_3241 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_53_read_reg_3246 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_54_read_reg_3251 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_55_read_reg_3256 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_56_read_reg_3261 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_57_read_reg_3266 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_58_read_reg_3271 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_59_read_reg_3276 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_60_read_reg_3281 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_61_read_reg_3286 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_62_read_reg_3291 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_1_63_read_reg_3296 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_0_read_reg_3301 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_1_read_reg_3306 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_2_read_reg_3311 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_3_read_reg_3316 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_4_read_reg_3321 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_5_read_reg_3326 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_6_read_reg_3331 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_7_read_reg_3336 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_8_read_reg_3341 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_9_read_reg_3346 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_10_read_reg_3351 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_11_read_reg_3356 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_12_read_reg_3361 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_13_read_reg_3366 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_14_read_reg_3371 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_15_read_reg_3376 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_16_read_reg_3381 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_17_read_reg_3386 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_18_read_reg_3391 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_19_read_reg_3396 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_20_read_reg_3401 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_21_read_reg_3406 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_22_read_reg_3411 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_23_read_reg_3416 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_24_read_reg_3421 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_25_read_reg_3426 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_26_read_reg_3431 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_27_read_reg_3436 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_28_read_reg_3441 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_29_read_reg_3446 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_30_read_reg_3451 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_31_read_reg_3456 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_32_read_reg_3461 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_33_read_reg_3466 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_34_read_reg_3471 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_35_read_reg_3476 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_36_read_reg_3481 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_37_read_reg_3486 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_38_read_reg_3491 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_39_read_reg_3496 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_40_read_reg_3501 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_41_read_reg_3506 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_42_read_reg_3511 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_43_read_reg_3516 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_44_read_reg_3521 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_45_read_reg_3526 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_46_read_reg_3531 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_47_read_reg_3536 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_48_read_reg_3541 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_49_read_reg_3546 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_50_read_reg_3551 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_51_read_reg_3556 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_52_read_reg_3561 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_53_read_reg_3566 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_54_read_reg_3571 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_55_read_reg_3576 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_56_read_reg_3581 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_57_read_reg_3586 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_58_read_reg_3591 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_59_read_reg_3596 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_60_read_reg_3601 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_61_read_reg_3606 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_62_read_reg_3611 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_2_63_read_reg_3616 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_0_read_reg_3621 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_1_read_reg_3626 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_2_read_reg_3631 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_3_read_reg_3636 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_4_read_reg_3641 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_5_read_reg_3646 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_6_read_reg_3651 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_7_read_reg_3656 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_8_read_reg_3661 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_9_read_reg_3666 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_10_read_reg_3671 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_11_read_reg_3676 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_12_read_reg_3681 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_13_read_reg_3686 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_14_read_reg_3691 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_15_read_reg_3696 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_16_read_reg_3701 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_17_read_reg_3706 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_18_read_reg_3711 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_19_read_reg_3716 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_20_read_reg_3721 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_21_read_reg_3726 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_22_read_reg_3731 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_23_read_reg_3736 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_24_read_reg_3741 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_25_read_reg_3746 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_26_read_reg_3751 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_27_read_reg_3756 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_28_read_reg_3761 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_29_read_reg_3766 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_30_read_reg_3771 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_31_read_reg_3776 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_32_read_reg_3781 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_33_read_reg_3786 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_34_read_reg_3791 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_35_read_reg_3796 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_36_read_reg_3801 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_37_read_reg_3806 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_38_read_reg_3811 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_39_read_reg_3816 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_40_read_reg_3821 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_41_read_reg_3826 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_42_read_reg_3831 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_43_read_reg_3836 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_44_read_reg_3841 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_45_read_reg_3846 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_46_read_reg_3851 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_47_read_reg_3856 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_48_read_reg_3861 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_49_read_reg_3866 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_50_read_reg_3871 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_51_read_reg_3876 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_52_read_reg_3881 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_53_read_reg_3886 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_54_read_reg_3891 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_55_read_reg_3896 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_56_read_reg_3901 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_57_read_reg_3906 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_58_read_reg_3911 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_59_read_reg_3916 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_60_read_reg_3921 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_61_read_reg_3926 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_62_read_reg_3931 : STD_LOGIC_VECTOR (31 downto 0);
    signal logits_buf_3_63_read_reg_3936 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start : STD_LOGIC;
    signal grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done : STD_LOGIC;
    signal grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_idle : STD_LOGIC;
    signal grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_ready : STD_LOGIC;
    signal grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_exp_stream_din : STD_LOGIC_VECTOR (131 downto 0);
    signal grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_exp_stream_write : STD_LOGIC;
    signal grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call775 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln155_fu_2629_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component prometheus_soc_emit_exp_stream_Pipeline_exp_emit_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        exp_stream_din : OUT STD_LOGIC_VECTOR (131 downto 0);
        exp_stream_full_n : IN STD_LOGIC;
        exp_stream_write : OUT STD_LOGIC;
        exp_stream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        exp_stream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        blocks_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        n : IN STD_LOGIC_VECTOR (8 downto 0);
        logits_buf_0_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_12_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_13_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_14_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_15_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_16_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_17_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_18_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_21_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_22_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_23_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_24_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_25_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_28_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_29_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_30_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_31_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_32_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_33_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_34_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_35_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_36_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_37_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_38_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_39_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_40_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_41_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_42_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_43_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_44_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_45_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_46_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_47_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_48_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_49_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_50_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_51_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_52_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_53_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_54_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_55_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_56_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_57_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_58_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_59_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_60_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_61_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_62_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_0_63_load : IN STD_LOGIC_VECTOR (31 downto 0);
        max_x : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_12_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_13_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_14_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_15_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_16_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_17_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_18_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_21_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_22_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_23_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_24_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_25_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_28_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_29_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_30_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_31_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_32_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_33_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_34_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_35_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_36_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_37_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_38_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_39_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_40_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_41_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_42_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_43_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_44_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_45_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_46_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_47_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_48_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_49_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_50_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_51_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_52_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_53_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_54_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_55_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_56_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_57_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_58_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_59_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_60_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_61_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_62_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_1_63_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_12_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_13_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_14_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_15_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_16_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_17_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_18_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_21_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_22_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_23_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_24_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_25_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_28_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_29_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_30_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_31_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_32_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_33_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_34_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_35_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_36_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_37_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_38_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_39_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_40_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_41_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_42_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_43_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_44_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_45_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_46_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_47_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_48_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_49_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_50_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_51_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_52_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_53_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_54_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_55_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_56_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_57_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_58_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_59_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_60_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_61_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_62_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_2_63_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_12_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_13_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_14_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_15_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_16_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_17_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_18_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_21_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_22_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_23_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_24_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_25_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_28_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_29_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_30_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_31_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_32_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_33_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_34_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_35_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_36_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_37_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_38_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_39_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_40_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_41_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_42_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_43_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_44_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_45_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_46_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_47_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_48_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_49_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_50_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_51_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_52_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_53_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_54_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_55_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_56_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_57_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_58_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_59_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_60_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_61_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_62_load : IN STD_LOGIC_VECTOR (31 downto 0);
        logits_buf_3_63_load : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106 : component prometheus_soc_emit_exp_stream_Pipeline_exp_emit_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start,
        ap_done => grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done,
        ap_idle => grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_idle,
        ap_ready => grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_ready,
        exp_stream_din => grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_exp_stream_din,
        exp_stream_full_n => exp_stream_full_n,
        exp_stream_write => grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_exp_stream_write,
        exp_stream_num_data_valid => exp_stream_num_data_valid,
        exp_stream_fifo_cap => exp_stream_fifo_cap,
        blocks_cast => blocks_cast_reg_2656,
        n => n_read_reg_2651,
        logits_buf_0_0_load => logits_buf_0_0_read_reg_2661,
        logits_buf_0_1_load => logits_buf_0_1_read_reg_2666,
        logits_buf_0_2_load => logits_buf_0_2_read_reg_2671,
        logits_buf_0_3_load => logits_buf_0_3_read_reg_2676,
        logits_buf_0_4_load => logits_buf_0_4_read_reg_2681,
        logits_buf_0_5_load => logits_buf_0_5_read_reg_2686,
        logits_buf_0_6_load => logits_buf_0_6_read_reg_2691,
        logits_buf_0_7_load => logits_buf_0_7_read_reg_2696,
        logits_buf_0_8_load => logits_buf_0_8_read_reg_2701,
        logits_buf_0_9_load => logits_buf_0_9_read_reg_2706,
        logits_buf_0_10_load => logits_buf_0_10_read_reg_2711,
        logits_buf_0_11_load => logits_buf_0_11_read_reg_2716,
        logits_buf_0_12_load => logits_buf_0_12_read_reg_2721,
        logits_buf_0_13_load => logits_buf_0_13_read_reg_2726,
        logits_buf_0_14_load => logits_buf_0_14_read_reg_2731,
        logits_buf_0_15_load => logits_buf_0_15_read_reg_2736,
        logits_buf_0_16_load => logits_buf_0_16_read_reg_2741,
        logits_buf_0_17_load => logits_buf_0_17_read_reg_2746,
        logits_buf_0_18_load => logits_buf_0_18_read_reg_2751,
        logits_buf_0_19_load => logits_buf_0_19_read_reg_2756,
        logits_buf_0_20_load => logits_buf_0_20_read_reg_2761,
        logits_buf_0_21_load => logits_buf_0_21_read_reg_2766,
        logits_buf_0_22_load => logits_buf_0_22_read_reg_2771,
        logits_buf_0_23_load => logits_buf_0_23_read_reg_2776,
        logits_buf_0_24_load => logits_buf_0_24_read_reg_2781,
        logits_buf_0_25_load => logits_buf_0_25_read_reg_2786,
        logits_buf_0_26_load => logits_buf_0_26_read_reg_2791,
        logits_buf_0_27_load => logits_buf_0_27_read_reg_2796,
        logits_buf_0_28_load => logits_buf_0_28_read_reg_2801,
        logits_buf_0_29_load => logits_buf_0_29_read_reg_2806,
        logits_buf_0_30_load => logits_buf_0_30_read_reg_2811,
        logits_buf_0_31_load => logits_buf_0_31_read_reg_2816,
        logits_buf_0_32_load => logits_buf_0_32_read_reg_2821,
        logits_buf_0_33_load => logits_buf_0_33_read_reg_2826,
        logits_buf_0_34_load => logits_buf_0_34_read_reg_2831,
        logits_buf_0_35_load => logits_buf_0_35_read_reg_2836,
        logits_buf_0_36_load => logits_buf_0_36_read_reg_2841,
        logits_buf_0_37_load => logits_buf_0_37_read_reg_2846,
        logits_buf_0_38_load => logits_buf_0_38_read_reg_2851,
        logits_buf_0_39_load => logits_buf_0_39_read_reg_2856,
        logits_buf_0_40_load => logits_buf_0_40_read_reg_2861,
        logits_buf_0_41_load => logits_buf_0_41_read_reg_2866,
        logits_buf_0_42_load => logits_buf_0_42_read_reg_2871,
        logits_buf_0_43_load => logits_buf_0_43_read_reg_2876,
        logits_buf_0_44_load => logits_buf_0_44_read_reg_2881,
        logits_buf_0_45_load => logits_buf_0_45_read_reg_2886,
        logits_buf_0_46_load => logits_buf_0_46_read_reg_2891,
        logits_buf_0_47_load => logits_buf_0_47_read_reg_2896,
        logits_buf_0_48_load => logits_buf_0_48_read_reg_2901,
        logits_buf_0_49_load => logits_buf_0_49_read_reg_2906,
        logits_buf_0_50_load => logits_buf_0_50_read_reg_2911,
        logits_buf_0_51_load => logits_buf_0_51_read_reg_2916,
        logits_buf_0_52_load => logits_buf_0_52_read_reg_2921,
        logits_buf_0_53_load => logits_buf_0_53_read_reg_2926,
        logits_buf_0_54_load => logits_buf_0_54_read_reg_2931,
        logits_buf_0_55_load => logits_buf_0_55_read_reg_2936,
        logits_buf_0_56_load => logits_buf_0_56_read_reg_2941,
        logits_buf_0_57_load => logits_buf_0_57_read_reg_2946,
        logits_buf_0_58_load => logits_buf_0_58_read_reg_2951,
        logits_buf_0_59_load => logits_buf_0_59_read_reg_2956,
        logits_buf_0_60_load => logits_buf_0_60_read_reg_2961,
        logits_buf_0_61_load => logits_buf_0_61_read_reg_2966,
        logits_buf_0_62_load => logits_buf_0_62_read_reg_2971,
        logits_buf_0_63_load => logits_buf_0_63_read_reg_2976,
        max_x => max_x_read_reg_2646,
        logits_buf_1_0_load => logits_buf_1_0_read_reg_2981,
        logits_buf_1_1_load => logits_buf_1_1_read_reg_2986,
        logits_buf_1_2_load => logits_buf_1_2_read_reg_2991,
        logits_buf_1_3_load => logits_buf_1_3_read_reg_2996,
        logits_buf_1_4_load => logits_buf_1_4_read_reg_3001,
        logits_buf_1_5_load => logits_buf_1_5_read_reg_3006,
        logits_buf_1_6_load => logits_buf_1_6_read_reg_3011,
        logits_buf_1_7_load => logits_buf_1_7_read_reg_3016,
        logits_buf_1_8_load => logits_buf_1_8_read_reg_3021,
        logits_buf_1_9_load => logits_buf_1_9_read_reg_3026,
        logits_buf_1_10_load => logits_buf_1_10_read_reg_3031,
        logits_buf_1_11_load => logits_buf_1_11_read_reg_3036,
        logits_buf_1_12_load => logits_buf_1_12_read_reg_3041,
        logits_buf_1_13_load => logits_buf_1_13_read_reg_3046,
        logits_buf_1_14_load => logits_buf_1_14_read_reg_3051,
        logits_buf_1_15_load => logits_buf_1_15_read_reg_3056,
        logits_buf_1_16_load => logits_buf_1_16_read_reg_3061,
        logits_buf_1_17_load => logits_buf_1_17_read_reg_3066,
        logits_buf_1_18_load => logits_buf_1_18_read_reg_3071,
        logits_buf_1_19_load => logits_buf_1_19_read_reg_3076,
        logits_buf_1_20_load => logits_buf_1_20_read_reg_3081,
        logits_buf_1_21_load => logits_buf_1_21_read_reg_3086,
        logits_buf_1_22_load => logits_buf_1_22_read_reg_3091,
        logits_buf_1_23_load => logits_buf_1_23_read_reg_3096,
        logits_buf_1_24_load => logits_buf_1_24_read_reg_3101,
        logits_buf_1_25_load => logits_buf_1_25_read_reg_3106,
        logits_buf_1_26_load => logits_buf_1_26_read_reg_3111,
        logits_buf_1_27_load => logits_buf_1_27_read_reg_3116,
        logits_buf_1_28_load => logits_buf_1_28_read_reg_3121,
        logits_buf_1_29_load => logits_buf_1_29_read_reg_3126,
        logits_buf_1_30_load => logits_buf_1_30_read_reg_3131,
        logits_buf_1_31_load => logits_buf_1_31_read_reg_3136,
        logits_buf_1_32_load => logits_buf_1_32_read_reg_3141,
        logits_buf_1_33_load => logits_buf_1_33_read_reg_3146,
        logits_buf_1_34_load => logits_buf_1_34_read_reg_3151,
        logits_buf_1_35_load => logits_buf_1_35_read_reg_3156,
        logits_buf_1_36_load => logits_buf_1_36_read_reg_3161,
        logits_buf_1_37_load => logits_buf_1_37_read_reg_3166,
        logits_buf_1_38_load => logits_buf_1_38_read_reg_3171,
        logits_buf_1_39_load => logits_buf_1_39_read_reg_3176,
        logits_buf_1_40_load => logits_buf_1_40_read_reg_3181,
        logits_buf_1_41_load => logits_buf_1_41_read_reg_3186,
        logits_buf_1_42_load => logits_buf_1_42_read_reg_3191,
        logits_buf_1_43_load => logits_buf_1_43_read_reg_3196,
        logits_buf_1_44_load => logits_buf_1_44_read_reg_3201,
        logits_buf_1_45_load => logits_buf_1_45_read_reg_3206,
        logits_buf_1_46_load => logits_buf_1_46_read_reg_3211,
        logits_buf_1_47_load => logits_buf_1_47_read_reg_3216,
        logits_buf_1_48_load => logits_buf_1_48_read_reg_3221,
        logits_buf_1_49_load => logits_buf_1_49_read_reg_3226,
        logits_buf_1_50_load => logits_buf_1_50_read_reg_3231,
        logits_buf_1_51_load => logits_buf_1_51_read_reg_3236,
        logits_buf_1_52_load => logits_buf_1_52_read_reg_3241,
        logits_buf_1_53_load => logits_buf_1_53_read_reg_3246,
        logits_buf_1_54_load => logits_buf_1_54_read_reg_3251,
        logits_buf_1_55_load => logits_buf_1_55_read_reg_3256,
        logits_buf_1_56_load => logits_buf_1_56_read_reg_3261,
        logits_buf_1_57_load => logits_buf_1_57_read_reg_3266,
        logits_buf_1_58_load => logits_buf_1_58_read_reg_3271,
        logits_buf_1_59_load => logits_buf_1_59_read_reg_3276,
        logits_buf_1_60_load => logits_buf_1_60_read_reg_3281,
        logits_buf_1_61_load => logits_buf_1_61_read_reg_3286,
        logits_buf_1_62_load => logits_buf_1_62_read_reg_3291,
        logits_buf_1_63_load => logits_buf_1_63_read_reg_3296,
        logits_buf_2_0_load => logits_buf_2_0_read_reg_3301,
        logits_buf_2_1_load => logits_buf_2_1_read_reg_3306,
        logits_buf_2_2_load => logits_buf_2_2_read_reg_3311,
        logits_buf_2_3_load => logits_buf_2_3_read_reg_3316,
        logits_buf_2_4_load => logits_buf_2_4_read_reg_3321,
        logits_buf_2_5_load => logits_buf_2_5_read_reg_3326,
        logits_buf_2_6_load => logits_buf_2_6_read_reg_3331,
        logits_buf_2_7_load => logits_buf_2_7_read_reg_3336,
        logits_buf_2_8_load => logits_buf_2_8_read_reg_3341,
        logits_buf_2_9_load => logits_buf_2_9_read_reg_3346,
        logits_buf_2_10_load => logits_buf_2_10_read_reg_3351,
        logits_buf_2_11_load => logits_buf_2_11_read_reg_3356,
        logits_buf_2_12_load => logits_buf_2_12_read_reg_3361,
        logits_buf_2_13_load => logits_buf_2_13_read_reg_3366,
        logits_buf_2_14_load => logits_buf_2_14_read_reg_3371,
        logits_buf_2_15_load => logits_buf_2_15_read_reg_3376,
        logits_buf_2_16_load => logits_buf_2_16_read_reg_3381,
        logits_buf_2_17_load => logits_buf_2_17_read_reg_3386,
        logits_buf_2_18_load => logits_buf_2_18_read_reg_3391,
        logits_buf_2_19_load => logits_buf_2_19_read_reg_3396,
        logits_buf_2_20_load => logits_buf_2_20_read_reg_3401,
        logits_buf_2_21_load => logits_buf_2_21_read_reg_3406,
        logits_buf_2_22_load => logits_buf_2_22_read_reg_3411,
        logits_buf_2_23_load => logits_buf_2_23_read_reg_3416,
        logits_buf_2_24_load => logits_buf_2_24_read_reg_3421,
        logits_buf_2_25_load => logits_buf_2_25_read_reg_3426,
        logits_buf_2_26_load => logits_buf_2_26_read_reg_3431,
        logits_buf_2_27_load => logits_buf_2_27_read_reg_3436,
        logits_buf_2_28_load => logits_buf_2_28_read_reg_3441,
        logits_buf_2_29_load => logits_buf_2_29_read_reg_3446,
        logits_buf_2_30_load => logits_buf_2_30_read_reg_3451,
        logits_buf_2_31_load => logits_buf_2_31_read_reg_3456,
        logits_buf_2_32_load => logits_buf_2_32_read_reg_3461,
        logits_buf_2_33_load => logits_buf_2_33_read_reg_3466,
        logits_buf_2_34_load => logits_buf_2_34_read_reg_3471,
        logits_buf_2_35_load => logits_buf_2_35_read_reg_3476,
        logits_buf_2_36_load => logits_buf_2_36_read_reg_3481,
        logits_buf_2_37_load => logits_buf_2_37_read_reg_3486,
        logits_buf_2_38_load => logits_buf_2_38_read_reg_3491,
        logits_buf_2_39_load => logits_buf_2_39_read_reg_3496,
        logits_buf_2_40_load => logits_buf_2_40_read_reg_3501,
        logits_buf_2_41_load => logits_buf_2_41_read_reg_3506,
        logits_buf_2_42_load => logits_buf_2_42_read_reg_3511,
        logits_buf_2_43_load => logits_buf_2_43_read_reg_3516,
        logits_buf_2_44_load => logits_buf_2_44_read_reg_3521,
        logits_buf_2_45_load => logits_buf_2_45_read_reg_3526,
        logits_buf_2_46_load => logits_buf_2_46_read_reg_3531,
        logits_buf_2_47_load => logits_buf_2_47_read_reg_3536,
        logits_buf_2_48_load => logits_buf_2_48_read_reg_3541,
        logits_buf_2_49_load => logits_buf_2_49_read_reg_3546,
        logits_buf_2_50_load => logits_buf_2_50_read_reg_3551,
        logits_buf_2_51_load => logits_buf_2_51_read_reg_3556,
        logits_buf_2_52_load => logits_buf_2_52_read_reg_3561,
        logits_buf_2_53_load => logits_buf_2_53_read_reg_3566,
        logits_buf_2_54_load => logits_buf_2_54_read_reg_3571,
        logits_buf_2_55_load => logits_buf_2_55_read_reg_3576,
        logits_buf_2_56_load => logits_buf_2_56_read_reg_3581,
        logits_buf_2_57_load => logits_buf_2_57_read_reg_3586,
        logits_buf_2_58_load => logits_buf_2_58_read_reg_3591,
        logits_buf_2_59_load => logits_buf_2_59_read_reg_3596,
        logits_buf_2_60_load => logits_buf_2_60_read_reg_3601,
        logits_buf_2_61_load => logits_buf_2_61_read_reg_3606,
        logits_buf_2_62_load => logits_buf_2_62_read_reg_3611,
        logits_buf_2_63_load => logits_buf_2_63_read_reg_3616,
        logits_buf_3_0_load => logits_buf_3_0_read_reg_3621,
        logits_buf_3_1_load => logits_buf_3_1_read_reg_3626,
        logits_buf_3_2_load => logits_buf_3_2_read_reg_3631,
        logits_buf_3_3_load => logits_buf_3_3_read_reg_3636,
        logits_buf_3_4_load => logits_buf_3_4_read_reg_3641,
        logits_buf_3_5_load => logits_buf_3_5_read_reg_3646,
        logits_buf_3_6_load => logits_buf_3_6_read_reg_3651,
        logits_buf_3_7_load => logits_buf_3_7_read_reg_3656,
        logits_buf_3_8_load => logits_buf_3_8_read_reg_3661,
        logits_buf_3_9_load => logits_buf_3_9_read_reg_3666,
        logits_buf_3_10_load => logits_buf_3_10_read_reg_3671,
        logits_buf_3_11_load => logits_buf_3_11_read_reg_3676,
        logits_buf_3_12_load => logits_buf_3_12_read_reg_3681,
        logits_buf_3_13_load => logits_buf_3_13_read_reg_3686,
        logits_buf_3_14_load => logits_buf_3_14_read_reg_3691,
        logits_buf_3_15_load => logits_buf_3_15_read_reg_3696,
        logits_buf_3_16_load => logits_buf_3_16_read_reg_3701,
        logits_buf_3_17_load => logits_buf_3_17_read_reg_3706,
        logits_buf_3_18_load => logits_buf_3_18_read_reg_3711,
        logits_buf_3_19_load => logits_buf_3_19_read_reg_3716,
        logits_buf_3_20_load => logits_buf_3_20_read_reg_3721,
        logits_buf_3_21_load => logits_buf_3_21_read_reg_3726,
        logits_buf_3_22_load => logits_buf_3_22_read_reg_3731,
        logits_buf_3_23_load => logits_buf_3_23_read_reg_3736,
        logits_buf_3_24_load => logits_buf_3_24_read_reg_3741,
        logits_buf_3_25_load => logits_buf_3_25_read_reg_3746,
        logits_buf_3_26_load => logits_buf_3_26_read_reg_3751,
        logits_buf_3_27_load => logits_buf_3_27_read_reg_3756,
        logits_buf_3_28_load => logits_buf_3_28_read_reg_3761,
        logits_buf_3_29_load => logits_buf_3_29_read_reg_3766,
        logits_buf_3_30_load => logits_buf_3_30_read_reg_3771,
        logits_buf_3_31_load => logits_buf_3_31_read_reg_3776,
        logits_buf_3_32_load => logits_buf_3_32_read_reg_3781,
        logits_buf_3_33_load => logits_buf_3_33_read_reg_3786,
        logits_buf_3_34_load => logits_buf_3_34_read_reg_3791,
        logits_buf_3_35_load => logits_buf_3_35_read_reg_3796,
        logits_buf_3_36_load => logits_buf_3_36_read_reg_3801,
        logits_buf_3_37_load => logits_buf_3_37_read_reg_3806,
        logits_buf_3_38_load => logits_buf_3_38_read_reg_3811,
        logits_buf_3_39_load => logits_buf_3_39_read_reg_3816,
        logits_buf_3_40_load => logits_buf_3_40_read_reg_3821,
        logits_buf_3_41_load => logits_buf_3_41_read_reg_3826,
        logits_buf_3_42_load => logits_buf_3_42_read_reg_3831,
        logits_buf_3_43_load => logits_buf_3_43_read_reg_3836,
        logits_buf_3_44_load => logits_buf_3_44_read_reg_3841,
        logits_buf_3_45_load => logits_buf_3_45_read_reg_3846,
        logits_buf_3_46_load => logits_buf_3_46_read_reg_3851,
        logits_buf_3_47_load => logits_buf_3_47_read_reg_3856,
        logits_buf_3_48_load => logits_buf_3_48_read_reg_3861,
        logits_buf_3_49_load => logits_buf_3_49_read_reg_3866,
        logits_buf_3_50_load => logits_buf_3_50_read_reg_3871,
        logits_buf_3_51_load => logits_buf_3_51_read_reg_3876,
        logits_buf_3_52_load => logits_buf_3_52_read_reg_3881,
        logits_buf_3_53_load => logits_buf_3_53_read_reg_3886,
        logits_buf_3_54_load => logits_buf_3_54_read_reg_3891,
        logits_buf_3_55_load => logits_buf_3_55_read_reg_3896,
        logits_buf_3_56_load => logits_buf_3_56_read_reg_3901,
        logits_buf_3_57_load => logits_buf_3_57_read_reg_3906,
        logits_buf_3_58_load => logits_buf_3_58_read_reg_3911,
        logits_buf_3_59_load => logits_buf_3_59_read_reg_3916,
        logits_buf_3_60_load => logits_buf_3_60_read_reg_3921,
        logits_buf_3_61_load => logits_buf_3_61_read_reg_3926,
        logits_buf_3_62_load => logits_buf_3_62_read_reg_3931,
        logits_buf_3_63_load => logits_buf_3_63_read_reg_3936);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call775) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_ready = ap_const_logic_1)) then 
                    grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                blocks_cast_reg_2656 <= add_ln155_fu_2629_p2(8 downto 2);
                logits_buf_0_0_read_reg_2661 <= logits_buf_0_0;
                logits_buf_0_10_read_reg_2711 <= logits_buf_0_10;
                logits_buf_0_11_read_reg_2716 <= logits_buf_0_11;
                logits_buf_0_12_read_reg_2721 <= logits_buf_0_12;
                logits_buf_0_13_read_reg_2726 <= logits_buf_0_13;
                logits_buf_0_14_read_reg_2731 <= logits_buf_0_14;
                logits_buf_0_15_read_reg_2736 <= logits_buf_0_15;
                logits_buf_0_16_read_reg_2741 <= logits_buf_0_16;
                logits_buf_0_17_read_reg_2746 <= logits_buf_0_17;
                logits_buf_0_18_read_reg_2751 <= logits_buf_0_18;
                logits_buf_0_19_read_reg_2756 <= logits_buf_0_19;
                logits_buf_0_1_read_reg_2666 <= logits_buf_0_1;
                logits_buf_0_20_read_reg_2761 <= logits_buf_0_20;
                logits_buf_0_21_read_reg_2766 <= logits_buf_0_21;
                logits_buf_0_22_read_reg_2771 <= logits_buf_0_22;
                logits_buf_0_23_read_reg_2776 <= logits_buf_0_23;
                logits_buf_0_24_read_reg_2781 <= logits_buf_0_24;
                logits_buf_0_25_read_reg_2786 <= logits_buf_0_25;
                logits_buf_0_26_read_reg_2791 <= logits_buf_0_26;
                logits_buf_0_27_read_reg_2796 <= logits_buf_0_27;
                logits_buf_0_28_read_reg_2801 <= logits_buf_0_28;
                logits_buf_0_29_read_reg_2806 <= logits_buf_0_29;
                logits_buf_0_2_read_reg_2671 <= logits_buf_0_2;
                logits_buf_0_30_read_reg_2811 <= logits_buf_0_30;
                logits_buf_0_31_read_reg_2816 <= logits_buf_0_31;
                logits_buf_0_32_read_reg_2821 <= logits_buf_0_32;
                logits_buf_0_33_read_reg_2826 <= logits_buf_0_33;
                logits_buf_0_34_read_reg_2831 <= logits_buf_0_34;
                logits_buf_0_35_read_reg_2836 <= logits_buf_0_35;
                logits_buf_0_36_read_reg_2841 <= logits_buf_0_36;
                logits_buf_0_37_read_reg_2846 <= logits_buf_0_37;
                logits_buf_0_38_read_reg_2851 <= logits_buf_0_38;
                logits_buf_0_39_read_reg_2856 <= logits_buf_0_39;
                logits_buf_0_3_read_reg_2676 <= logits_buf_0_3;
                logits_buf_0_40_read_reg_2861 <= logits_buf_0_40;
                logits_buf_0_41_read_reg_2866 <= logits_buf_0_41;
                logits_buf_0_42_read_reg_2871 <= logits_buf_0_42;
                logits_buf_0_43_read_reg_2876 <= logits_buf_0_43;
                logits_buf_0_44_read_reg_2881 <= logits_buf_0_44;
                logits_buf_0_45_read_reg_2886 <= logits_buf_0_45;
                logits_buf_0_46_read_reg_2891 <= logits_buf_0_46;
                logits_buf_0_47_read_reg_2896 <= logits_buf_0_47;
                logits_buf_0_48_read_reg_2901 <= logits_buf_0_48;
                logits_buf_0_49_read_reg_2906 <= logits_buf_0_49;
                logits_buf_0_4_read_reg_2681 <= logits_buf_0_4;
                logits_buf_0_50_read_reg_2911 <= logits_buf_0_50;
                logits_buf_0_51_read_reg_2916 <= logits_buf_0_51;
                logits_buf_0_52_read_reg_2921 <= logits_buf_0_52;
                logits_buf_0_53_read_reg_2926 <= logits_buf_0_53;
                logits_buf_0_54_read_reg_2931 <= logits_buf_0_54;
                logits_buf_0_55_read_reg_2936 <= logits_buf_0_55;
                logits_buf_0_56_read_reg_2941 <= logits_buf_0_56;
                logits_buf_0_57_read_reg_2946 <= logits_buf_0_57;
                logits_buf_0_58_read_reg_2951 <= logits_buf_0_58;
                logits_buf_0_59_read_reg_2956 <= logits_buf_0_59;
                logits_buf_0_5_read_reg_2686 <= logits_buf_0_5;
                logits_buf_0_60_read_reg_2961 <= logits_buf_0_60;
                logits_buf_0_61_read_reg_2966 <= logits_buf_0_61;
                logits_buf_0_62_read_reg_2971 <= logits_buf_0_62;
                logits_buf_0_63_read_reg_2976 <= logits_buf_0_63;
                logits_buf_0_6_read_reg_2691 <= logits_buf_0_6;
                logits_buf_0_7_read_reg_2696 <= logits_buf_0_7;
                logits_buf_0_8_read_reg_2701 <= logits_buf_0_8;
                logits_buf_0_9_read_reg_2706 <= logits_buf_0_9;
                logits_buf_1_0_read_reg_2981 <= logits_buf_1_0;
                logits_buf_1_10_read_reg_3031 <= logits_buf_1_10;
                logits_buf_1_11_read_reg_3036 <= logits_buf_1_11;
                logits_buf_1_12_read_reg_3041 <= logits_buf_1_12;
                logits_buf_1_13_read_reg_3046 <= logits_buf_1_13;
                logits_buf_1_14_read_reg_3051 <= logits_buf_1_14;
                logits_buf_1_15_read_reg_3056 <= logits_buf_1_15;
                logits_buf_1_16_read_reg_3061 <= logits_buf_1_16;
                logits_buf_1_17_read_reg_3066 <= logits_buf_1_17;
                logits_buf_1_18_read_reg_3071 <= logits_buf_1_18;
                logits_buf_1_19_read_reg_3076 <= logits_buf_1_19;
                logits_buf_1_1_read_reg_2986 <= logits_buf_1_1;
                logits_buf_1_20_read_reg_3081 <= logits_buf_1_20;
                logits_buf_1_21_read_reg_3086 <= logits_buf_1_21;
                logits_buf_1_22_read_reg_3091 <= logits_buf_1_22;
                logits_buf_1_23_read_reg_3096 <= logits_buf_1_23;
                logits_buf_1_24_read_reg_3101 <= logits_buf_1_24;
                logits_buf_1_25_read_reg_3106 <= logits_buf_1_25;
                logits_buf_1_26_read_reg_3111 <= logits_buf_1_26;
                logits_buf_1_27_read_reg_3116 <= logits_buf_1_27;
                logits_buf_1_28_read_reg_3121 <= logits_buf_1_28;
                logits_buf_1_29_read_reg_3126 <= logits_buf_1_29;
                logits_buf_1_2_read_reg_2991 <= logits_buf_1_2;
                logits_buf_1_30_read_reg_3131 <= logits_buf_1_30;
                logits_buf_1_31_read_reg_3136 <= logits_buf_1_31;
                logits_buf_1_32_read_reg_3141 <= logits_buf_1_32;
                logits_buf_1_33_read_reg_3146 <= logits_buf_1_33;
                logits_buf_1_34_read_reg_3151 <= logits_buf_1_34;
                logits_buf_1_35_read_reg_3156 <= logits_buf_1_35;
                logits_buf_1_36_read_reg_3161 <= logits_buf_1_36;
                logits_buf_1_37_read_reg_3166 <= logits_buf_1_37;
                logits_buf_1_38_read_reg_3171 <= logits_buf_1_38;
                logits_buf_1_39_read_reg_3176 <= logits_buf_1_39;
                logits_buf_1_3_read_reg_2996 <= logits_buf_1_3;
                logits_buf_1_40_read_reg_3181 <= logits_buf_1_40;
                logits_buf_1_41_read_reg_3186 <= logits_buf_1_41;
                logits_buf_1_42_read_reg_3191 <= logits_buf_1_42;
                logits_buf_1_43_read_reg_3196 <= logits_buf_1_43;
                logits_buf_1_44_read_reg_3201 <= logits_buf_1_44;
                logits_buf_1_45_read_reg_3206 <= logits_buf_1_45;
                logits_buf_1_46_read_reg_3211 <= logits_buf_1_46;
                logits_buf_1_47_read_reg_3216 <= logits_buf_1_47;
                logits_buf_1_48_read_reg_3221 <= logits_buf_1_48;
                logits_buf_1_49_read_reg_3226 <= logits_buf_1_49;
                logits_buf_1_4_read_reg_3001 <= logits_buf_1_4;
                logits_buf_1_50_read_reg_3231 <= logits_buf_1_50;
                logits_buf_1_51_read_reg_3236 <= logits_buf_1_51;
                logits_buf_1_52_read_reg_3241 <= logits_buf_1_52;
                logits_buf_1_53_read_reg_3246 <= logits_buf_1_53;
                logits_buf_1_54_read_reg_3251 <= logits_buf_1_54;
                logits_buf_1_55_read_reg_3256 <= logits_buf_1_55;
                logits_buf_1_56_read_reg_3261 <= logits_buf_1_56;
                logits_buf_1_57_read_reg_3266 <= logits_buf_1_57;
                logits_buf_1_58_read_reg_3271 <= logits_buf_1_58;
                logits_buf_1_59_read_reg_3276 <= logits_buf_1_59;
                logits_buf_1_5_read_reg_3006 <= logits_buf_1_5;
                logits_buf_1_60_read_reg_3281 <= logits_buf_1_60;
                logits_buf_1_61_read_reg_3286 <= logits_buf_1_61;
                logits_buf_1_62_read_reg_3291 <= logits_buf_1_62;
                logits_buf_1_63_read_reg_3296 <= logits_buf_1_63;
                logits_buf_1_6_read_reg_3011 <= logits_buf_1_6;
                logits_buf_1_7_read_reg_3016 <= logits_buf_1_7;
                logits_buf_1_8_read_reg_3021 <= logits_buf_1_8;
                logits_buf_1_9_read_reg_3026 <= logits_buf_1_9;
                logits_buf_2_0_read_reg_3301 <= logits_buf_2_0;
                logits_buf_2_10_read_reg_3351 <= logits_buf_2_10;
                logits_buf_2_11_read_reg_3356 <= logits_buf_2_11;
                logits_buf_2_12_read_reg_3361 <= logits_buf_2_12;
                logits_buf_2_13_read_reg_3366 <= logits_buf_2_13;
                logits_buf_2_14_read_reg_3371 <= logits_buf_2_14;
                logits_buf_2_15_read_reg_3376 <= logits_buf_2_15;
                logits_buf_2_16_read_reg_3381 <= logits_buf_2_16;
                logits_buf_2_17_read_reg_3386 <= logits_buf_2_17;
                logits_buf_2_18_read_reg_3391 <= logits_buf_2_18;
                logits_buf_2_19_read_reg_3396 <= logits_buf_2_19;
                logits_buf_2_1_read_reg_3306 <= logits_buf_2_1;
                logits_buf_2_20_read_reg_3401 <= logits_buf_2_20;
                logits_buf_2_21_read_reg_3406 <= logits_buf_2_21;
                logits_buf_2_22_read_reg_3411 <= logits_buf_2_22;
                logits_buf_2_23_read_reg_3416 <= logits_buf_2_23;
                logits_buf_2_24_read_reg_3421 <= logits_buf_2_24;
                logits_buf_2_25_read_reg_3426 <= logits_buf_2_25;
                logits_buf_2_26_read_reg_3431 <= logits_buf_2_26;
                logits_buf_2_27_read_reg_3436 <= logits_buf_2_27;
                logits_buf_2_28_read_reg_3441 <= logits_buf_2_28;
                logits_buf_2_29_read_reg_3446 <= logits_buf_2_29;
                logits_buf_2_2_read_reg_3311 <= logits_buf_2_2;
                logits_buf_2_30_read_reg_3451 <= logits_buf_2_30;
                logits_buf_2_31_read_reg_3456 <= logits_buf_2_31;
                logits_buf_2_32_read_reg_3461 <= logits_buf_2_32;
                logits_buf_2_33_read_reg_3466 <= logits_buf_2_33;
                logits_buf_2_34_read_reg_3471 <= logits_buf_2_34;
                logits_buf_2_35_read_reg_3476 <= logits_buf_2_35;
                logits_buf_2_36_read_reg_3481 <= logits_buf_2_36;
                logits_buf_2_37_read_reg_3486 <= logits_buf_2_37;
                logits_buf_2_38_read_reg_3491 <= logits_buf_2_38;
                logits_buf_2_39_read_reg_3496 <= logits_buf_2_39;
                logits_buf_2_3_read_reg_3316 <= logits_buf_2_3;
                logits_buf_2_40_read_reg_3501 <= logits_buf_2_40;
                logits_buf_2_41_read_reg_3506 <= logits_buf_2_41;
                logits_buf_2_42_read_reg_3511 <= logits_buf_2_42;
                logits_buf_2_43_read_reg_3516 <= logits_buf_2_43;
                logits_buf_2_44_read_reg_3521 <= logits_buf_2_44;
                logits_buf_2_45_read_reg_3526 <= logits_buf_2_45;
                logits_buf_2_46_read_reg_3531 <= logits_buf_2_46;
                logits_buf_2_47_read_reg_3536 <= logits_buf_2_47;
                logits_buf_2_48_read_reg_3541 <= logits_buf_2_48;
                logits_buf_2_49_read_reg_3546 <= logits_buf_2_49;
                logits_buf_2_4_read_reg_3321 <= logits_buf_2_4;
                logits_buf_2_50_read_reg_3551 <= logits_buf_2_50;
                logits_buf_2_51_read_reg_3556 <= logits_buf_2_51;
                logits_buf_2_52_read_reg_3561 <= logits_buf_2_52;
                logits_buf_2_53_read_reg_3566 <= logits_buf_2_53;
                logits_buf_2_54_read_reg_3571 <= logits_buf_2_54;
                logits_buf_2_55_read_reg_3576 <= logits_buf_2_55;
                logits_buf_2_56_read_reg_3581 <= logits_buf_2_56;
                logits_buf_2_57_read_reg_3586 <= logits_buf_2_57;
                logits_buf_2_58_read_reg_3591 <= logits_buf_2_58;
                logits_buf_2_59_read_reg_3596 <= logits_buf_2_59;
                logits_buf_2_5_read_reg_3326 <= logits_buf_2_5;
                logits_buf_2_60_read_reg_3601 <= logits_buf_2_60;
                logits_buf_2_61_read_reg_3606 <= logits_buf_2_61;
                logits_buf_2_62_read_reg_3611 <= logits_buf_2_62;
                logits_buf_2_63_read_reg_3616 <= logits_buf_2_63;
                logits_buf_2_6_read_reg_3331 <= logits_buf_2_6;
                logits_buf_2_7_read_reg_3336 <= logits_buf_2_7;
                logits_buf_2_8_read_reg_3341 <= logits_buf_2_8;
                logits_buf_2_9_read_reg_3346 <= logits_buf_2_9;
                logits_buf_3_0_read_reg_3621 <= logits_buf_3_0;
                logits_buf_3_10_read_reg_3671 <= logits_buf_3_10;
                logits_buf_3_11_read_reg_3676 <= logits_buf_3_11;
                logits_buf_3_12_read_reg_3681 <= logits_buf_3_12;
                logits_buf_3_13_read_reg_3686 <= logits_buf_3_13;
                logits_buf_3_14_read_reg_3691 <= logits_buf_3_14;
                logits_buf_3_15_read_reg_3696 <= logits_buf_3_15;
                logits_buf_3_16_read_reg_3701 <= logits_buf_3_16;
                logits_buf_3_17_read_reg_3706 <= logits_buf_3_17;
                logits_buf_3_18_read_reg_3711 <= logits_buf_3_18;
                logits_buf_3_19_read_reg_3716 <= logits_buf_3_19;
                logits_buf_3_1_read_reg_3626 <= logits_buf_3_1;
                logits_buf_3_20_read_reg_3721 <= logits_buf_3_20;
                logits_buf_3_21_read_reg_3726 <= logits_buf_3_21;
                logits_buf_3_22_read_reg_3731 <= logits_buf_3_22;
                logits_buf_3_23_read_reg_3736 <= logits_buf_3_23;
                logits_buf_3_24_read_reg_3741 <= logits_buf_3_24;
                logits_buf_3_25_read_reg_3746 <= logits_buf_3_25;
                logits_buf_3_26_read_reg_3751 <= logits_buf_3_26;
                logits_buf_3_27_read_reg_3756 <= logits_buf_3_27;
                logits_buf_3_28_read_reg_3761 <= logits_buf_3_28;
                logits_buf_3_29_read_reg_3766 <= logits_buf_3_29;
                logits_buf_3_2_read_reg_3631 <= logits_buf_3_2;
                logits_buf_3_30_read_reg_3771 <= logits_buf_3_30;
                logits_buf_3_31_read_reg_3776 <= logits_buf_3_31;
                logits_buf_3_32_read_reg_3781 <= logits_buf_3_32;
                logits_buf_3_33_read_reg_3786 <= logits_buf_3_33;
                logits_buf_3_34_read_reg_3791 <= logits_buf_3_34;
                logits_buf_3_35_read_reg_3796 <= logits_buf_3_35;
                logits_buf_3_36_read_reg_3801 <= logits_buf_3_36;
                logits_buf_3_37_read_reg_3806 <= logits_buf_3_37;
                logits_buf_3_38_read_reg_3811 <= logits_buf_3_38;
                logits_buf_3_39_read_reg_3816 <= logits_buf_3_39;
                logits_buf_3_3_read_reg_3636 <= logits_buf_3_3;
                logits_buf_3_40_read_reg_3821 <= logits_buf_3_40;
                logits_buf_3_41_read_reg_3826 <= logits_buf_3_41;
                logits_buf_3_42_read_reg_3831 <= logits_buf_3_42;
                logits_buf_3_43_read_reg_3836 <= logits_buf_3_43;
                logits_buf_3_44_read_reg_3841 <= logits_buf_3_44;
                logits_buf_3_45_read_reg_3846 <= logits_buf_3_45;
                logits_buf_3_46_read_reg_3851 <= logits_buf_3_46;
                logits_buf_3_47_read_reg_3856 <= logits_buf_3_47;
                logits_buf_3_48_read_reg_3861 <= logits_buf_3_48;
                logits_buf_3_49_read_reg_3866 <= logits_buf_3_49;
                logits_buf_3_4_read_reg_3641 <= logits_buf_3_4;
                logits_buf_3_50_read_reg_3871 <= logits_buf_3_50;
                logits_buf_3_51_read_reg_3876 <= logits_buf_3_51;
                logits_buf_3_52_read_reg_3881 <= logits_buf_3_52;
                logits_buf_3_53_read_reg_3886 <= logits_buf_3_53;
                logits_buf_3_54_read_reg_3891 <= logits_buf_3_54;
                logits_buf_3_55_read_reg_3896 <= logits_buf_3_55;
                logits_buf_3_56_read_reg_3901 <= logits_buf_3_56;
                logits_buf_3_57_read_reg_3906 <= logits_buf_3_57;
                logits_buf_3_58_read_reg_3911 <= logits_buf_3_58;
                logits_buf_3_59_read_reg_3916 <= logits_buf_3_59;
                logits_buf_3_5_read_reg_3646 <= logits_buf_3_5;
                logits_buf_3_60_read_reg_3921 <= logits_buf_3_60;
                logits_buf_3_61_read_reg_3926 <= logits_buf_3_61;
                logits_buf_3_62_read_reg_3931 <= logits_buf_3_62;
                logits_buf_3_63_read_reg_3936 <= logits_buf_3_63;
                logits_buf_3_6_read_reg_3651 <= logits_buf_3_6;
                logits_buf_3_7_read_reg_3656 <= logits_buf_3_7;
                logits_buf_3_8_read_reg_3661 <= logits_buf_3_8;
                logits_buf_3_9_read_reg_3666 <= logits_buf_3_9;
                max_x_read_reg_2646 <= max_x;
                n_read_reg_2651 <= n;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln155_fu_2629_p2 <= std_logic_vector(unsigned(n) + unsigned(ap_const_lv9_3));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done)
    begin
        if ((grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call775_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call775 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    exp_stream_din <= grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_exp_stream_din;
    exp_stream_write <= grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_exp_stream_write;
    grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start <= grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_start_reg;

    internal_ap_ready_assign_proc : process(grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_emit_exp_stream_Pipeline_exp_emit_loop_fu_2106_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
