-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity softmax_accel_load_logits_and_find_max_Pipeline_load_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    blocks : IN STD_LOGIC_VECTOR (6 downto 0);
    n : IN STD_LOGIC_VECTOR (8 downto 0);
    sext_ln204 : IN STD_LOGIC_VECTOR (59 downto 0);
    logits_buf_3_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    logits_buf_3_ce1 : OUT STD_LOGIC;
    logits_buf_3_we1 : OUT STD_LOGIC;
    logits_buf_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_2_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    logits_buf_2_ce1 : OUT STD_LOGIC;
    logits_buf_2_we1 : OUT STD_LOGIC;
    logits_buf_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_1_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    logits_buf_1_ce1 : OUT STD_LOGIC;
    logits_buf_1_we1 : OUT STD_LOGIC;
    logits_buf_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    logits_buf_0_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    logits_buf_0_ce1 : OUT STD_LOGIC;
    logits_buf_0_we1 : OUT STD_LOGIC;
    logits_buf_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    max_x_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    max_x_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of softmax_accel_load_logits_and_find_max_Pipeline_load_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln204_reg_657 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln204_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal blk_2_reg_651 : STD_LOGIC_VECTOR (6 downto 0);
    signal blk_2_reg_651_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln204_reg_657_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln204_reg_657_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln215_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln215_reg_661 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln215_reg_661_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln220_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln220_reg_665 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln220_reg_665_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln220_reg_665_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln225_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln225_reg_669 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln225_reg_669_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln225_reg_669_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_673 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_673_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_673_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_reg_677 : STD_LOGIC_VECTOR (127 downto 0);
    signal x0_fu_423_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln237_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln237_reg_705 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln237_reg_705_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal local_max_fu_594_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_max_reg_710 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_keep_reg_216 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_keep_reg_216 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_keep_reg_216 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter3_keep_reg_216 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_x0_1_reg_229 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_x0_1_reg_229 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_x0_1_reg_229 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_x0_1_reg_229 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_keep_1_phi_fu_243_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal keep_4_fu_461_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter3_keep_1_reg_240 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln210_fu_456_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_x1_1_reg_249 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_x1_1_reg_249 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_x1_1_reg_249 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_x1_1_reg_249 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_keep_2_phi_fu_263_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal keep_5_fu_475_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter3_keep_2_reg_260 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln211_fu_470_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_x2_1_reg_269 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_x2_1_reg_269 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_x2_1_reg_269 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_x2_1_reg_269 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_keep_3_phi_fu_283_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal keep_6_fu_489_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_reg_pp0_iter3_keep_3_reg_280 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln212_fu_484_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_reg_pp0_iter0_x3_1_reg_289 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_x3_1_reg_289 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_x3_1_reg_289 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_x3_1_reg_289 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln204_fu_416_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal max_x_fu_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_x_2_fu_615_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal blk_fu_114 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln204_fu_323_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_blk_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal logits_buf_0_we1_local : STD_LOGIC;
    signal logits_buf_0_ce1_local : STD_LOGIC;
    signal logits_buf_1_we1_local : STD_LOGIC;
    signal logits_buf_1_ce1_local : STD_LOGIC;
    signal logits_buf_2_we1_local : STD_LOGIC;
    signal logits_buf_2_ce1_local : STD_LOGIC;
    signal logits_buf_3_we1_local : STD_LOGIC;
    signal logits_buf_3_ce1_local : STD_LOGIC;
    signal trunc_ln206_fu_329_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln2_fu_333_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln207_fu_341_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln_fu_351_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln220_fu_359_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln1_fu_369_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln225_fu_377_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln2_fu_387_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln230_fu_395_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln141_fu_500_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_512_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_72_fu_528_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_73_fu_544_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal m0_fu_504_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m1_fu_520_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln146_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m2_fu_536_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m3_fu_552_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln147_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m01_fu_566_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m23_fu_580_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln148_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln237_1_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln237_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_251 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component softmax_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component softmax_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_keep_reg_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_251)) then
                if (((icmp_ln215_fu_345_p2 = ap_const_lv1_0) and (icmp_ln204_fu_317_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_keep_reg_216 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_keep_reg_216 <= ap_phi_reg_pp0_iter0_keep_reg_216;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_x0_1_reg_229_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_251)) then
                if (((icmp_ln215_fu_345_p2 = ap_const_lv1_0) and (icmp_ln204_fu_317_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_x0_1_reg_229 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_x0_1_reg_229 <= ap_phi_reg_pp0_iter0_x0_1_reg_229;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_x1_1_reg_249_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_251)) then
                if (((icmp_ln220_fu_363_p2 = ap_const_lv1_0) and (icmp_ln204_fu_317_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_x1_1_reg_249 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_x1_1_reg_249 <= ap_phi_reg_pp0_iter0_x1_1_reg_249;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_x2_1_reg_269_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_251)) then
                if (((icmp_ln225_fu_381_p2 = ap_const_lv1_0) and (icmp_ln204_fu_317_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_x2_1_reg_269 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_x2_1_reg_269 <= ap_phi_reg_pp0_iter0_x2_1_reg_269;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_x3_1_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_251)) then
                if (((icmp_ln230_fu_399_p2 = ap_const_lv1_0) and (icmp_ln204_fu_317_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_x3_1_reg_289 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_x3_1_reg_289 <= ap_phi_reg_pp0_iter0_x3_1_reg_289;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_keep_reg_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln215_reg_661_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_keep_reg_216 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_keep_reg_216 <= ap_phi_reg_pp0_iter2_keep_reg_216;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_x0_1_reg_229_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln215_reg_661_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_x0_1_reg_229 <= x0_fu_423_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_x0_1_reg_229 <= ap_phi_reg_pp0_iter2_x0_1_reg_229;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_x1_1_reg_249_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln220_reg_665_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_x1_1_reg_249 <= line_reg_677(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_x1_1_reg_249 <= ap_phi_reg_pp0_iter2_x1_1_reg_249;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_x2_1_reg_269_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln225_reg_669_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_x2_1_reg_269 <= line_reg_677(95 downto 64);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_x2_1_reg_269 <= ap_phi_reg_pp0_iter2_x2_1_reg_269;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_x3_1_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln230_reg_673_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_x3_1_reg_289 <= line_reg_677(127 downto 96);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_x3_1_reg_289 <= ap_phi_reg_pp0_iter2_x3_1_reg_289;
                end if;
            end if; 
        end if;
    end process;

    blk_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln204_fu_317_p2 = ap_const_lv1_0))) then 
                    blk_fu_114 <= add_ln204_fu_323_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    blk_fu_114 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    max_x_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    max_x_fu_110 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    max_x_fu_110 <= max_x_2_fu_615_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                blk_2_reg_651 <= ap_sig_allocacmp_blk_2;
                blk_2_reg_651_pp0_iter1_reg <= blk_2_reg_651;
                icmp_ln204_reg_657 <= icmp_ln204_fu_317_p2;
                icmp_ln204_reg_657_pp0_iter1_reg <= icmp_ln204_reg_657;
                icmp_ln215_reg_661 <= icmp_ln215_fu_345_p2;
                icmp_ln215_reg_661_pp0_iter1_reg <= icmp_ln215_reg_661;
                icmp_ln220_reg_665 <= icmp_ln220_fu_363_p2;
                icmp_ln220_reg_665_pp0_iter1_reg <= icmp_ln220_reg_665;
                icmp_ln225_reg_669 <= icmp_ln225_fu_381_p2;
                icmp_ln225_reg_669_pp0_iter1_reg <= icmp_ln225_reg_669;
                icmp_ln230_reg_673 <= icmp_ln230_fu_399_p2;
                icmp_ln230_reg_673_pp0_iter1_reg <= icmp_ln230_reg_673;
                line_reg_677 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln204_reg_657_pp0_iter2_reg <= icmp_ln204_reg_657_pp0_iter1_reg;
                icmp_ln220_reg_665_pp0_iter2_reg <= icmp_ln220_reg_665_pp0_iter1_reg;
                icmp_ln225_reg_669_pp0_iter2_reg <= icmp_ln225_reg_669_pp0_iter1_reg;
                icmp_ln230_reg_673_pp0_iter2_reg <= icmp_ln230_reg_673_pp0_iter1_reg;
                local_max_reg_710 <= local_max_fu_594_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter2_keep_reg_216 <= ap_phi_reg_pp0_iter1_keep_reg_216;
                ap_phi_reg_pp0_iter2_x0_1_reg_229 <= ap_phi_reg_pp0_iter1_x0_1_reg_229;
                ap_phi_reg_pp0_iter2_x1_1_reg_249 <= ap_phi_reg_pp0_iter1_x1_1_reg_249;
                ap_phi_reg_pp0_iter2_x2_1_reg_269 <= ap_phi_reg_pp0_iter1_x2_1_reg_269;
                ap_phi_reg_pp0_iter2_x3_1_reg_289 <= ap_phi_reg_pp0_iter1_x3_1_reg_289;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                icmp_ln237_reg_705 <= icmp_ln237_fu_451_p2;
                icmp_ln237_reg_705_pp0_iter3_reg <= icmp_ln237_reg_705;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln204_fu_323_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_blk_2) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem_0_RVALID, icmp_ln204_reg_657)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln204_reg_657 = ap_const_lv1_0) and (m_axi_gmem_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_251_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_251 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln204_fu_317_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln204_fu_317_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_keep_1_phi_fu_243_p4_assign_proc : process(icmp_ln204_reg_657_pp0_iter2_reg, icmp_ln220_reg_665_pp0_iter2_reg, keep_4_fu_461_p3, ap_phi_reg_pp0_iter3_keep_1_reg_240, zext_ln210_fu_456_p1)
    begin
        if ((icmp_ln204_reg_657_pp0_iter2_reg = ap_const_lv1_0)) then
            if ((icmp_ln220_reg_665_pp0_iter2_reg = ap_const_lv1_0)) then 
                ap_phi_mux_keep_1_phi_fu_243_p4 <= zext_ln210_fu_456_p1;
            elsif ((icmp_ln220_reg_665_pp0_iter2_reg = ap_const_lv1_1)) then 
                ap_phi_mux_keep_1_phi_fu_243_p4 <= keep_4_fu_461_p3;
            else 
                ap_phi_mux_keep_1_phi_fu_243_p4 <= ap_phi_reg_pp0_iter3_keep_1_reg_240;
            end if;
        else 
            ap_phi_mux_keep_1_phi_fu_243_p4 <= ap_phi_reg_pp0_iter3_keep_1_reg_240;
        end if; 
    end process;


    ap_phi_mux_keep_2_phi_fu_263_p4_assign_proc : process(icmp_ln204_reg_657_pp0_iter2_reg, icmp_ln225_reg_669_pp0_iter2_reg, keep_5_fu_475_p3, ap_phi_reg_pp0_iter3_keep_2_reg_260, zext_ln211_fu_470_p1)
    begin
        if ((icmp_ln204_reg_657_pp0_iter2_reg = ap_const_lv1_0)) then
            if ((icmp_ln225_reg_669_pp0_iter2_reg = ap_const_lv1_0)) then 
                ap_phi_mux_keep_2_phi_fu_263_p4 <= zext_ln211_fu_470_p1;
            elsif ((icmp_ln225_reg_669_pp0_iter2_reg = ap_const_lv1_1)) then 
                ap_phi_mux_keep_2_phi_fu_263_p4 <= keep_5_fu_475_p3;
            else 
                ap_phi_mux_keep_2_phi_fu_263_p4 <= ap_phi_reg_pp0_iter3_keep_2_reg_260;
            end if;
        else 
            ap_phi_mux_keep_2_phi_fu_263_p4 <= ap_phi_reg_pp0_iter3_keep_2_reg_260;
        end if; 
    end process;


    ap_phi_mux_keep_3_phi_fu_283_p4_assign_proc : process(icmp_ln204_reg_657_pp0_iter2_reg, icmp_ln230_reg_673_pp0_iter2_reg, keep_6_fu_489_p4, ap_phi_reg_pp0_iter3_keep_3_reg_280, zext_ln212_fu_484_p1)
    begin
        if ((icmp_ln204_reg_657_pp0_iter2_reg = ap_const_lv1_0)) then
            if ((icmp_ln230_reg_673_pp0_iter2_reg = ap_const_lv1_0)) then 
                ap_phi_mux_keep_3_phi_fu_283_p4 <= zext_ln212_fu_484_p1;
            elsif ((icmp_ln230_reg_673_pp0_iter2_reg = ap_const_lv1_1)) then 
                ap_phi_mux_keep_3_phi_fu_283_p4 <= keep_6_fu_489_p4;
            else 
                ap_phi_mux_keep_3_phi_fu_283_p4 <= ap_phi_reg_pp0_iter3_keep_3_reg_280;
            end if;
        else 
            ap_phi_mux_keep_3_phi_fu_283_p4 <= ap_phi_reg_pp0_iter3_keep_3_reg_280;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_keep_reg_216 <= "X";
    ap_phi_reg_pp0_iter0_x0_1_reg_229 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_x1_1_reg_249 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_x2_1_reg_269 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_x3_1_reg_289 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_keep_1_reg_240 <= "XX";
    ap_phi_reg_pp0_iter3_keep_2_reg_260 <= "XXX";
    ap_phi_reg_pp0_iter3_keep_3_reg_280 <= "XXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_blk_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, blk_fu_114)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_blk_2 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_blk_2 <= blk_fu_114;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_0_RVALID, icmp_ln204_reg_657, ap_block_pp0_stage0)
    begin
        if (((icmp_ln204_reg_657 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem_blk_n_R <= m_axi_gmem_0_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln146_fu_560_p2 <= "1" when (signed(m0_fu_504_p3) > signed(m1_fu_520_p3)) else "0";
    icmp_ln147_fu_574_p2 <= "1" when (signed(m2_fu_536_p3) > signed(m3_fu_552_p3)) else "0";
    icmp_ln148_fu_588_p2 <= "1" when (signed(m01_fu_566_p3) > signed(m23_fu_580_p3)) else "0";
    icmp_ln204_fu_317_p2 <= "1" when (ap_sig_allocacmp_blk_2 = blocks) else "0";
    icmp_ln215_fu_345_p2 <= "1" when (unsigned(zext_ln207_fu_341_p1) < unsigned(n)) else "0";
    icmp_ln220_fu_363_p2 <= "1" when (unsigned(zext_ln220_fu_359_p1) < unsigned(n)) else "0";
    icmp_ln225_fu_381_p2 <= "1" when (unsigned(zext_ln225_fu_377_p1) < unsigned(n)) else "0";
    icmp_ln230_fu_399_p2 <= "1" when (unsigned(zext_ln230_fu_395_p1) < unsigned(n)) else "0";
    icmp_ln237_1_fu_605_p2 <= "1" when (signed(local_max_reg_710) > signed(max_x_fu_110)) else "0";
    icmp_ln237_fu_451_p2 <= "1" when (blk_2_reg_651_pp0_iter1_reg = ap_const_lv7_0) else "0";
    keep_4_fu_461_p3 <= (ap_const_lv1_1 & ap_phi_reg_pp0_iter3_keep_reg_216);
    keep_5_fu_475_p3 <= (ap_const_lv1_1 & ap_phi_mux_keep_1_phi_fu_243_p4);
    
    keep_6_fu_489_p4_proc : process(zext_ln212_fu_484_p1)
    begin
        keep_6_fu_489_p4 <= zext_ln212_fu_484_p1;
        keep_6_fu_489_p4(3) <= ap_const_lv1_1(0);
    end process;

    local_max_fu_594_p3 <= 
        m01_fu_566_p3 when (icmp_ln148_fu_588_p2(0) = '1') else 
        m23_fu_580_p3;
    logits_buf_0_address1 <= zext_ln204_fu_416_p1(6 - 1 downto 0);
    logits_buf_0_ce1 <= logits_buf_0_ce1_local;

    logits_buf_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            logits_buf_0_ce1_local <= ap_const_logic_1;
        else 
            logits_buf_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    logits_buf_0_d1 <= x0_fu_423_p1;
    logits_buf_0_we1 <= logits_buf_0_we1_local;

    logits_buf_0_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln204_reg_657_pp0_iter1_reg, icmp_ln215_reg_661_pp0_iter1_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln215_reg_661_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            logits_buf_0_we1_local <= ap_const_logic_1;
        else 
            logits_buf_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    logits_buf_1_address1 <= zext_ln204_fu_416_p1(6 - 1 downto 0);
    logits_buf_1_ce1 <= logits_buf_1_ce1_local;

    logits_buf_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            logits_buf_1_ce1_local <= ap_const_logic_1;
        else 
            logits_buf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    logits_buf_1_d1 <= line_reg_677(63 downto 32);
    logits_buf_1_we1 <= logits_buf_1_we1_local;

    logits_buf_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln204_reg_657_pp0_iter1_reg, icmp_ln220_reg_665_pp0_iter1_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln220_reg_665_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            logits_buf_1_we1_local <= ap_const_logic_1;
        else 
            logits_buf_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    logits_buf_2_address1 <= zext_ln204_fu_416_p1(6 - 1 downto 0);
    logits_buf_2_ce1 <= logits_buf_2_ce1_local;

    logits_buf_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            logits_buf_2_ce1_local <= ap_const_logic_1;
        else 
            logits_buf_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    logits_buf_2_d1 <= line_reg_677(95 downto 64);
    logits_buf_2_we1 <= logits_buf_2_we1_local;

    logits_buf_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln204_reg_657_pp0_iter1_reg, icmp_ln225_reg_669_pp0_iter1_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln225_reg_669_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            logits_buf_2_we1_local <= ap_const_logic_1;
        else 
            logits_buf_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    logits_buf_3_address1 <= zext_ln204_fu_416_p1(6 - 1 downto 0);
    logits_buf_3_ce1 <= logits_buf_3_ce1_local;

    logits_buf_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            logits_buf_3_ce1_local <= ap_const_logic_1;
        else 
            logits_buf_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    logits_buf_3_d1 <= line_reg_677(127 downto 96);
    logits_buf_3_we1 <= logits_buf_3_we1_local;

    logits_buf_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln204_reg_657_pp0_iter1_reg, icmp_ln230_reg_673_pp0_iter1_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln230_reg_673_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln204_reg_657_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            logits_buf_3_we1_local <= ap_const_logic_1;
        else 
            logits_buf_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    m01_fu_566_p3 <= 
        m0_fu_504_p3 when (icmp_ln146_fu_560_p2(0) = '1') else 
        m1_fu_520_p3;
    m0_fu_504_p3 <= 
        ap_phi_reg_pp0_iter3_x0_1_reg_229 when (trunc_ln141_fu_500_p1(0) = '1') else 
        ap_const_lv32_80000000;
    m1_fu_520_p3 <= 
        ap_phi_reg_pp0_iter3_x1_1_reg_249 when (tmp_fu_512_p3(0) = '1') else 
        ap_const_lv32_80000000;
    m23_fu_580_p3 <= 
        m2_fu_536_p3 when (icmp_ln147_fu_574_p2(0) = '1') else 
        m3_fu_552_p3;
    m2_fu_536_p3 <= 
        ap_phi_reg_pp0_iter3_x2_1_reg_269 when (tmp_72_fu_528_p3(0) = '1') else 
        ap_const_lv32_80000000;
    m3_fu_552_p3 <= 
        ap_phi_reg_pp0_iter3_x3_1_reg_289 when (tmp_73_fu_544_p3(0) = '1') else 
        ap_const_lv32_80000000;
    m_axi_gmem_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln204_reg_657, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln204_reg_657 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_0_WDATA <= ap_const_lv128_lc_1;
    m_axi_gmem_0_WID <= ap_const_lv1_0;
    m_axi_gmem_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_0_WSTRB <= ap_const_lv16_0;
    m_axi_gmem_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_0_WVALID <= ap_const_logic_0;
    max_x_2_fu_615_p3 <= 
        local_max_reg_710 when (or_ln237_fu_610_p2(0) = '1') else 
        max_x_fu_110;
    max_x_out <= max_x_fu_110;

    max_x_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln204_reg_657_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln204_reg_657_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            max_x_out_ap_vld <= ap_const_logic_1;
        else 
            max_x_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1_fu_369_p3 <= (trunc_ln206_fu_329_p1 & ap_const_lv2_2);
    or_ln237_fu_610_p2 <= (icmp_ln237_reg_705_pp0_iter3_reg or icmp_ln237_1_fu_605_p2);
    or_ln2_fu_387_p3 <= (trunc_ln206_fu_329_p1 & ap_const_lv2_3);
    or_ln_fu_351_p3 <= (trunc_ln206_fu_329_p1 & ap_const_lv2_1);
    shl_ln2_fu_333_p3 <= (trunc_ln206_fu_329_p1 & ap_const_lv2_0);
    tmp_72_fu_528_p3 <= ap_phi_mux_keep_3_phi_fu_283_p4(2 downto 2);
    tmp_73_fu_544_p3 <= ap_phi_mux_keep_3_phi_fu_283_p4(3 downto 3);
    tmp_fu_512_p3 <= ap_phi_mux_keep_3_phi_fu_283_p4(1 downto 1);
    trunc_ln141_fu_500_p1 <= ap_phi_mux_keep_3_phi_fu_283_p4(1 - 1 downto 0);
    trunc_ln206_fu_329_p1 <= ap_sig_allocacmp_blk_2(6 - 1 downto 0);
    x0_fu_423_p1 <= line_reg_677(32 - 1 downto 0);
    zext_ln204_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(blk_2_reg_651_pp0_iter1_reg),64));
    zext_ln207_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_333_p3),9));
    zext_ln210_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_keep_reg_216),2));
    zext_ln211_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_keep_1_phi_fu_243_p4),3));
    zext_ln212_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_keep_2_phi_fu_263_p4),4));
    zext_ln220_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_351_p3),9));
    zext_ln225_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln1_fu_369_p3),9));
    zext_ln230_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln2_fu_387_p3),9));
end behav;
