// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module softmax_accel_emit_exp_stream_Pipeline_exp_emit_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        exp_stream_din,
        exp_stream_full_n,
        exp_stream_write,
        exp_stream_num_data_valid,
        exp_stream_fifo_cap,
        trunc_ln,
        n,
        logits_buf_0_address0,
        logits_buf_0_ce0,
        logits_buf_0_q0,
        max_x,
        logits_buf_1_address0,
        logits_buf_1_ce0,
        logits_buf_1_q0,
        logits_buf_2_address0,
        logits_buf_2_ce0,
        logits_buf_2_q0,
        logits_buf_3_address0,
        logits_buf_3_ce0,
        logits_buf_3_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [131:0] exp_stream_din;
input   exp_stream_full_n;
output   exp_stream_write;
input  [31:0] exp_stream_num_data_valid;
input  [31:0] exp_stream_fifo_cap;
input  [6:0] trunc_ln;
input  [8:0] n;
output  [5:0] logits_buf_0_address0;
output   logits_buf_0_ce0;
input  [31:0] logits_buf_0_q0;
input  [31:0] max_x;
output  [5:0] logits_buf_1_address0;
output   logits_buf_1_ce0;
input  [31:0] logits_buf_1_q0;
output  [5:0] logits_buf_2_address0;
output   logits_buf_2_ce0;
input  [31:0] logits_buf_2_q0;
output  [5:0] logits_buf_3_address0;
output   logits_buf_3_ce0;
input  [31:0] logits_buf_3_q0;

reg ap_idle;
reg exp_stream_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln256_fu_347_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    exp_stream_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [31:0] max_x_read_reg_2454;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] pkt_keep_fu_383_p2;
reg   [0:0] pkt_keep_reg_2466;
reg   [0:0] pkt_keep_reg_2466_pp0_iter1_reg;
reg   [0:0] pkt_keep_reg_2466_pp0_iter2_reg;
reg   [0:0] pkt_keep_reg_2466_pp0_iter3_reg;
reg   [0:0] pkt_keep_reg_2466_pp0_iter4_reg;
reg   [0:0] pkt_keep_reg_2466_pp0_iter5_reg;
reg   [0:0] pkt_keep_reg_2466_pp0_iter6_reg;
wire   [0:0] icmp_ln270_fu_401_p2;
reg   [0:0] icmp_ln270_reg_2479;
reg   [0:0] icmp_ln270_reg_2479_pp0_iter1_reg;
reg   [0:0] icmp_ln270_reg_2479_pp0_iter2_reg;
reg   [0:0] icmp_ln270_reg_2479_pp0_iter3_reg;
reg   [0:0] icmp_ln270_reg_2479_pp0_iter4_reg;
reg   [0:0] icmp_ln270_reg_2479_pp0_iter5_reg;
reg   [0:0] icmp_ln270_reg_2479_pp0_iter6_reg;
wire   [0:0] icmp_ln274_fu_419_p2;
reg   [0:0] icmp_ln274_reg_2490;
reg   [0:0] icmp_ln274_reg_2490_pp0_iter1_reg;
reg   [0:0] icmp_ln274_reg_2490_pp0_iter2_reg;
reg   [0:0] icmp_ln274_reg_2490_pp0_iter3_reg;
reg   [0:0] icmp_ln274_reg_2490_pp0_iter4_reg;
reg   [0:0] icmp_ln274_reg_2490_pp0_iter5_reg;
reg   [0:0] icmp_ln274_reg_2490_pp0_iter6_reg;
wire   [0:0] icmp_ln278_fu_437_p2;
reg   [0:0] icmp_ln278_reg_2501;
reg   [0:0] icmp_ln278_reg_2501_pp0_iter1_reg;
reg   [0:0] icmp_ln278_reg_2501_pp0_iter2_reg;
reg   [0:0] icmp_ln278_reg_2501_pp0_iter3_reg;
reg   [0:0] icmp_ln278_reg_2501_pp0_iter4_reg;
reg   [0:0] icmp_ln278_reg_2501_pp0_iter5_reg;
reg   [0:0] icmp_ln278_reg_2501_pp0_iter6_reg;
wire   [31:0] x_q16_fu_448_p2;
reg   [31:0] x_q16_reg_2512;
wire   [31:0] x_q16_2_fu_453_p2;
reg   [31:0] x_q16_2_reg_2518;
wire   [31:0] x_q16_4_fu_458_p2;
reg   [31:0] x_q16_4_reg_2524;
wire   [31:0] x_q16_6_fu_463_p2;
reg   [31:0] x_q16_6_reg_2530;
wire   [31:0] x_q16_1_fu_473_p3;
reg   [31:0] x_q16_1_reg_2536;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [31:0] x_q16_1_reg_2536_pp0_iter3_reg;
wire   [49:0] sub_ln64_1_fu_522_p2;
reg   [49:0] sub_ln64_1_reg_2544;
wire   [31:0] x_q16_3_fu_533_p3;
reg   [31:0] x_q16_3_reg_2549;
reg   [31:0] x_q16_3_reg_2549_pp0_iter3_reg;
wire   [49:0] sub_ln64_3_fu_582_p2;
reg   [49:0] sub_ln64_3_reg_2557;
wire   [31:0] x_q16_5_fu_593_p3;
reg   [31:0] x_q16_5_reg_2562;
reg   [31:0] x_q16_5_reg_2562_pp0_iter3_reg;
wire   [49:0] sub_ln64_5_fu_642_p2;
reg   [49:0] sub_ln64_5_reg_2570;
wire   [31:0] x_q16_7_fu_653_p3;
reg   [31:0] x_q16_7_reg_2575;
reg   [31:0] x_q16_7_reg_2575_pp0_iter3_reg;
wire   [49:0] sub_ln64_7_fu_702_p2;
reg   [49:0] sub_ln64_7_reg_2583;
wire   [49:0] add_ln64_1_fu_735_p2;
reg   [49:0] add_ln64_1_reg_2588;
wire   [49:0] add_ln64_5_fu_768_p2;
reg   [49:0] add_ln64_5_reg_2593;
wire   [49:0] add_ln64_9_fu_801_p2;
reg   [49:0] add_ln64_9_reg_2598;
wire   [49:0] add_ln64_13_fu_834_p2;
reg   [49:0] add_ln64_13_reg_2603;
wire   [49:0] t64_fu_867_p2;
reg   [49:0] t64_reg_2608;
reg   [49:0] t64_reg_2608_pp0_iter5_reg;
reg   [11:0] rem_reg_2613;
reg   [15:0] k_reg_2618;
reg   [15:0] k_reg_2618_pp0_iter5_reg;
reg   [3:0] idx_reg_2623;
wire   [16:0] y0_fu_903_p35;
reg   [16:0] y0_reg_2628;
reg   [16:0] y0_reg_2628_pp0_iter5_reg;
reg   [0:0] tmp_80_reg_2634;
reg   [0:0] tmp_80_reg_2634_pp0_iter5_reg;
wire   [0:0] icmp_ln83_fu_993_p2;
reg   [0:0] icmp_ln83_reg_2640;
reg   [0:0] icmp_ln83_reg_2640_pp0_iter5_reg;
wire   [49:0] t64_1_fu_1026_p2;
reg   [49:0] t64_1_reg_2645;
reg   [49:0] t64_1_reg_2645_pp0_iter5_reg;
reg   [11:0] rem_1_reg_2650;
reg   [15:0] k_1_reg_2655;
reg   [15:0] k_1_reg_2655_pp0_iter5_reg;
reg   [3:0] idx_1_reg_2660;
wire   [16:0] y0_1_fu_1062_p35;
reg   [16:0] y0_1_reg_2665;
reg   [16:0] y0_1_reg_2665_pp0_iter5_reg;
reg   [0:0] tmp_90_reg_2671;
reg   [0:0] tmp_90_reg_2671_pp0_iter5_reg;
wire   [0:0] icmp_ln83_1_fu_1152_p2;
reg   [0:0] icmp_ln83_1_reg_2677;
reg   [0:0] icmp_ln83_1_reg_2677_pp0_iter5_reg;
wire   [49:0] t64_2_fu_1185_p2;
reg   [49:0] t64_2_reg_2682;
reg   [49:0] t64_2_reg_2682_pp0_iter5_reg;
reg   [11:0] rem_2_reg_2687;
reg   [15:0] k_2_reg_2692;
reg   [15:0] k_2_reg_2692_pp0_iter5_reg;
reg   [3:0] idx_2_reg_2697;
wire   [16:0] y0_2_fu_1221_p35;
reg   [16:0] y0_2_reg_2702;
reg   [16:0] y0_2_reg_2702_pp0_iter5_reg;
reg   [0:0] tmp_100_reg_2708;
reg   [0:0] tmp_100_reg_2708_pp0_iter5_reg;
wire   [0:0] icmp_ln83_2_fu_1311_p2;
reg   [0:0] icmp_ln83_2_reg_2714;
reg   [0:0] icmp_ln83_2_reg_2714_pp0_iter5_reg;
wire   [49:0] t64_3_fu_1344_p2;
reg   [49:0] t64_3_reg_2719;
reg   [49:0] t64_3_reg_2719_pp0_iter5_reg;
reg   [11:0] rem_3_reg_2724;
reg   [15:0] k_3_reg_2729;
reg   [15:0] k_3_reg_2729_pp0_iter5_reg;
reg   [3:0] idx_3_reg_2734;
wire   [16:0] y0_3_fu_1380_p35;
reg   [16:0] y0_3_reg_2739;
reg   [16:0] y0_3_reg_2739_pp0_iter5_reg;
reg   [0:0] tmp_110_reg_2745;
reg   [0:0] tmp_110_reg_2745_pp0_iter5_reg;
wire   [0:0] icmp_ln83_3_fu_1470_p2;
reg   [0:0] icmp_ln83_3_reg_2751;
reg   [0:0] icmp_ln83_3_reg_2751_pp0_iter5_reg;
reg   [17:0] trunc_ln1_reg_2756;
reg   [17:0] trunc_ln78_1_reg_2761;
reg   [17:0] trunc_ln78_2_reg_2766;
reg   [17:0] trunc_ln78_3_reg_2771;
wire   [31:0] y_15_fu_1993_p9;
reg   [31:0] y_15_reg_2776;
wire   [31:0] pkt_v1_2_fu_2128_p3;
reg   [31:0] pkt_v1_2_reg_2781;
wire   [31:0] pkt_v2_2_fu_2250_p3;
reg   [31:0] pkt_v2_2_reg_2786;
wire   [31:0] pkt_v3_2_fu_2372_p3;
reg   [31:0] pkt_v3_2_reg_2791;
wire   [63:0] zext_ln256_fu_359_p1;
wire    ap_block_pp0_stage0;
reg   [6:0] blk_fu_258;
wire   [6:0] add_ln256_fu_353_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_blk_4;
reg    ap_block_pp0_stage0_01001_grp1;
reg    logits_buf_0_ce0_local;
reg    logits_buf_1_ce0_local;
reg    logits_buf_2_ce0_local;
reg    logits_buf_3_ce0_local;
wire   [5:0] trunc_ln258_fu_367_p1;
wire   [7:0] shl_ln_fu_371_p3;
wire   [8:0] zext_ln266_fu_379_p1;
wire   [7:0] or_ln_fu_389_p3;
wire   [8:0] zext_ln270_fu_397_p1;
wire   [7:0] or_ln5_fu_407_p3;
wire   [8:0] zext_ln274_fu_415_p1;
wire   [7:0] or_ln6_fu_425_p3;
wire   [8:0] zext_ln278_fu_433_p1;
wire   [0:0] icmp_ln62_fu_468_p2;
wire   [48:0] tmp_fu_480_p3;
wire   [46:0] tmp_74_fu_492_p3;
wire  signed [49:0] sext_ln64_fu_488_p1;
wire  signed [49:0] sext_ln64_1_fu_500_p1;
wire   [43:0] tmp_75_fu_510_p3;
wire   [49:0] sub_ln64_fu_504_p2;
wire  signed [49:0] sext_ln64_2_fu_518_p1;
wire   [0:0] icmp_ln62_1_fu_528_p2;
wire   [48:0] tmp_83_fu_540_p3;
wire   [46:0] tmp_84_fu_552_p3;
wire  signed [49:0] sext_ln64_7_fu_548_p1;
wire  signed [49:0] sext_ln64_8_fu_560_p1;
wire   [43:0] tmp_85_fu_570_p3;
wire   [49:0] sub_ln64_2_fu_564_p2;
wire  signed [49:0] sext_ln64_9_fu_578_p1;
wire   [0:0] icmp_ln62_2_fu_588_p2;
wire   [48:0] tmp_93_fu_600_p3;
wire   [46:0] tmp_94_fu_612_p3;
wire  signed [49:0] sext_ln64_14_fu_608_p1;
wire  signed [49:0] sext_ln64_15_fu_620_p1;
wire   [43:0] tmp_95_fu_630_p3;
wire   [49:0] sub_ln64_4_fu_624_p2;
wire  signed [49:0] sext_ln64_16_fu_638_p1;
wire   [0:0] icmp_ln62_3_fu_648_p2;
wire   [48:0] tmp_103_fu_660_p3;
wire   [46:0] tmp_104_fu_672_p3;
wire  signed [49:0] sext_ln64_21_fu_668_p1;
wire  signed [49:0] sext_ln64_22_fu_680_p1;
wire   [43:0] tmp_105_fu_690_p3;
wire   [49:0] sub_ln64_6_fu_684_p2;
wire  signed [49:0] sext_ln64_23_fu_698_p1;
wire   [39:0] tmp_76_fu_708_p3;
wire  signed [49:0] sext_ln64_3_fu_715_p1;
wire   [37:0] tmp_77_fu_724_p3;
wire   [49:0] add_ln64_fu_719_p2;
wire  signed [49:0] sext_ln64_4_fu_731_p1;
wire   [39:0] tmp_86_fu_741_p3;
wire  signed [49:0] sext_ln64_10_fu_748_p1;
wire   [37:0] tmp_87_fu_757_p3;
wire   [49:0] add_ln64_4_fu_752_p2;
wire  signed [49:0] sext_ln64_11_fu_764_p1;
wire   [39:0] tmp_96_fu_774_p3;
wire  signed [49:0] sext_ln64_17_fu_781_p1;
wire   [37:0] tmp_97_fu_790_p3;
wire   [49:0] add_ln64_8_fu_785_p2;
wire  signed [49:0] sext_ln64_18_fu_797_p1;
wire   [39:0] tmp_106_fu_807_p3;
wire  signed [49:0] sext_ln64_24_fu_814_p1;
wire   [37:0] tmp_107_fu_823_p3;
wire   [49:0] add_ln64_12_fu_818_p2;
wire  signed [49:0] sext_ln64_25_fu_830_p1;
wire   [35:0] tmp_78_fu_840_p3;
wire  signed [49:0] sext_ln64_5_fu_847_p1;
wire   [33:0] tmp_79_fu_856_p3;
wire   [49:0] add_ln64_2_fu_851_p2;
wire  signed [49:0] sext_ln64_6_fu_863_p1;
wire   [16:0] y0_fu_903_p33;
wire   [3:0] y0_fu_903_p34;
wire   [11:0] tmp_81_fu_983_p4;
wire   [35:0] tmp_88_fu_999_p3;
wire  signed [49:0] sext_ln64_12_fu_1006_p1;
wire   [33:0] tmp_89_fu_1015_p3;
wire   [49:0] add_ln64_6_fu_1010_p2;
wire  signed [49:0] sext_ln64_13_fu_1022_p1;
wire   [16:0] y0_1_fu_1062_p33;
wire   [3:0] y0_1_fu_1062_p34;
wire   [11:0] tmp_91_fu_1142_p4;
wire   [35:0] tmp_98_fu_1158_p3;
wire  signed [49:0] sext_ln64_19_fu_1165_p1;
wire   [33:0] tmp_99_fu_1174_p3;
wire   [49:0] add_ln64_10_fu_1169_p2;
wire  signed [49:0] sext_ln64_20_fu_1181_p1;
wire   [16:0] y0_2_fu_1221_p33;
wire   [3:0] y0_2_fu_1221_p34;
wire   [11:0] tmp_101_fu_1301_p4;
wire   [35:0] tmp_108_fu_1317_p3;
wire  signed [49:0] sext_ln64_26_fu_1324_p1;
wire   [33:0] tmp_109_fu_1333_p3;
wire   [49:0] add_ln64_14_fu_1328_p2;
wire  signed [49:0] sext_ln64_27_fu_1340_p1;
wire   [16:0] y0_3_fu_1380_p33;
wire   [3:0] y0_3_fu_1380_p34;
wire   [11:0] tmp_111_fu_1460_p4;
wire   [17:0] y1_fu_1476_p33;
wire   [17:0] y1_fu_1476_p35;
wire   [17:0] zext_ln75_fu_1547_p1;
wire  signed [17:0] dy_fu_1550_p2;
wire   [11:0] interp_fu_1563_p0;
wire   [29:0] interp_fu_1563_p2;
wire   [17:0] y1_1_fu_1579_p33;
wire   [17:0] y1_1_fu_1579_p35;
wire   [17:0] zext_ln75_1_fu_1650_p1;
wire  signed [17:0] dy_1_fu_1653_p2;
wire   [11:0] interp_1_fu_1666_p0;
wire   [29:0] interp_1_fu_1666_p2;
wire   [17:0] y1_2_fu_1682_p33;
wire   [17:0] y1_2_fu_1682_p35;
wire   [17:0] zext_ln75_2_fu_1753_p1;
wire  signed [17:0] dy_2_fu_1756_p2;
wire   [11:0] interp_2_fu_1769_p0;
wire   [29:0] interp_2_fu_1769_p2;
wire   [17:0] y1_3_fu_1785_p33;
wire   [17:0] y1_3_fu_1785_p35;
wire   [17:0] zext_ln75_3_fu_1856_p1;
wire  signed [17:0] dy_3_fu_1859_p2;
wire   [11:0] interp_3_fu_1872_p0;
wire   [29:0] interp_3_fu_1872_p2;
wire  signed [18:0] sext_ln78_fu_1891_p1;
wire   [18:0] zext_ln73_fu_1888_p1;
wire   [18:0] y_frac_fu_1894_p2;
wire   [3:0] trunc_ln2_fu_1909_p4;
wire   [3:0] sh_1_fu_1918_p3;
wire  signed [31:0] sext_ln78_1_fu_1900_p1;
wire   [31:0] zext_ln82_fu_1925_p1;
wire  signed [16:0] sext_ln86_fu_1935_p1;
wire   [16:0] sh_2_fu_1938_p2;
wire   [31:0] zext_ln86_fu_1944_p1;
wire   [0:0] xor_ln81_fu_1904_p2;
wire   [11:0] tmp_82_fu_1959_p4;
wire   [0:0] icmp_ln87_fu_1969_p2;
wire   [0:0] and_ln87_fu_1975_p2;
wire   [0:0] and_ln81_fu_1954_p2;
wire   [0:0] and_ln87_1_fu_1980_p2;
wire   [31:0] y_15_fu_1993_p2;
wire   [31:0] y_15_fu_1993_p4;
wire   [31:0] y_15_fu_1993_p7;
wire   [1:0] y_15_fu_1993_p8;
wire  signed [18:0] sext_ln78_2_fu_2016_p1;
wire   [18:0] zext_ln73_1_fu_2013_p1;
wire   [18:0] y_frac_1_fu_2019_p2;
wire   [3:0] trunc_ln82_1_fu_2034_p4;
wire   [3:0] sh_4_fu_2043_p3;
wire  signed [31:0] sext_ln78_3_fu_2025_p1;
wire   [31:0] zext_ln82_1_fu_2050_p1;
wire  signed [16:0] sext_ln86_1_fu_2060_p1;
wire   [16:0] sh_5_fu_2063_p2;
wire   [11:0] tmp_92_fu_2073_p4;
wire   [31:0] zext_ln86_1_fu_2069_p1;
wire   [0:0] icmp_ln87_1_fu_2083_p2;
wire   [0:0] xor_ln81_1_fu_2029_p2;
wire   [0:0] and_ln87_2_fu_2095_p2;
wire   [31:0] y_16_fu_2108_p2;
wire   [31:0] y_16_fu_2108_p6;
wire   [31:0] y_16_fu_2108_p7;
wire   [1:0] y_16_fu_2108_p8;
wire   [31:0] y_16_fu_2108_p9;
wire  signed [18:0] sext_ln78_4_fu_2138_p1;
wire   [18:0] zext_ln73_2_fu_2135_p1;
wire   [18:0] y_frac_2_fu_2141_p2;
wire   [3:0] trunc_ln82_2_fu_2156_p4;
wire   [3:0] sh_7_fu_2165_p3;
wire  signed [31:0] sext_ln78_5_fu_2147_p1;
wire   [31:0] zext_ln82_2_fu_2172_p1;
wire  signed [16:0] sext_ln86_2_fu_2182_p1;
wire   [16:0] sh_8_fu_2185_p2;
wire   [11:0] tmp_102_fu_2195_p4;
wire   [31:0] zext_ln86_2_fu_2191_p1;
wire   [0:0] icmp_ln87_2_fu_2205_p2;
wire   [0:0] xor_ln81_2_fu_2151_p2;
wire   [0:0] and_ln87_3_fu_2217_p2;
wire   [31:0] y_fu_2230_p2;
wire   [31:0] y_fu_2230_p6;
wire   [31:0] y_fu_2230_p7;
wire   [1:0] y_fu_2230_p8;
wire   [31:0] y_fu_2230_p9;
wire  signed [18:0] sext_ln78_6_fu_2260_p1;
wire   [18:0] zext_ln73_3_fu_2257_p1;
wire   [18:0] y_frac_3_fu_2263_p2;
wire   [3:0] trunc_ln82_3_fu_2278_p4;
wire   [3:0] sh_10_fu_2287_p3;
wire  signed [31:0] sext_ln78_7_fu_2269_p1;
wire   [31:0] zext_ln82_3_fu_2294_p1;
wire  signed [16:0] sext_ln86_3_fu_2304_p1;
wire   [16:0] sh_11_fu_2307_p2;
wire   [11:0] tmp_112_fu_2317_p4;
wire   [31:0] zext_ln86_3_fu_2313_p1;
wire   [0:0] icmp_ln87_3_fu_2327_p2;
wire   [0:0] xor_ln81_3_fu_2273_p2;
wire   [0:0] and_ln87_4_fu_2339_p2;
wire   [31:0] y_17_fu_2352_p2;
wire   [31:0] y_17_fu_2352_p6;
wire   [31:0] y_17_fu_2352_p7;
wire   [1:0] y_17_fu_2352_p8;
wire   [31:0] y_17_fu_2352_p9;
wire   [1:0] pkt_keep_7_fu_2382_p3;
wire   [1:0] zext_ln259_fu_2379_p1;
wire   [1:0] pkt_keep_8_fu_2389_p3;
wire   [2:0] pkt_keep_9_fu_2400_p3;
wire   [2:0] zext_ln259_1_fu_2396_p1;
wire   [2:0] pkt_keep_2_fu_2408_p3;
wire   [3:0] zext_ln259_2_fu_2415_p1;
wire   [3:0] pkt_keep_10_fu_2419_p4;
wire   [3:0] pkt_keep_3_fu_2429_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [29:0] interp_1_fu_1666_p00;
wire   [29:0] interp_2_fu_1769_p00;
wire   [29:0] interp_3_fu_1872_p00;
wire   [29:0] interp_fu_1563_p00;
wire   [3:0] y0_fu_903_p1;
wire   [3:0] y0_fu_903_p3;
wire   [3:0] y0_fu_903_p5;
wire   [3:0] y0_fu_903_p7;
wire   [3:0] y0_fu_903_p9;
wire   [3:0] y0_fu_903_p11;
wire   [3:0] y0_fu_903_p13;
wire   [3:0] y0_fu_903_p15;
wire  signed [3:0] y0_fu_903_p17;
wire  signed [3:0] y0_fu_903_p19;
wire  signed [3:0] y0_fu_903_p21;
wire  signed [3:0] y0_fu_903_p23;
wire  signed [3:0] y0_fu_903_p25;
wire  signed [3:0] y0_fu_903_p27;
wire  signed [3:0] y0_fu_903_p29;
wire  signed [3:0] y0_fu_903_p31;
wire   [3:0] y0_1_fu_1062_p1;
wire   [3:0] y0_1_fu_1062_p3;
wire   [3:0] y0_1_fu_1062_p5;
wire   [3:0] y0_1_fu_1062_p7;
wire   [3:0] y0_1_fu_1062_p9;
wire   [3:0] y0_1_fu_1062_p11;
wire   [3:0] y0_1_fu_1062_p13;
wire   [3:0] y0_1_fu_1062_p15;
wire  signed [3:0] y0_1_fu_1062_p17;
wire  signed [3:0] y0_1_fu_1062_p19;
wire  signed [3:0] y0_1_fu_1062_p21;
wire  signed [3:0] y0_1_fu_1062_p23;
wire  signed [3:0] y0_1_fu_1062_p25;
wire  signed [3:0] y0_1_fu_1062_p27;
wire  signed [3:0] y0_1_fu_1062_p29;
wire  signed [3:0] y0_1_fu_1062_p31;
wire   [3:0] y0_2_fu_1221_p1;
wire   [3:0] y0_2_fu_1221_p3;
wire   [3:0] y0_2_fu_1221_p5;
wire   [3:0] y0_2_fu_1221_p7;
wire   [3:0] y0_2_fu_1221_p9;
wire   [3:0] y0_2_fu_1221_p11;
wire   [3:0] y0_2_fu_1221_p13;
wire   [3:0] y0_2_fu_1221_p15;
wire  signed [3:0] y0_2_fu_1221_p17;
wire  signed [3:0] y0_2_fu_1221_p19;
wire  signed [3:0] y0_2_fu_1221_p21;
wire  signed [3:0] y0_2_fu_1221_p23;
wire  signed [3:0] y0_2_fu_1221_p25;
wire  signed [3:0] y0_2_fu_1221_p27;
wire  signed [3:0] y0_2_fu_1221_p29;
wire  signed [3:0] y0_2_fu_1221_p31;
wire   [3:0] y0_3_fu_1380_p1;
wire   [3:0] y0_3_fu_1380_p3;
wire   [3:0] y0_3_fu_1380_p5;
wire   [3:0] y0_3_fu_1380_p7;
wire   [3:0] y0_3_fu_1380_p9;
wire   [3:0] y0_3_fu_1380_p11;
wire   [3:0] y0_3_fu_1380_p13;
wire   [3:0] y0_3_fu_1380_p15;
wire  signed [3:0] y0_3_fu_1380_p17;
wire  signed [3:0] y0_3_fu_1380_p19;
wire  signed [3:0] y0_3_fu_1380_p21;
wire  signed [3:0] y0_3_fu_1380_p23;
wire  signed [3:0] y0_3_fu_1380_p25;
wire  signed [3:0] y0_3_fu_1380_p27;
wire  signed [3:0] y0_3_fu_1380_p29;
wire  signed [3:0] y0_3_fu_1380_p31;
wire   [3:0] y1_fu_1476_p1;
wire   [3:0] y1_fu_1476_p3;
wire   [3:0] y1_fu_1476_p5;
wire   [3:0] y1_fu_1476_p7;
wire   [3:0] y1_fu_1476_p9;
wire   [3:0] y1_fu_1476_p11;
wire   [3:0] y1_fu_1476_p13;
wire   [3:0] y1_fu_1476_p15;
wire  signed [3:0] y1_fu_1476_p17;
wire  signed [3:0] y1_fu_1476_p19;
wire  signed [3:0] y1_fu_1476_p21;
wire  signed [3:0] y1_fu_1476_p23;
wire  signed [3:0] y1_fu_1476_p25;
wire  signed [3:0] y1_fu_1476_p27;
wire  signed [3:0] y1_fu_1476_p29;
wire  signed [3:0] y1_fu_1476_p31;
wire   [3:0] y1_1_fu_1579_p1;
wire   [3:0] y1_1_fu_1579_p3;
wire   [3:0] y1_1_fu_1579_p5;
wire   [3:0] y1_1_fu_1579_p7;
wire   [3:0] y1_1_fu_1579_p9;
wire   [3:0] y1_1_fu_1579_p11;
wire   [3:0] y1_1_fu_1579_p13;
wire   [3:0] y1_1_fu_1579_p15;
wire  signed [3:0] y1_1_fu_1579_p17;
wire  signed [3:0] y1_1_fu_1579_p19;
wire  signed [3:0] y1_1_fu_1579_p21;
wire  signed [3:0] y1_1_fu_1579_p23;
wire  signed [3:0] y1_1_fu_1579_p25;
wire  signed [3:0] y1_1_fu_1579_p27;
wire  signed [3:0] y1_1_fu_1579_p29;
wire  signed [3:0] y1_1_fu_1579_p31;
wire   [3:0] y1_2_fu_1682_p1;
wire   [3:0] y1_2_fu_1682_p3;
wire   [3:0] y1_2_fu_1682_p5;
wire   [3:0] y1_2_fu_1682_p7;
wire   [3:0] y1_2_fu_1682_p9;
wire   [3:0] y1_2_fu_1682_p11;
wire   [3:0] y1_2_fu_1682_p13;
wire   [3:0] y1_2_fu_1682_p15;
wire  signed [3:0] y1_2_fu_1682_p17;
wire  signed [3:0] y1_2_fu_1682_p19;
wire  signed [3:0] y1_2_fu_1682_p21;
wire  signed [3:0] y1_2_fu_1682_p23;
wire  signed [3:0] y1_2_fu_1682_p25;
wire  signed [3:0] y1_2_fu_1682_p27;
wire  signed [3:0] y1_2_fu_1682_p29;
wire  signed [3:0] y1_2_fu_1682_p31;
wire   [3:0] y1_3_fu_1785_p1;
wire   [3:0] y1_3_fu_1785_p3;
wire   [3:0] y1_3_fu_1785_p5;
wire   [3:0] y1_3_fu_1785_p7;
wire   [3:0] y1_3_fu_1785_p9;
wire   [3:0] y1_3_fu_1785_p11;
wire   [3:0] y1_3_fu_1785_p13;
wire   [3:0] y1_3_fu_1785_p15;
wire  signed [3:0] y1_3_fu_1785_p17;
wire  signed [3:0] y1_3_fu_1785_p19;
wire  signed [3:0] y1_3_fu_1785_p21;
wire  signed [3:0] y1_3_fu_1785_p23;
wire  signed [3:0] y1_3_fu_1785_p25;
wire  signed [3:0] y1_3_fu_1785_p27;
wire  signed [3:0] y1_3_fu_1785_p29;
wire  signed [3:0] y1_3_fu_1785_p31;
wire  signed [1:0] y_15_fu_1993_p1;
wire   [1:0] y_15_fu_1993_p3;
wire   [1:0] y_15_fu_1993_p5;
wire  signed [1:0] y_16_fu_2108_p1;
wire   [1:0] y_16_fu_2108_p3;
wire   [1:0] y_16_fu_2108_p5;
wire  signed [1:0] y_fu_2230_p1;
wire   [1:0] y_fu_2230_p3;
wire   [1:0] y_fu_2230_p5;
wire  signed [1:0] y_17_fu_2352_p1;
wire   [1:0] y_17_fu_2352_p3;
wire   [1:0] y_17_fu_2352_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 blk_fu_258 = 7'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_33_4_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 17 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 17 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 17 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 17 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 17 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 17 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 17 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 17 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 17 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 17 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 17 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 17 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 17 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 17 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 17 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 17 ),
    .def_WIDTH( 17 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 17 ))
sparsemux_33_4_17_1_1_U18(
    .din0(17'd65536),
    .din1(17'd68450),
    .din2(17'd71495),
    .din3(17'd74716),
    .din4(17'd78085),
    .din5(17'd81633),
    .din6(17'd85355),
    .din7(17'd89284),
    .din8(17'd93423),
    .din9(17'd97786),
    .din10(17'd102391),
    .din11(17'd107255),
    .din12(17'd112401),
    .din13(17'd117854),
    .din14(17'd123642),
    .din15(17'd129794),
    .def(y0_fu_903_p33),
    .sel(y0_fu_903_p34),
    .dout(y0_fu_903_p35)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_33_4_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 17 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 17 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 17 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 17 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 17 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 17 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 17 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 17 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 17 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 17 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 17 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 17 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 17 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 17 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 17 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 17 ),
    .def_WIDTH( 17 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 17 ))
sparsemux_33_4_17_1_1_U19(
    .din0(17'd65536),
    .din1(17'd68450),
    .din2(17'd71495),
    .din3(17'd74716),
    .din4(17'd78085),
    .din5(17'd81633),
    .din6(17'd85355),
    .din7(17'd89284),
    .din8(17'd93423),
    .din9(17'd97786),
    .din10(17'd102391),
    .din11(17'd107255),
    .din12(17'd112401),
    .din13(17'd117854),
    .din14(17'd123642),
    .din15(17'd129794),
    .def(y0_1_fu_1062_p33),
    .sel(y0_1_fu_1062_p34),
    .dout(y0_1_fu_1062_p35)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_33_4_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 17 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 17 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 17 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 17 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 17 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 17 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 17 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 17 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 17 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 17 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 17 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 17 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 17 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 17 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 17 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 17 ),
    .def_WIDTH( 17 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 17 ))
sparsemux_33_4_17_1_1_U20(
    .din0(17'd65536),
    .din1(17'd68450),
    .din2(17'd71495),
    .din3(17'd74716),
    .din4(17'd78085),
    .din5(17'd81633),
    .din6(17'd85355),
    .din7(17'd89284),
    .din8(17'd93423),
    .din9(17'd97786),
    .din10(17'd102391),
    .din11(17'd107255),
    .din12(17'd112401),
    .din13(17'd117854),
    .din14(17'd123642),
    .din15(17'd129794),
    .def(y0_2_fu_1221_p33),
    .sel(y0_2_fu_1221_p34),
    .dout(y0_2_fu_1221_p35)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_33_4_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 17 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 17 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 17 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 17 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 17 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 17 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 17 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 17 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 17 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 17 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 17 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 17 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 17 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 17 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 17 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 17 ),
    .def_WIDTH( 17 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 17 ))
sparsemux_33_4_17_1_1_U21(
    .din0(17'd65536),
    .din1(17'd68450),
    .din2(17'd71495),
    .din3(17'd74716),
    .din4(17'd78085),
    .din5(17'd81633),
    .din6(17'd85355),
    .din7(17'd89284),
    .din8(17'd93423),
    .din9(17'd97786),
    .din10(17'd102391),
    .din11(17'd107255),
    .din12(17'd112401),
    .din13(17'd117854),
    .din14(17'd123642),
    .din15(17'd129794),
    .def(y0_3_fu_1380_p33),
    .sel(y0_3_fu_1380_p34),
    .dout(y0_3_fu_1380_p35)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_33_4_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 18 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 18 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 18 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 18 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 18 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 18 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 18 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 18 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 18 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 18 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 18 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 18 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 18 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 18 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
sparsemux_33_4_18_1_1_U22(
    .din0(18'd68450),
    .din1(18'd71495),
    .din2(18'd74716),
    .din3(18'd78085),
    .din4(18'd81633),
    .din5(18'd85355),
    .din6(18'd89284),
    .din7(18'd93423),
    .din8(18'd97786),
    .din9(18'd102391),
    .din10(18'd107255),
    .din11(18'd112401),
    .din12(18'd117854),
    .din13(18'd123642),
    .din14(18'd129794),
    .din15(18'd136350),
    .def(y1_fu_1476_p33),
    .sel(idx_reg_2623),
    .dout(y1_fu_1476_p35)
);

softmax_accel_mul_12ns_18s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
mul_12ns_18s_30_1_1_U23(
    .din0(interp_fu_1563_p0),
    .din1(dy_fu_1550_p2),
    .dout(interp_fu_1563_p2)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_33_4_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 18 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 18 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 18 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 18 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 18 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 18 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 18 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 18 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 18 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 18 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 18 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 18 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 18 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 18 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
sparsemux_33_4_18_1_1_U24(
    .din0(18'd68450),
    .din1(18'd71495),
    .din2(18'd74716),
    .din3(18'd78085),
    .din4(18'd81633),
    .din5(18'd85355),
    .din6(18'd89284),
    .din7(18'd93423),
    .din8(18'd97786),
    .din9(18'd102391),
    .din10(18'd107255),
    .din11(18'd112401),
    .din12(18'd117854),
    .din13(18'd123642),
    .din14(18'd129794),
    .din15(18'd136350),
    .def(y1_1_fu_1579_p33),
    .sel(idx_1_reg_2660),
    .dout(y1_1_fu_1579_p35)
);

softmax_accel_mul_12ns_18s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
mul_12ns_18s_30_1_1_U25(
    .din0(interp_1_fu_1666_p0),
    .din1(dy_1_fu_1653_p2),
    .dout(interp_1_fu_1666_p2)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_33_4_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 18 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 18 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 18 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 18 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 18 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 18 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 18 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 18 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 18 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 18 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 18 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 18 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 18 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 18 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
sparsemux_33_4_18_1_1_U26(
    .din0(18'd68450),
    .din1(18'd71495),
    .din2(18'd74716),
    .din3(18'd78085),
    .din4(18'd81633),
    .din5(18'd85355),
    .din6(18'd89284),
    .din7(18'd93423),
    .din8(18'd97786),
    .din9(18'd102391),
    .din10(18'd107255),
    .din11(18'd112401),
    .din12(18'd117854),
    .din13(18'd123642),
    .din14(18'd129794),
    .din15(18'd136350),
    .def(y1_2_fu_1682_p33),
    .sel(idx_2_reg_2697),
    .dout(y1_2_fu_1682_p35)
);

softmax_accel_mul_12ns_18s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
mul_12ns_18s_30_1_1_U27(
    .din0(interp_2_fu_1769_p0),
    .din1(dy_2_fu_1756_p2),
    .dout(interp_2_fu_1769_p2)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_33_4_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 18 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 18 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 18 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 18 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 18 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 18 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 18 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 18 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 18 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 18 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 18 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 18 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 18 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 18 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
sparsemux_33_4_18_1_1_U28(
    .din0(18'd68450),
    .din1(18'd71495),
    .din2(18'd74716),
    .din3(18'd78085),
    .din4(18'd81633),
    .din5(18'd85355),
    .din6(18'd89284),
    .din7(18'd93423),
    .din8(18'd97786),
    .din9(18'd102391),
    .din10(18'd107255),
    .din11(18'd112401),
    .din12(18'd117854),
    .din13(18'd123642),
    .din14(18'd129794),
    .din15(18'd136350),
    .def(y1_3_fu_1785_p33),
    .sel(idx_3_reg_2734),
    .dout(y1_3_fu_1785_p35)
);

softmax_accel_mul_12ns_18s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
mul_12ns_18s_30_1_1_U29(
    .din0(interp_3_fu_1872_p0),
    .din1(dy_3_fu_1859_p2),
    .dout(interp_3_fu_1872_p2)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U30(
    .din0(y_15_fu_1993_p2),
    .din1(y_15_fu_1993_p4),
    .din2(32'd0),
    .def(y_15_fu_1993_p7),
    .sel(y_15_fu_1993_p8),
    .dout(y_15_fu_1993_p9)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U31(
    .din0(y_16_fu_2108_p2),
    .din1(32'd0),
    .din2(y_16_fu_2108_p6),
    .def(y_16_fu_2108_p7),
    .sel(y_16_fu_2108_p8),
    .dout(y_16_fu_2108_p9)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U32(
    .din0(y_fu_2230_p2),
    .din1(32'd0),
    .din2(y_fu_2230_p6),
    .def(y_fu_2230_p7),
    .sel(y_fu_2230_p8),
    .dout(y_fu_2230_p9)
);

(* dissolve_hierarchy = "yes" *) softmax_accel_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U33(
    .din0(y_17_fu_2352_p2),
    .din1(32'd0),
    .din2(y_17_fu_2352_p6),
    .def(y_17_fu_2352_p7),
    .sel(y_17_fu_2352_p8),
    .dout(y_17_fu_2352_p9)
);

softmax_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln256_fu_347_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            blk_fu_258 <= add_ln256_fu_353_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            blk_fu_258 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln64_13_reg_2603[49 : 6] <= add_ln64_13_fu_834_p2[49 : 6];
        add_ln64_1_reg_2588[49 : 6] <= add_ln64_1_fu_735_p2[49 : 6];
        add_ln64_5_reg_2593[49 : 6] <= add_ln64_5_fu_768_p2[49 : 6];
        add_ln64_9_reg_2598[49 : 6] <= add_ln64_9_fu_801_p2[49 : 6];
        icmp_ln83_1_reg_2677 <= icmp_ln83_1_fu_1152_p2;
        icmp_ln83_1_reg_2677_pp0_iter5_reg <= icmp_ln83_1_reg_2677;
        icmp_ln83_2_reg_2714 <= icmp_ln83_2_fu_1311_p2;
        icmp_ln83_2_reg_2714_pp0_iter5_reg <= icmp_ln83_2_reg_2714;
        icmp_ln83_3_reg_2751 <= icmp_ln83_3_fu_1470_p2;
        icmp_ln83_3_reg_2751_pp0_iter5_reg <= icmp_ln83_3_reg_2751;
        icmp_ln83_reg_2640 <= icmp_ln83_fu_993_p2;
        icmp_ln83_reg_2640_pp0_iter5_reg <= icmp_ln83_reg_2640;
        idx_1_reg_2660 <= {{t64_1_fu_1026_p2[31:28]}};
        idx_2_reg_2697 <= {{t64_2_fu_1185_p2[31:28]}};
        idx_3_reg_2734 <= {{t64_3_fu_1344_p2[31:28]}};
        idx_reg_2623 <= {{t64_fu_867_p2[31:28]}};
        k_1_reg_2655 <= {{t64_1_fu_1026_p2[47:32]}};
        k_1_reg_2655_pp0_iter5_reg <= k_1_reg_2655;
        k_2_reg_2692 <= {{t64_2_fu_1185_p2[47:32]}};
        k_2_reg_2692_pp0_iter5_reg <= k_2_reg_2692;
        k_3_reg_2729 <= {{t64_3_fu_1344_p2[47:32]}};
        k_3_reg_2729_pp0_iter5_reg <= k_3_reg_2729;
        k_reg_2618 <= {{t64_fu_867_p2[47:32]}};
        k_reg_2618_pp0_iter5_reg <= k_reg_2618;
        pkt_v1_2_reg_2781 <= pkt_v1_2_fu_2128_p3;
        pkt_v2_2_reg_2786 <= pkt_v2_2_fu_2250_p3;
        pkt_v3_2_reg_2791 <= pkt_v3_2_fu_2372_p3;
        rem_1_reg_2650 <= {{t64_1_fu_1026_p2[27:16]}};
        rem_2_reg_2687 <= {{t64_2_fu_1185_p2[27:16]}};
        rem_3_reg_2724 <= {{t64_3_fu_1344_p2[27:16]}};
        rem_reg_2613 <= {{t64_fu_867_p2[27:16]}};
        sub_ln64_1_reg_2544[49 : 12] <= sub_ln64_1_fu_522_p2[49 : 12];
        sub_ln64_3_reg_2557[49 : 12] <= sub_ln64_3_fu_582_p2[49 : 12];
        sub_ln64_5_reg_2570[49 : 12] <= sub_ln64_5_fu_642_p2[49 : 12];
        sub_ln64_7_reg_2583[49 : 12] <= sub_ln64_7_fu_702_p2[49 : 12];
        t64_1_reg_2645[49 : 2] <= t64_1_fu_1026_p2[49 : 2];
        t64_1_reg_2645_pp0_iter5_reg[49 : 2] <= t64_1_reg_2645[49 : 2];
        t64_2_reg_2682[49 : 2] <= t64_2_fu_1185_p2[49 : 2];
        t64_2_reg_2682_pp0_iter5_reg[49 : 2] <= t64_2_reg_2682[49 : 2];
        t64_3_reg_2719[49 : 2] <= t64_3_fu_1344_p2[49 : 2];
        t64_3_reg_2719_pp0_iter5_reg[49 : 2] <= t64_3_reg_2719[49 : 2];
        t64_reg_2608[49 : 2] <= t64_fu_867_p2[49 : 2];
        t64_reg_2608_pp0_iter5_reg[49 : 2] <= t64_reg_2608[49 : 2];
        tmp_100_reg_2708 <= t64_2_fu_1185_p2[32'd47];
        tmp_100_reg_2708_pp0_iter5_reg <= tmp_100_reg_2708;
        tmp_110_reg_2745 <= t64_3_fu_1344_p2[32'd47];
        tmp_110_reg_2745_pp0_iter5_reg <= tmp_110_reg_2745;
        tmp_80_reg_2634 <= t64_fu_867_p2[32'd47];
        tmp_80_reg_2634_pp0_iter5_reg <= tmp_80_reg_2634;
        tmp_90_reg_2671 <= t64_1_fu_1026_p2[32'd47];
        tmp_90_reg_2671_pp0_iter5_reg <= tmp_90_reg_2671;
        trunc_ln1_reg_2756 <= {{interp_fu_1563_p2[29:12]}};
        trunc_ln78_1_reg_2761 <= {{interp_1_fu_1666_p2[29:12]}};
        trunc_ln78_2_reg_2766 <= {{interp_2_fu_1769_p2[29:12]}};
        trunc_ln78_3_reg_2771 <= {{interp_3_fu_1872_p2[29:12]}};
        x_q16_1_reg_2536 <= x_q16_1_fu_473_p3;
        x_q16_1_reg_2536_pp0_iter3_reg <= x_q16_1_reg_2536;
        x_q16_3_reg_2549 <= x_q16_3_fu_533_p3;
        x_q16_3_reg_2549_pp0_iter3_reg <= x_q16_3_reg_2549;
        x_q16_5_reg_2562 <= x_q16_5_fu_593_p3;
        x_q16_5_reg_2562_pp0_iter3_reg <= x_q16_5_reg_2562;
        x_q16_7_reg_2575 <= x_q16_7_fu_653_p3;
        x_q16_7_reg_2575_pp0_iter3_reg <= x_q16_7_reg_2575;
        y0_1_reg_2665 <= y0_1_fu_1062_p35;
        y0_1_reg_2665_pp0_iter5_reg <= y0_1_reg_2665;
        y0_2_reg_2702 <= y0_2_fu_1221_p35;
        y0_2_reg_2702_pp0_iter5_reg <= y0_2_reg_2702;
        y0_3_reg_2739 <= y0_3_fu_1380_p35;
        y0_3_reg_2739_pp0_iter5_reg <= y0_3_reg_2739;
        y0_reg_2628 <= y0_fu_903_p35;
        y0_reg_2628_pp0_iter5_reg <= y0_reg_2628;
        y_15_reg_2776 <= y_15_fu_1993_p9;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln270_reg_2479 <= icmp_ln270_fu_401_p2;
        icmp_ln270_reg_2479_pp0_iter1_reg <= icmp_ln270_reg_2479;
        icmp_ln274_reg_2490 <= icmp_ln274_fu_419_p2;
        icmp_ln274_reg_2490_pp0_iter1_reg <= icmp_ln274_reg_2490;
        icmp_ln278_reg_2501 <= icmp_ln278_fu_437_p2;
        icmp_ln278_reg_2501_pp0_iter1_reg <= icmp_ln278_reg_2501;
        max_x_read_reg_2454 <= max_x;
        pkt_keep_reg_2466 <= pkt_keep_fu_383_p2;
        pkt_keep_reg_2466_pp0_iter1_reg <= pkt_keep_reg_2466;
        x_q16_2_reg_2518 <= x_q16_2_fu_453_p2;
        x_q16_4_reg_2524 <= x_q16_4_fu_458_p2;
        x_q16_6_reg_2530 <= x_q16_6_fu_463_p2;
        x_q16_reg_2512 <= x_q16_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln270_reg_2479_pp0_iter2_reg <= icmp_ln270_reg_2479_pp0_iter1_reg;
        icmp_ln270_reg_2479_pp0_iter3_reg <= icmp_ln270_reg_2479_pp0_iter2_reg;
        icmp_ln270_reg_2479_pp0_iter4_reg <= icmp_ln270_reg_2479_pp0_iter3_reg;
        icmp_ln270_reg_2479_pp0_iter5_reg <= icmp_ln270_reg_2479_pp0_iter4_reg;
        icmp_ln270_reg_2479_pp0_iter6_reg <= icmp_ln270_reg_2479_pp0_iter5_reg;
        icmp_ln274_reg_2490_pp0_iter2_reg <= icmp_ln274_reg_2490_pp0_iter1_reg;
        icmp_ln274_reg_2490_pp0_iter3_reg <= icmp_ln274_reg_2490_pp0_iter2_reg;
        icmp_ln274_reg_2490_pp0_iter4_reg <= icmp_ln274_reg_2490_pp0_iter3_reg;
        icmp_ln274_reg_2490_pp0_iter5_reg <= icmp_ln274_reg_2490_pp0_iter4_reg;
        icmp_ln274_reg_2490_pp0_iter6_reg <= icmp_ln274_reg_2490_pp0_iter5_reg;
        icmp_ln278_reg_2501_pp0_iter2_reg <= icmp_ln278_reg_2501_pp0_iter1_reg;
        icmp_ln278_reg_2501_pp0_iter3_reg <= icmp_ln278_reg_2501_pp0_iter2_reg;
        icmp_ln278_reg_2501_pp0_iter4_reg <= icmp_ln278_reg_2501_pp0_iter3_reg;
        icmp_ln278_reg_2501_pp0_iter5_reg <= icmp_ln278_reg_2501_pp0_iter4_reg;
        icmp_ln278_reg_2501_pp0_iter6_reg <= icmp_ln278_reg_2501_pp0_iter5_reg;
        pkt_keep_reg_2466_pp0_iter2_reg <= pkt_keep_reg_2466_pp0_iter1_reg;
        pkt_keep_reg_2466_pp0_iter3_reg <= pkt_keep_reg_2466_pp0_iter2_reg;
        pkt_keep_reg_2466_pp0_iter4_reg <= pkt_keep_reg_2466_pp0_iter3_reg;
        pkt_keep_reg_2466_pp0_iter5_reg <= pkt_keep_reg_2466_pp0_iter4_reg;
        pkt_keep_reg_2466_pp0_iter6_reg <= pkt_keep_reg_2466_pp0_iter5_reg;
    end
end

always @ (*) begin
    if (((icmp_ln256_fu_347_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_blk_4 = 7'd0;
    end else begin
        ap_sig_allocacmp_blk_4 = blk_fu_258;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        exp_stream_blk_n = exp_stream_full_n;
    end else begin
        exp_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        exp_stream_write = 1'b1;
    end else begin
        exp_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        logits_buf_0_ce0_local = 1'b1;
    end else begin
        logits_buf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        logits_buf_1_ce0_local = 1'b1;
    end else begin
        logits_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        logits_buf_2_ce0_local = 1'b1;
    end else begin
        logits_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        logits_buf_3_ce0_local = 1'b1;
    end else begin
        logits_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln256_fu_353_p2 = (ap_sig_allocacmp_blk_4 + 7'd1);

assign add_ln64_10_fu_1169_p2 = ($signed(add_ln64_9_reg_2598) + $signed(sext_ln64_19_fu_1165_p1));

assign add_ln64_12_fu_818_p2 = ($signed(sub_ln64_7_reg_2583) + $signed(sext_ln64_24_fu_814_p1));

assign add_ln64_13_fu_834_p2 = ($signed(add_ln64_12_fu_818_p2) + $signed(sext_ln64_25_fu_830_p1));

assign add_ln64_14_fu_1328_p2 = ($signed(add_ln64_13_reg_2603) + $signed(sext_ln64_26_fu_1324_p1));

assign add_ln64_1_fu_735_p2 = ($signed(add_ln64_fu_719_p2) + $signed(sext_ln64_4_fu_731_p1));

assign add_ln64_2_fu_851_p2 = ($signed(add_ln64_1_reg_2588) + $signed(sext_ln64_5_fu_847_p1));

assign add_ln64_4_fu_752_p2 = ($signed(sub_ln64_3_reg_2557) + $signed(sext_ln64_10_fu_748_p1));

assign add_ln64_5_fu_768_p2 = ($signed(add_ln64_4_fu_752_p2) + $signed(sext_ln64_11_fu_764_p1));

assign add_ln64_6_fu_1010_p2 = ($signed(add_ln64_5_reg_2593) + $signed(sext_ln64_12_fu_1006_p1));

assign add_ln64_8_fu_785_p2 = ($signed(sub_ln64_5_reg_2570) + $signed(sext_ln64_17_fu_781_p1));

assign add_ln64_9_fu_801_p2 = ($signed(add_ln64_8_fu_785_p2) + $signed(sext_ln64_18_fu_797_p1));

assign add_ln64_fu_719_p2 = ($signed(sub_ln64_1_reg_2544) + $signed(sext_ln64_3_fu_715_p1));

assign and_ln81_fu_1954_p2 = (xor_ln81_fu_1904_p2 & pkt_keep_reg_2466_pp0_iter5_reg);

assign and_ln87_1_fu_1980_p2 = (pkt_keep_reg_2466_pp0_iter5_reg & and_ln87_fu_1975_p2);

assign and_ln87_2_fu_2095_p2 = (tmp_90_reg_2671_pp0_iter5_reg & icmp_ln87_1_fu_2083_p2);

assign and_ln87_3_fu_2217_p2 = (tmp_100_reg_2708_pp0_iter5_reg & icmp_ln87_2_fu_2205_p2);

assign and_ln87_4_fu_2339_p2 = (tmp_110_reg_2745_pp0_iter5_reg & icmp_ln87_3_fu_2327_p2);

assign and_ln87_fu_1975_p2 = (tmp_80_reg_2634_pp0_iter5_reg & icmp_ln87_fu_1969_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((exp_stream_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exp_stream_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((exp_stream_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exp_stream_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign dy_1_fu_1653_p2 = (y1_1_fu_1579_p35 - zext_ln75_1_fu_1650_p1);

assign dy_2_fu_1756_p2 = (y1_2_fu_1682_p35 - zext_ln75_2_fu_1753_p1);

assign dy_3_fu_1859_p2 = (y1_3_fu_1785_p35 - zext_ln75_3_fu_1856_p1);

assign dy_fu_1550_p2 = (y1_fu_1476_p35 - zext_ln75_fu_1547_p1);

assign exp_stream_din = {{{{{pkt_keep_3_fu_2429_p3}, {pkt_v3_2_reg_2791}}, {pkt_v2_2_reg_2786}}, {pkt_v1_2_reg_2781}}, {y_15_reg_2776}};

assign icmp_ln256_fu_347_p2 = ((ap_sig_allocacmp_blk_4 == trunc_ln) ? 1'b1 : 1'b0);

assign icmp_ln270_fu_401_p2 = ((zext_ln270_fu_397_p1 < n) ? 1'b1 : 1'b0);

assign icmp_ln274_fu_419_p2 = ((zext_ln274_fu_415_p1 < n) ? 1'b1 : 1'b0);

assign icmp_ln278_fu_437_p2 = ((zext_ln278_fu_433_p1 < n) ? 1'b1 : 1'b0);

assign icmp_ln62_1_fu_528_p2 = (($signed(x_q16_2_reg_2518) < $signed(32'd4294443008)) ? 1'b1 : 1'b0);

assign icmp_ln62_2_fu_588_p2 = (($signed(x_q16_4_reg_2524) < $signed(32'd4294443008)) ? 1'b1 : 1'b0);

assign icmp_ln62_3_fu_648_p2 = (($signed(x_q16_6_reg_2530) < $signed(32'd4294443008)) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_468_p2 = (($signed(x_q16_reg_2512) < $signed(32'd4294443008)) ? 1'b1 : 1'b0);

assign icmp_ln83_1_fu_1152_p2 = (($signed(tmp_91_fu_1142_p4) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln83_2_fu_1311_p2 = (($signed(tmp_101_fu_1301_p4) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln83_3_fu_1470_p2 = (($signed(tmp_111_fu_1460_p4) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_993_p2 = (($signed(tmp_81_fu_983_p4) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln87_1_fu_2083_p2 = (($signed(tmp_92_fu_2073_p4) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln87_2_fu_2205_p2 = (($signed(tmp_102_fu_2195_p4) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln87_3_fu_2327_p2 = (($signed(tmp_112_fu_2317_p4) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_1969_p2 = (($signed(tmp_82_fu_1959_p4) < $signed(12'd1)) ? 1'b1 : 1'b0);

assign interp_1_fu_1666_p0 = interp_1_fu_1666_p00;

assign interp_1_fu_1666_p00 = rem_1_reg_2650;

assign interp_2_fu_1769_p0 = interp_2_fu_1769_p00;

assign interp_2_fu_1769_p00 = rem_2_reg_2687;

assign interp_3_fu_1872_p0 = interp_3_fu_1872_p00;

assign interp_3_fu_1872_p00 = rem_3_reg_2724;

assign interp_fu_1563_p0 = interp_fu_1563_p00;

assign interp_fu_1563_p00 = rem_reg_2613;

assign logits_buf_0_address0 = zext_ln256_fu_359_p1;

assign logits_buf_0_ce0 = logits_buf_0_ce0_local;

assign logits_buf_1_address0 = zext_ln256_fu_359_p1;

assign logits_buf_1_ce0 = logits_buf_1_ce0_local;

assign logits_buf_2_address0 = zext_ln256_fu_359_p1;

assign logits_buf_2_ce0 = logits_buf_2_ce0_local;

assign logits_buf_3_address0 = zext_ln256_fu_359_p1;

assign logits_buf_3_ce0 = logits_buf_3_ce0_local;

assign or_ln5_fu_407_p3 = {{trunc_ln258_fu_367_p1}, {2'd2}};

assign or_ln6_fu_425_p3 = {{trunc_ln258_fu_367_p1}, {2'd3}};

assign or_ln_fu_389_p3 = {{trunc_ln258_fu_367_p1}, {2'd1}};

assign pkt_keep_10_fu_2419_p4 = {|(1'd1), zext_ln259_2_fu_2415_p1[3 - 1:0]};

assign pkt_keep_2_fu_2408_p3 = ((icmp_ln274_reg_2490_pp0_iter6_reg[0:0] == 1'b1) ? pkt_keep_9_fu_2400_p3 : zext_ln259_1_fu_2396_p1);

assign pkt_keep_3_fu_2429_p3 = ((icmp_ln278_reg_2501_pp0_iter6_reg[0:0] == 1'b1) ? pkt_keep_10_fu_2419_p4 : zext_ln259_2_fu_2415_p1);

assign pkt_keep_7_fu_2382_p3 = {{1'd1}, {pkt_keep_reg_2466_pp0_iter6_reg}};

assign pkt_keep_8_fu_2389_p3 = ((icmp_ln270_reg_2479_pp0_iter6_reg[0:0] == 1'b1) ? pkt_keep_7_fu_2382_p3 : zext_ln259_fu_2379_p1);

assign pkt_keep_9_fu_2400_p3 = {{1'd1}, {pkt_keep_8_fu_2389_p3}};

assign pkt_keep_fu_383_p2 = ((zext_ln266_fu_379_p1 < n) ? 1'b1 : 1'b0);

assign pkt_v1_2_fu_2128_p3 = ((icmp_ln270_reg_2479_pp0_iter5_reg[0:0] == 1'b1) ? y_16_fu_2108_p9 : 32'd0);

assign pkt_v2_2_fu_2250_p3 = ((icmp_ln274_reg_2490_pp0_iter5_reg[0:0] == 1'b1) ? y_fu_2230_p9 : 32'd0);

assign pkt_v3_2_fu_2372_p3 = ((icmp_ln278_reg_2501_pp0_iter5_reg[0:0] == 1'b1) ? y_17_fu_2352_p9 : 32'd0);

assign sext_ln64_10_fu_748_p1 = $signed(tmp_86_fu_741_p3);

assign sext_ln64_11_fu_764_p1 = $signed(tmp_87_fu_757_p3);

assign sext_ln64_12_fu_1006_p1 = $signed(tmp_88_fu_999_p3);

assign sext_ln64_13_fu_1022_p1 = $signed(tmp_89_fu_1015_p3);

assign sext_ln64_14_fu_608_p1 = $signed(tmp_93_fu_600_p3);

assign sext_ln64_15_fu_620_p1 = $signed(tmp_94_fu_612_p3);

assign sext_ln64_16_fu_638_p1 = $signed(tmp_95_fu_630_p3);

assign sext_ln64_17_fu_781_p1 = $signed(tmp_96_fu_774_p3);

assign sext_ln64_18_fu_797_p1 = $signed(tmp_97_fu_790_p3);

assign sext_ln64_19_fu_1165_p1 = $signed(tmp_98_fu_1158_p3);

assign sext_ln64_1_fu_500_p1 = $signed(tmp_74_fu_492_p3);

assign sext_ln64_20_fu_1181_p1 = $signed(tmp_99_fu_1174_p3);

assign sext_ln64_21_fu_668_p1 = $signed(tmp_103_fu_660_p3);

assign sext_ln64_22_fu_680_p1 = $signed(tmp_104_fu_672_p3);

assign sext_ln64_23_fu_698_p1 = $signed(tmp_105_fu_690_p3);

assign sext_ln64_24_fu_814_p1 = $signed(tmp_106_fu_807_p3);

assign sext_ln64_25_fu_830_p1 = $signed(tmp_107_fu_823_p3);

assign sext_ln64_26_fu_1324_p1 = $signed(tmp_108_fu_1317_p3);

assign sext_ln64_27_fu_1340_p1 = $signed(tmp_109_fu_1333_p3);

assign sext_ln64_2_fu_518_p1 = $signed(tmp_75_fu_510_p3);

assign sext_ln64_3_fu_715_p1 = $signed(tmp_76_fu_708_p3);

assign sext_ln64_4_fu_731_p1 = $signed(tmp_77_fu_724_p3);

assign sext_ln64_5_fu_847_p1 = $signed(tmp_78_fu_840_p3);

assign sext_ln64_6_fu_863_p1 = $signed(tmp_79_fu_856_p3);

assign sext_ln64_7_fu_548_p1 = $signed(tmp_83_fu_540_p3);

assign sext_ln64_8_fu_560_p1 = $signed(tmp_84_fu_552_p3);

assign sext_ln64_9_fu_578_p1 = $signed(tmp_85_fu_570_p3);

assign sext_ln64_fu_488_p1 = $signed(tmp_fu_480_p3);

assign sext_ln78_1_fu_1900_p1 = $signed(y_frac_fu_1894_p2);

assign sext_ln78_2_fu_2016_p1 = $signed(trunc_ln78_1_reg_2761);

assign sext_ln78_3_fu_2025_p1 = $signed(y_frac_1_fu_2019_p2);

assign sext_ln78_4_fu_2138_p1 = $signed(trunc_ln78_2_reg_2766);

assign sext_ln78_5_fu_2147_p1 = $signed(y_frac_2_fu_2141_p2);

assign sext_ln78_6_fu_2260_p1 = $signed(trunc_ln78_3_reg_2771);

assign sext_ln78_7_fu_2269_p1 = $signed(y_frac_3_fu_2263_p2);

assign sext_ln78_fu_1891_p1 = $signed(trunc_ln1_reg_2756);

assign sext_ln86_1_fu_2060_p1 = $signed(k_1_reg_2655_pp0_iter5_reg);

assign sext_ln86_2_fu_2182_p1 = $signed(k_2_reg_2692_pp0_iter5_reg);

assign sext_ln86_3_fu_2304_p1 = $signed(k_3_reg_2729_pp0_iter5_reg);

assign sext_ln86_fu_1935_p1 = $signed(k_reg_2618_pp0_iter5_reg);

assign sh_10_fu_2287_p3 = ((icmp_ln83_3_reg_2751_pp0_iter5_reg[0:0] == 1'b1) ? 4'd15 : trunc_ln82_3_fu_2278_p4);

assign sh_11_fu_2307_p2 = ($signed(17'd0) - $signed(sext_ln86_3_fu_2304_p1));

assign sh_1_fu_1918_p3 = ((icmp_ln83_reg_2640_pp0_iter5_reg[0:0] == 1'b1) ? 4'd15 : trunc_ln2_fu_1909_p4);

assign sh_2_fu_1938_p2 = ($signed(17'd0) - $signed(sext_ln86_fu_1935_p1));

assign sh_4_fu_2043_p3 = ((icmp_ln83_1_reg_2677_pp0_iter5_reg[0:0] == 1'b1) ? 4'd15 : trunc_ln82_1_fu_2034_p4);

assign sh_5_fu_2063_p2 = ($signed(17'd0) - $signed(sext_ln86_1_fu_2060_p1));

assign sh_7_fu_2165_p3 = ((icmp_ln83_2_reg_2714_pp0_iter5_reg[0:0] == 1'b1) ? 4'd15 : trunc_ln82_2_fu_2156_p4);

assign sh_8_fu_2185_p2 = ($signed(17'd0) - $signed(sext_ln86_2_fu_2182_p1));

assign shl_ln_fu_371_p3 = {{trunc_ln258_fu_367_p1}, {2'd0}};

assign sub_ln64_1_fu_522_p2 = ($signed(sub_ln64_fu_504_p2) - $signed(sext_ln64_2_fu_518_p1));

assign sub_ln64_2_fu_564_p2 = ($signed(sext_ln64_7_fu_548_p1) - $signed(sext_ln64_8_fu_560_p1));

assign sub_ln64_3_fu_582_p2 = ($signed(sub_ln64_2_fu_564_p2) - $signed(sext_ln64_9_fu_578_p1));

assign sub_ln64_4_fu_624_p2 = ($signed(sext_ln64_14_fu_608_p1) - $signed(sext_ln64_15_fu_620_p1));

assign sub_ln64_5_fu_642_p2 = ($signed(sub_ln64_4_fu_624_p2) - $signed(sext_ln64_16_fu_638_p1));

assign sub_ln64_6_fu_684_p2 = ($signed(sext_ln64_21_fu_668_p1) - $signed(sext_ln64_22_fu_680_p1));

assign sub_ln64_7_fu_702_p2 = ($signed(sub_ln64_6_fu_684_p2) - $signed(sext_ln64_23_fu_698_p1));

assign sub_ln64_fu_504_p2 = ($signed(sext_ln64_fu_488_p1) - $signed(sext_ln64_1_fu_500_p1));

assign t64_1_fu_1026_p2 = ($signed(add_ln64_6_fu_1010_p2) + $signed(sext_ln64_13_fu_1022_p1));

assign t64_2_fu_1185_p2 = ($signed(add_ln64_10_fu_1169_p2) + $signed(sext_ln64_20_fu_1181_p1));

assign t64_3_fu_1344_p2 = ($signed(add_ln64_14_fu_1328_p2) + $signed(sext_ln64_27_fu_1340_p1));

assign t64_fu_867_p2 = ($signed(add_ln64_2_fu_851_p2) + $signed(sext_ln64_6_fu_863_p1));

assign tmp_101_fu_1301_p4 = {{t64_2_fu_1185_p2[47:36]}};

assign tmp_102_fu_2195_p4 = {{sh_8_fu_2185_p2[16:5]}};

assign tmp_103_fu_660_p3 = {{x_q16_7_fu_653_p3}, {17'd0}};

assign tmp_104_fu_672_p3 = {{x_q16_7_fu_653_p3}, {15'd0}};

assign tmp_105_fu_690_p3 = {{x_q16_7_fu_653_p3}, {12'd0}};

assign tmp_106_fu_807_p3 = {{x_q16_7_reg_2575}, {8'd0}};

assign tmp_107_fu_823_p3 = {{x_q16_7_reg_2575}, {6'd0}};

assign tmp_108_fu_1317_p3 = {{x_q16_7_reg_2575_pp0_iter3_reg}, {4'd0}};

assign tmp_109_fu_1333_p3 = {{x_q16_7_reg_2575_pp0_iter3_reg}, {2'd0}};

assign tmp_111_fu_1460_p4 = {{t64_3_fu_1344_p2[47:36]}};

assign tmp_112_fu_2317_p4 = {{sh_11_fu_2307_p2[16:5]}};

assign tmp_74_fu_492_p3 = {{x_q16_1_fu_473_p3}, {15'd0}};

assign tmp_75_fu_510_p3 = {{x_q16_1_fu_473_p3}, {12'd0}};

assign tmp_76_fu_708_p3 = {{x_q16_1_reg_2536}, {8'd0}};

assign tmp_77_fu_724_p3 = {{x_q16_1_reg_2536}, {6'd0}};

assign tmp_78_fu_840_p3 = {{x_q16_1_reg_2536_pp0_iter3_reg}, {4'd0}};

assign tmp_79_fu_856_p3 = {{x_q16_1_reg_2536_pp0_iter3_reg}, {2'd0}};

assign tmp_81_fu_983_p4 = {{t64_fu_867_p2[47:36]}};

assign tmp_82_fu_1959_p4 = {{sh_2_fu_1938_p2[16:5]}};

assign tmp_83_fu_540_p3 = {{x_q16_3_fu_533_p3}, {17'd0}};

assign tmp_84_fu_552_p3 = {{x_q16_3_fu_533_p3}, {15'd0}};

assign tmp_85_fu_570_p3 = {{x_q16_3_fu_533_p3}, {12'd0}};

assign tmp_86_fu_741_p3 = {{x_q16_3_reg_2549}, {8'd0}};

assign tmp_87_fu_757_p3 = {{x_q16_3_reg_2549}, {6'd0}};

assign tmp_88_fu_999_p3 = {{x_q16_3_reg_2549_pp0_iter3_reg}, {4'd0}};

assign tmp_89_fu_1015_p3 = {{x_q16_3_reg_2549_pp0_iter3_reg}, {2'd0}};

assign tmp_91_fu_1142_p4 = {{t64_1_fu_1026_p2[47:36]}};

assign tmp_92_fu_2073_p4 = {{sh_5_fu_2063_p2[16:5]}};

assign tmp_93_fu_600_p3 = {{x_q16_5_fu_593_p3}, {17'd0}};

assign tmp_94_fu_612_p3 = {{x_q16_5_fu_593_p3}, {15'd0}};

assign tmp_95_fu_630_p3 = {{x_q16_5_fu_593_p3}, {12'd0}};

assign tmp_96_fu_774_p3 = {{x_q16_5_reg_2562}, {8'd0}};

assign tmp_97_fu_790_p3 = {{x_q16_5_reg_2562}, {6'd0}};

assign tmp_98_fu_1158_p3 = {{x_q16_5_reg_2562_pp0_iter3_reg}, {4'd0}};

assign tmp_99_fu_1174_p3 = {{x_q16_5_reg_2562_pp0_iter3_reg}, {2'd0}};

assign tmp_fu_480_p3 = {{x_q16_1_fu_473_p3}, {17'd0}};

assign trunc_ln258_fu_367_p1 = ap_sig_allocacmp_blk_4[5:0];

assign trunc_ln2_fu_1909_p4 = {{t64_reg_2608_pp0_iter5_reg[35:32]}};

assign trunc_ln82_1_fu_2034_p4 = {{t64_1_reg_2645_pp0_iter5_reg[35:32]}};

assign trunc_ln82_2_fu_2156_p4 = {{t64_2_reg_2682_pp0_iter5_reg[35:32]}};

assign trunc_ln82_3_fu_2278_p4 = {{t64_3_reg_2719_pp0_iter5_reg[35:32]}};

assign x_q16_1_fu_473_p3 = ((icmp_ln62_fu_468_p2[0:0] == 1'b1) ? 32'd4294443008 : x_q16_reg_2512);

assign x_q16_2_fu_453_p2 = (logits_buf_1_q0 - max_x_read_reg_2454);

assign x_q16_3_fu_533_p3 = ((icmp_ln62_1_fu_528_p2[0:0] == 1'b1) ? 32'd4294443008 : x_q16_2_reg_2518);

assign x_q16_4_fu_458_p2 = (logits_buf_2_q0 - max_x_read_reg_2454);

assign x_q16_5_fu_593_p3 = ((icmp_ln62_2_fu_588_p2[0:0] == 1'b1) ? 32'd4294443008 : x_q16_4_reg_2524);

assign x_q16_6_fu_463_p2 = (logits_buf_3_q0 - max_x_read_reg_2454);

assign x_q16_7_fu_653_p3 = ((icmp_ln62_3_fu_648_p2[0:0] == 1'b1) ? 32'd4294443008 : x_q16_6_reg_2530);

assign x_q16_fu_448_p2 = (logits_buf_0_q0 - max_x_read_reg_2454);

assign xor_ln81_1_fu_2029_p2 = (tmp_90_reg_2671_pp0_iter5_reg ^ 1'd1);

assign xor_ln81_2_fu_2151_p2 = (tmp_100_reg_2708_pp0_iter5_reg ^ 1'd1);

assign xor_ln81_3_fu_2273_p2 = (tmp_110_reg_2745_pp0_iter5_reg ^ 1'd1);

assign xor_ln81_fu_1904_p2 = (tmp_80_reg_2634_pp0_iter5_reg ^ 1'd1);

assign y0_1_fu_1062_p33 = 'bx;

assign y0_1_fu_1062_p34 = {{t64_1_fu_1026_p2[31:28]}};

assign y0_2_fu_1221_p33 = 'bx;

assign y0_2_fu_1221_p34 = {{t64_2_fu_1185_p2[31:28]}};

assign y0_3_fu_1380_p33 = 'bx;

assign y0_3_fu_1380_p34 = {{t64_3_fu_1344_p2[31:28]}};

assign y0_fu_903_p33 = 'bx;

assign y0_fu_903_p34 = {{t64_fu_867_p2[31:28]}};

assign y1_1_fu_1579_p33 = 'bx;

assign y1_2_fu_1682_p33 = 'bx;

assign y1_3_fu_1785_p33 = 'bx;

assign y1_fu_1476_p33 = 'bx;

assign y_15_fu_1993_p2 = sext_ln78_1_fu_1900_p1 << zext_ln82_fu_1925_p1;

assign y_15_fu_1993_p4 = sext_ln78_1_fu_1900_p1 >> zext_ln86_fu_1944_p1;

assign y_15_fu_1993_p7 = 'bx;

assign y_15_fu_1993_p8 = {{and_ln81_fu_1954_p2}, {and_ln87_1_fu_1980_p2}};

assign y_16_fu_2108_p2 = sext_ln78_3_fu_2025_p1 << zext_ln82_1_fu_2050_p1;

assign y_16_fu_2108_p6 = sext_ln78_3_fu_2025_p1 >> zext_ln86_1_fu_2069_p1;

assign y_16_fu_2108_p7 = 'bx;

assign y_16_fu_2108_p8 = {{xor_ln81_1_fu_2029_p2}, {and_ln87_2_fu_2095_p2}};

assign y_17_fu_2352_p2 = sext_ln78_7_fu_2269_p1 << zext_ln82_3_fu_2294_p1;

assign y_17_fu_2352_p6 = sext_ln78_7_fu_2269_p1 >> zext_ln86_3_fu_2313_p1;

assign y_17_fu_2352_p7 = 'bx;

assign y_17_fu_2352_p8 = {{xor_ln81_3_fu_2273_p2}, {and_ln87_4_fu_2339_p2}};

assign y_frac_1_fu_2019_p2 = ($signed(sext_ln78_2_fu_2016_p1) + $signed(zext_ln73_1_fu_2013_p1));

assign y_frac_2_fu_2141_p2 = ($signed(sext_ln78_4_fu_2138_p1) + $signed(zext_ln73_2_fu_2135_p1));

assign y_frac_3_fu_2263_p2 = ($signed(sext_ln78_6_fu_2260_p1) + $signed(zext_ln73_3_fu_2257_p1));

assign y_frac_fu_1894_p2 = ($signed(sext_ln78_fu_1891_p1) + $signed(zext_ln73_fu_1888_p1));

assign y_fu_2230_p2 = sext_ln78_5_fu_2147_p1 << zext_ln82_2_fu_2172_p1;

assign y_fu_2230_p6 = sext_ln78_5_fu_2147_p1 >> zext_ln86_2_fu_2191_p1;

assign y_fu_2230_p7 = 'bx;

assign y_fu_2230_p8 = {{xor_ln81_2_fu_2151_p2}, {and_ln87_3_fu_2217_p2}};

assign zext_ln256_fu_359_p1 = ap_sig_allocacmp_blk_4;

assign zext_ln259_1_fu_2396_p1 = pkt_keep_8_fu_2389_p3;

assign zext_ln259_2_fu_2415_p1 = pkt_keep_2_fu_2408_p3;

assign zext_ln259_fu_2379_p1 = pkt_keep_reg_2466_pp0_iter6_reg;

assign zext_ln266_fu_379_p1 = shl_ln_fu_371_p3;

assign zext_ln270_fu_397_p1 = or_ln_fu_389_p3;

assign zext_ln274_fu_415_p1 = or_ln5_fu_407_p3;

assign zext_ln278_fu_433_p1 = or_ln6_fu_425_p3;

assign zext_ln73_1_fu_2013_p1 = y0_1_reg_2665_pp0_iter5_reg;

assign zext_ln73_2_fu_2135_p1 = y0_2_reg_2702_pp0_iter5_reg;

assign zext_ln73_3_fu_2257_p1 = y0_3_reg_2739_pp0_iter5_reg;

assign zext_ln73_fu_1888_p1 = y0_reg_2628_pp0_iter5_reg;

assign zext_ln75_1_fu_1650_p1 = y0_1_reg_2665;

assign zext_ln75_2_fu_1753_p1 = y0_2_reg_2702;

assign zext_ln75_3_fu_1856_p1 = y0_3_reg_2739;

assign zext_ln75_fu_1547_p1 = y0_reg_2628;

assign zext_ln82_1_fu_2050_p1 = sh_4_fu_2043_p3;

assign zext_ln82_2_fu_2172_p1 = sh_7_fu_2165_p3;

assign zext_ln82_3_fu_2294_p1 = sh_10_fu_2287_p3;

assign zext_ln82_fu_1925_p1 = sh_1_fu_1918_p3;

assign zext_ln86_1_fu_2069_p1 = sh_5_fu_2063_p2;

assign zext_ln86_2_fu_2191_p1 = sh_8_fu_2185_p2;

assign zext_ln86_3_fu_2313_p1 = sh_11_fu_2307_p2;

assign zext_ln86_fu_1944_p1 = sh_2_fu_1938_p2;

always @ (posedge ap_clk) begin
    sub_ln64_1_reg_2544[11:0] <= 12'b000000000000;
    sub_ln64_3_reg_2557[11:0] <= 12'b000000000000;
    sub_ln64_5_reg_2570[11:0] <= 12'b000000000000;
    sub_ln64_7_reg_2583[11:0] <= 12'b000000000000;
    add_ln64_1_reg_2588[5:0] <= 6'b000000;
    add_ln64_5_reg_2593[5:0] <= 6'b000000;
    add_ln64_9_reg_2598[5:0] <= 6'b000000;
    add_ln64_13_reg_2603[5:0] <= 6'b000000;
    t64_reg_2608[1:0] <= 2'b00;
    t64_reg_2608_pp0_iter5_reg[1:0] <= 2'b00;
    t64_1_reg_2645[1:0] <= 2'b00;
    t64_1_reg_2645_pp0_iter5_reg[1:0] <= 2'b00;
    t64_2_reg_2682[1:0] <= 2'b00;
    t64_2_reg_2682_pp0_iter5_reg[1:0] <= 2'b00;
    t64_3_reg_2719[1:0] <= 2'b00;
    t64_3_reg_2719_pp0_iter5_reg[1:0] <= 2'b00;
end

endmodule //softmax_accel_emit_exp_stream_Pipeline_exp_emit_loop
