// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cpu_cpu_Pipeline_PROGRAM_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reg_file_address0,
        reg_file_ce0,
        reg_file_we0,
        reg_file_d0,
        reg_file_q0,
        reg_file_address1,
        reg_file_ce1,
        reg_file_q1,
        mem_address0,
        mem_ce0,
        mem_we0,
        mem_d0,
        mem_q0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_pp0_stage0 = 8'd2;
parameter    ap_ST_fsm_pp0_stage1 = 8'd4;
parameter    ap_ST_fsm_pp0_stage2 = 8'd8;
parameter    ap_ST_fsm_pp0_stage3 = 8'd16;
parameter    ap_ST_fsm_pp0_stage4 = 8'd32;
parameter    ap_ST_fsm_state8 = 8'd64;
parameter    ap_ST_fsm_state9 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] reg_file_address0;
output   reg_file_ce0;
output   reg_file_we0;
output  [31:0] reg_file_d0;
input  [31:0] reg_file_q0;
output  [4:0] reg_file_address1;
output   reg_file_ce1;
input  [31:0] reg_file_q1;
output  [12:0] mem_address0;
output   mem_ce0;
output   mem_we0;
output  [31:0] mem_d0;
input  [31:0] mem_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] imm_reg_208;
reg   [31:0] pc_1_reg_1184;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln40_fu_377_p2;
reg   [0:0] or_ln40_reg_1190;
reg    ap_enable_reg_pp0_iter0;
wire   [6:0] opcode_fu_398_p1;
reg   [6:0] opcode_reg_1199;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [5:0] trunc_ln56_1_fu_402_p1;
reg   [5:0] trunc_ln56_1_reg_1207;
reg   [4:0] rd_reg_1211;
wire   [4:0] rs2_fu_422_p3;
reg   [4:0] rs2_reg_1218;
reg   [2:0] func3_reg_1223;
reg   [6:0] func7_reg_1232;
reg   [11:0] immI_reg_1239;
reg   [3:0] tmp_2_reg_1244;
reg   [5:0] tmp_3_reg_1249;
reg   [0:0] tmp_4_reg_1254;
reg   [0:0] tmp_5_reg_1259;
reg   [9:0] tmp_s_reg_1265;
reg   [0:0] tmp_8_reg_1270;
reg   [7:0] tmp_6_reg_1275;
reg   [19:0] tmp_reg_1280;
reg  signed [31:0] src1_reg_1295;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage2_11001;
reg  signed [31:0] src2_reg_1319;
wire   [0:0] grp_fu_310_p2;
reg   [0:0] icmp_ln226_reg_1331;
wire   [1:0] trunc_ln231_fu_657_p1;
reg   [1:0] trunc_ln231_reg_1335;
reg   [12:0] lshr_ln2_reg_1340;
reg   [16:0] tmp_10_reg_1345;
reg   [0:0] icmp_ln203_reg_1350;
wire   [0:0] icmp_ln144_fu_681_p2;
reg   [0:0] icmp_ln144_reg_1354;
wire   [0:0] icmp_ln14_1_fu_702_p2;
reg   [0:0] icmp_ln14_1_reg_1358;
wire   [0:0] or_ln14_fu_707_p2;
reg   [0:0] or_ln14_reg_1362;
wire   [0:0] grp_fu_315_p2;
reg   [0:0] icmp_ln134_reg_1366;
reg   [0:0] icmp_ln188_1_reg_1371;
reg   [0:0] icmp_ln180_1_reg_1376;
wire   [0:0] take_6_fu_730_p2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire   [0:0] grp_fu_320_p2;
wire   [0:0] take_3_fu_736_p2;
wire   [0:0] grp_fu_324_p2;
wire   [0:0] take_1_fu_742_p2;
wire   [0:0] take_fu_746_p2;
wire   [0:0] or_ln233_fu_760_p2;
reg   [0:0] or_ln233_reg_1411;
wire   [0:0] or_ln210_fu_806_p2;
reg   [0:0] or_ln210_reg_1415;
wire  signed [63:0] sext_ln151_fu_817_p1;
wire   [63:0] zext_ln152_1_fu_830_p1;
wire   [31:0] res_15_fu_848_p3;
reg   [31:0] res_15_reg_1446;
wire   [31:0] res_12_fu_855_p2;
reg   [31:0] res_12_reg_1451;
wire   [31:0] op2_1_fu_865_p3;
reg   [31:0] op2_1_reg_1456;
wire   [0:0] and_ln188_fu_876_p2;
reg   [0:0] and_ln188_reg_1467;
wire   [31:0] res_36_fu_885_p2;
reg   [31:0] res_36_reg_1471;
wire   [31:0] res_35_fu_890_p2;
reg   [31:0] res_35_reg_1476;
wire   [31:0] res_29_fu_899_p2;
reg   [31:0] res_29_reg_1481;
wire   [31:0] next_pc_4_fu_904_p2;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire   [63:0] grp_fu_306_p2;
reg   [63:0] prod_ss_reg_1497;
reg   [31:0] res_34_reg_1503;
reg   [31:0] res_33_reg_1508;
wire   [0:0] res_30_fu_1015_p2;
reg   [0:0] res_30_reg_1513;
wire   [31:0] res_25_fu_1067_p3;
wire   [0:0] res_16_fu_1080_p2;
reg   [0:0] res_16_reg_1523;
wire   [31:0] grp_fu_338_p2;
wire    ap_block_pp0_stage4_subdone;
reg    ap_predicate_tran6to8_state6;
reg    ap_condition_pp0_exit_iter0_state6;
reg    ap_enable_reg_pp0_iter1;
reg   [31:0] ap_phi_mux_imm_phi_fu_211_p12;
wire   [31:0] ap_phi_reg_pp0_iter0_imm_reg_208;
wire  signed [31:0] sext_ln77_fu_623_p1;
wire  signed [31:0] sext_ln73_fu_608_p1;
wire  signed [31:0] sext_ln81_fu_638_p1;
wire   [31:0] immU_fu_643_p3;
wire  signed [31:0] sext_ln70_fu_598_p1;
reg   [0:0] ap_phi_reg_pp0_iter0_take_4_reg_227;
reg    ap_predicate_pred381_state5;
reg    ap_predicate_pred385_state5;
reg    ap_predicate_pred391_state5;
reg    ap_predicate_pred397_state5;
reg    ap_predicate_pred403_state5;
reg    ap_predicate_pred409_state5;
reg   [31:0] ap_phi_mux_res_17_phi_fu_248_p44;
wire   [31:0] ap_phi_reg_pp0_iter0_res_17_reg_244;
reg   [31:0] ap_phi_reg_pp0_iter1_res_17_reg_244;
reg    ap_predicate_pred370_state6;
reg    ap_predicate_pred375_state6;
reg    ap_predicate_pred367_state6;
reg    ap_predicate_pred440_state6;
reg    ap_predicate_pred447_state6;
reg    ap_predicate_pred471_state6;
wire   [31:0] res_26_fu_1122_p2;
wire   [31:0] res_27_fu_1117_p2;
wire   [31:0] res_28_fu_1112_p2;
reg    ap_predicate_pred554_state6;
wire   [31:0] zext_ln191_fu_1108_p1;
wire   [31:0] zext_ln192_fu_1127_p1;
reg    ap_predicate_pred371_state6;
wire   [31:0] res_31_fu_1104_p1;
reg    ap_predicate_pred689_state6;
wire   [63:0] zext_ln49_fu_393_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln103_fu_542_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln104_fu_547_p1;
wire   [63:0] zext_ln242_fu_766_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln219_fu_812_p1;
wire   [63:0] zext_ln297_fu_1152_p1;
wire   [0:0] or_ln14_1_fu_1141_p2;
wire   [0:0] icmp_ln296_fu_1147_p2;
reg   [31:0] pc_fu_142;
wire   [31:0] next_pc_2_fu_924_p3;
wire   [31:0] next_pc_3_fu_942_p3;
reg    ap_predicate_pred655_state6;
reg    ap_predicate_pred663_state6;
reg    ap_predicate_pred672_state6;
reg    ap_predicate_pred681_state6;
reg    ap_predicate_pred575_state6;
reg    ap_predicate_pred534_state6;
reg    ap_predicate_pred513_state6;
reg    ap_predicate_pred492_state6;
reg    ap_predicate_pred596_state6;
reg    mem_ce0_local;
reg   [12:0] mem_address0_local;
reg    mem_we0_local;
reg    reg_file_ce1_local;
reg    reg_file_ce0_local;
reg   [4:0] reg_file_address0_local;
reg    reg_file_we0_local;
wire   [31:0] grp_fu_298_p0;
wire   [31:0] grp_fu_298_p1;
wire   [31:0] grp_fu_302_p0;
wire  signed [31:0] grp_fu_302_p1;
wire  signed [31:0] grp_fu_306_p1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage4;
wire   [1:0] trunc_ln27_fu_351_p1;
wire   [16:0] tmp_1_fu_361_p4;
wire   [0:0] icmp_ln40_fu_355_p2;
wire   [0:0] icmp_ln44_fu_371_p2;
wire   [12:0] lshr_ln_fu_383_p4;
wire   [4:0] rs1_fu_414_p3;
wire   [11:0] simm_fu_602_p3;
wire   [12:0] bimm_fu_613_p6;
wire   [20:0] jimm_fu_628_p6;
wire  signed [31:0] addr_1_fu_651_p0;
wire   [31:0] addr_1_fu_651_p2;
wire   [0:0] icmp_ln14_fu_697_p2;
wire   [0:0] icmp_ln233_fu_750_p2;
wire   [0:0] icmp_ln237_fu_755_p2;
wire   [31:0] grp_fu_328_p2;
wire   [1:0] trunc_ln208_fu_770_p1;
wire   [16:0] tmp_9_fu_790_p4;
wire   [0:0] icmp_ln210_fu_774_p2;
wire   [0:0] icmp_ln214_fu_800_p2;
wire   [12:0] lshr_ln1_fu_780_p4;
wire   [31:0] zext_ln127_fu_835_p1;
wire   [31:0] res_13_fu_838_p2;
wire   [31:0] res_14_fu_843_p2;
wire   [0:0] icmp_ln173_fu_860_p2;
wire   [0:0] grp_fu_333_p2;
wire   [4:0] trunc_ln173_fu_872_p1;
wire   [31:0] zext_ln188_fu_881_p1;
wire   [31:0] zext_ln186_fu_895_p1;
wire   [30:0] tmp_7_fu_914_p4;
wire   [63:0] grp_fu_298_p2;
wire   [63:0] grp_fu_302_p2;
wire   [0:0] and_ln180_fu_1054_p2;
wire   [31:0] res_23_fu_1059_p2;
wire   [31:0] res_24_fu_1063_p2;
wire   [0:0] icmp_ln14_3_fu_1136_p2;
wire   [0:0] icmp_ln14_2_fu_1131_p2;
reg    ap_predicate_pred1387_state7;
wire    ap_CS_fsm_state8;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [63:0] grp_fu_298_p10;
reg    ap_condition_181;
reg    ap_condition_315;
reg    ap_condition_372;
reg    ap_condition_377;
reg    ap_condition_144;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 pc_fu_142 = 32'd0;
end

cpu_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_298_p0),
    .din1(grp_fu_298_p1),
    .ce(1'b1),
    .dout(grp_fu_298_p2)
);

cpu_mul_32ns_32s_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32s_64_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_302_p0),
    .din1(grp_fu_302_p1),
    .ce(1'b1),
    .dout(grp_fu_302_p2)
);

cpu_mul_32s_32s_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32s_64_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(src2_reg_1319),
    .din1(grp_fu_306_p1),
    .ce(1'b1),
    .dout(grp_fu_306_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state6);
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_181)) begin
        if ((ap_predicate_pred409_state5 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_take_4_reg_227 <= take_6_fu_730_p2;
        end else if ((ap_predicate_pred403_state5 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_take_4_reg_227 <= grp_fu_320_p2;
        end else if ((ap_predicate_pred397_state5 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_take_4_reg_227 <= take_3_fu_736_p2;
        end else if ((ap_predicate_pred391_state5 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_take_4_reg_227 <= grp_fu_324_p2;
        end else if ((ap_predicate_pred385_state5 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_take_4_reg_227 <= take_1_fu_742_p2;
        end else if ((ap_predicate_pred381_state5 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_take_4_reg_227 <= take_fu_746_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred689_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred371_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= imm_reg_208;
    end else if (((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln210_reg_1415 == 1'd0) & (icmp_ln203_reg_1350 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= mem_q0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (func3_reg_1223 == 3'd5)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd5) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd5))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & 
    (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd5) & (trunc_ln56_1_reg_1207 == 6'd19))))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= res_36_reg_1471;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (func3_reg_1223 == 3'd5)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd5) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd5))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & 
    (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd5) & (trunc_ln56_1_reg_1207 == 6'd19))))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= res_35_reg_1476;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred554_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= res_29_reg_1481;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred471_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= res_25_fu_1067_p3;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred447_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= res_15_reg_1446;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred440_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= res_12_reg_1451;
    end else if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred367_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred375_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= next_pc_4_fu_904_p2;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred370_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= grp_fu_338_p2;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_phi_reg_pp0_iter1_res_17_reg_244 <= ap_phi_reg_pp0_iter0_res_17_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((1'b1 == ap_condition_377)) begin
            imm_reg_208 <= sext_ln70_fu_598_p1;
        end else if ((1'b1 == ap_condition_372)) begin
            imm_reg_208 <= immU_fu_643_p3;
        end else if (((opcode_reg_1199 == 7'd111) & (or_ln40_reg_1190 == 1'd0))) begin
            imm_reg_208 <= sext_ln81_fu_638_p1;
        end else if (((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0))) begin
            imm_reg_208 <= sext_ln73_fu_608_p1;
        end else if (((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0))) begin
            imm_reg_208 <= sext_ln77_fu_623_p1;
        end else if ((1'b1 == ap_condition_315)) begin
            imm_reg_208 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            imm_reg_208 <= ap_phi_reg_pp0_iter0_imm_reg_208;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        pc_fu_142 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred689_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        pc_fu_142 <= next_pc_3_fu_942_p3;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred367_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        pc_fu_142 <= grp_fu_338_p2;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred375_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        pc_fu_142 <= next_pc_2_fu_924_p3;
    end else if ((((ap_predicate_pred596_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_predicate_pred492_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_predicate_pred513_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_predicate_pred534_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_predicate_pred575_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_predicate_pred681_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_predicate_pred672_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) 
    & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_predicate_pred663_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_predicate_pred655_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln233_reg_1411 == 1'd0) & (icmp_ln226_reg_1331 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln210_reg_1415 == 1'd0) & (icmp_ln203_reg_1350 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred371_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred554_state6 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred471_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred447_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred440_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_pred370_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (func3_reg_1223 == 3'd5)) | (~(trunc_ln56_1_reg_1207 
    == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd5) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd5))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd0 == and_ln188_reg_1467) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd5) & (trunc_ln56_1_reg_1207 == 6'd19)))) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & ((((((~(trunc_ln56_1_reg_1207 
    == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (func3_reg_1223 == 3'd5)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd5) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd5))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (1'd1 == and_ln188_reg_1467) & (or_ln14_reg_1362 == 1'd0) 
    & (func3_reg_1223 == 3'd5) & (trunc_ln56_1_reg_1207 == 6'd19)))))) begin
        pc_fu_142 <= next_pc_4_fu_904_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        and_ln188_reg_1467 <= and_ln188_fu_876_p2;
        ap_predicate_pred367_state6 <= ((opcode_reg_1199 == 7'd111) & (or_ln40_reg_1190 == 1'd0));
        ap_predicate_pred370_state6 <= ((opcode_reg_1199 == 7'd23) & (or_ln40_reg_1190 == 1'd0));
        ap_predicate_pred371_state6 <= ((opcode_reg_1199 == 7'd55) & (or_ln40_reg_1190 == 1'd0));
        ap_predicate_pred375_state6 <= ((opcode_reg_1199 == 7'd103) & (or_ln40_reg_1190 == 1'd0));
        ap_predicate_pred440_state6 <= (((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd1) & (icmp_ln14_1_reg_1358 == 1'd1) & (trunc_ln56_1_reg_1207 == 6'd19)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd1) & (icmp_ln14_1_reg_1358 == 1'd1) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred447_state6 <= (((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd1) & (icmp_ln14_1_reg_1358 == 1'd0) & (trunc_ln56_1_reg_1207 == 6'd19)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd1) & (icmp_ln14_1_reg_1358 == 1'd0) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred471_state6 <= ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd0)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd0))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd0) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd0))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd0))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd0) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred492_state6 <= ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd4)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd4))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd4) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd4))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd4))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd4) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred513_state6 <= ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd6)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd6))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd6) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd6))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd6))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd6) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred534_state6 <= ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd7)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd7))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd7) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd7))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd7))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd7) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred554_state6 <= ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd1)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd1))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd1) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd1))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd1))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd1) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred575_state6 <= ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd2)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd2) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd2))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd2) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred596_state6 <= ((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd3)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd3) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd3))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd3) & (trunc_ln56_1_reg_1207 == 6'd19)));
        ap_predicate_pred655_state6 <= (((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd3) & (trunc_ln56_1_reg_1207 == 6'd51)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd3) & (trunc_ln56_1_reg_1207 == 6'd51)));
        ap_predicate_pred663_state6 <= (((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd2) & (trunc_ln56_1_reg_1207 == 6'd51)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd2) & (trunc_ln56_1_reg_1207 == 6'd51)));
        ap_predicate_pred672_state6 <= (((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd1) & (trunc_ln56_1_reg_1207 == 6'd51)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd1) & (trunc_ln56_1_reg_1207 == 6'd51)));
        ap_predicate_pred681_state6 <= (((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd0) & (trunc_ln56_1_reg_1207 == 6'd51)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd0) & (trunc_ln56_1_reg_1207 == 6'd51)));
        ap_predicate_pred689_state6 <= (((((((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd7)) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd6))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd4))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd1))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd0)));
        op2_1_reg_1456 <= op2_1_fu_865_p3;
        or_ln210_reg_1415 <= or_ln210_fu_806_p2;
        or_ln233_reg_1411 <= or_ln233_fu_760_p2;
        res_12_reg_1451 <= res_12_fu_855_p2;
        res_15_reg_1446 <= res_15_fu_848_p3;
        res_29_reg_1481 <= res_29_fu_899_p2;
        res_35_reg_1476 <= res_35_fu_890_p2;
        res_36_reg_1471 <= res_36_fu_885_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_predicate_pred1387_state7 <= (((((((((((((((((((((((((((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd1)) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd0))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0))) | (~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (trunc_ln56_1_reg_1207 == 6'd19))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd1))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd0))) | ((opcode_reg_1199 == 7'd23) & (or_ln40_reg_1190 == 1'd0))) | ((opcode_reg_1199 == 7'd55) & (or_ln40_reg_1190 == 1'd0))) | ((opcode_reg_1199 == 7'd111) & (or_ln40_reg_1190 == 1'd0))) | ((opcode_reg_1199 
    == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd7))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd6))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd4))) | ((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0) & (or_ln233_reg_1411 == 1'd0) & (icmp_ln226_reg_1331 == 1'd1))) | ((opcode_reg_1199 == 7'd103) & (or_ln40_reg_1190 == 1'd0))) | ((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (or_ln210_reg_1415 == 1'd0) & (icmp_ln203_reg_1350 == 1'd1))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0))) | (~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (trunc_ln56_1_reg_1207 == 6'd19))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 
    == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd1))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd0)));
        prod_ss_reg_1497 <= grp_fu_306_p2;
        res_16_reg_1523 <= res_16_fu_1080_p2;
        res_30_reg_1513 <= res_30_fu_1015_p2;
        res_33_reg_1508 <= {{grp_fu_302_p2[63:32]}};
        res_34_reg_1503 <= {{grp_fu_298_p2[63:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_predicate_pred381_state5 <= ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd0));
        ap_predicate_pred385_state5 <= ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd1));
        ap_predicate_pred391_state5 <= ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd4));
        ap_predicate_pred397_state5 <= ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd5));
        ap_predicate_pred403_state5 <= ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd6));
        ap_predicate_pred409_state5 <= ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd7));
        icmp_ln144_reg_1354 <= icmp_ln144_fu_681_p2;
        icmp_ln14_1_reg_1358 <= icmp_ln14_1_fu_702_p2;
        lshr_ln2_reg_1340 <= {{addr_1_fu_651_p2[14:2]}};
        or_ln14_reg_1362 <= or_ln14_fu_707_p2;
        tmp_10_reg_1345 <= {{addr_1_fu_651_p2[31:15]}};
        trunc_ln231_reg_1335 <= trunc_ln231_fu_657_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        func3_reg_1223 <= {{mem_q0[14:12]}};
        func7_reg_1232 <= {{mem_q0[31:25]}};
        immI_reg_1239 <= {{mem_q0[31:20]}};
        opcode_reg_1199 <= opcode_fu_398_p1;
        rd_reg_1211 <= {{mem_q0[11:7]}};
        rs2_reg_1218 <= {{mem_q0[24:20]}};
        tmp_2_reg_1244 <= {{mem_q0[11:8]}};
        tmp_3_reg_1249 <= {{mem_q0[30:25]}};
        tmp_4_reg_1254 <= mem_q0[32'd7];
        tmp_5_reg_1259 <= mem_q0[32'd31];
        tmp_6_reg_1275 <= {{mem_q0[19:12]}};
        tmp_8_reg_1270 <= mem_q0[32'd20];
        tmp_reg_1280 <= {{mem_q0[31:12]}};
        tmp_s_reg_1265 <= {{mem_q0[30:21]}};
        trunc_ln56_1_reg_1207 <= trunc_ln56_1_fu_402_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        icmp_ln134_reg_1366 <= grp_fu_315_p2;
        icmp_ln180_1_reg_1376 <= grp_fu_315_p2;
        icmp_ln188_1_reg_1371 <= grp_fu_315_p2;
        icmp_ln203_reg_1350 <= grp_fu_310_p2;
        icmp_ln226_reg_1331 <= grp_fu_310_p2;
        src1_reg_1295 <= reg_file_q1;
        src2_reg_1319 <= reg_file_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln40_reg_1190 <= or_ln40_fu_377_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pc_1_reg_1184 <= pc_fu_142;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((or_ln40_reg_1190 == 1'd1) | (ap_predicate_tran6to8_state6 == 1'b1))) begin
        ap_condition_pp0_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((((opcode_reg_1199 == 7'd103) & (or_ln40_reg_1190 == 1'd0)) | ((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0)))) begin
        ap_phi_mux_imm_phi_fu_211_p12 = sext_ln70_fu_598_p1;
    end else if ((((opcode_reg_1199 == 7'd23) & (or_ln40_reg_1190 == 1'd0)) | ((opcode_reg_1199 == 7'd55) & (or_ln40_reg_1190 == 1'd0)))) begin
        ap_phi_mux_imm_phi_fu_211_p12 = immU_fu_643_p3;
    end else if (((opcode_reg_1199 == 7'd111) & (or_ln40_reg_1190 == 1'd0))) begin
        ap_phi_mux_imm_phi_fu_211_p12 = sext_ln81_fu_638_p1;
    end else if (((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0))) begin
        ap_phi_mux_imm_phi_fu_211_p12 = sext_ln73_fu_608_p1;
    end else if (((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0))) begin
        ap_phi_mux_imm_phi_fu_211_p12 = sext_ln77_fu_623_p1;
    end else if ((~(opcode_reg_1199 == 7'd19) & ~(opcode_reg_1199 == 7'd23) & ~(opcode_reg_1199 == 7'd55) & ~(opcode_reg_1199 == 7'd111) & ~(opcode_reg_1199 == 7'd99) & ~(opcode_reg_1199 == 7'd35) & ~(opcode_reg_1199 == 7'd103) & ~(opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0))) begin
        ap_phi_mux_imm_phi_fu_211_p12 = 32'd0;
    end else begin
        ap_phi_mux_imm_phi_fu_211_p12 = ap_phi_reg_pp0_iter0_imm_reg_208;
    end
end

always @ (*) begin
    if ((((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd0) & (trunc_ln56_1_reg_1207 == 6'd51)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd0) & (trunc_ln56_1_reg_1207 == 6'd51)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = res_31_fu_1104_p1;
    end else if ((((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd1) & (trunc_ln56_1_reg_1207 == 6'd51)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd1) & (trunc_ln56_1_reg_1207 == 6'd51)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = {{prod_ss_reg_1497[63:32]}};
    end else if ((((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd2) & (trunc_ln56_1_reg_1207 == 6'd51)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd2) & (trunc_ln56_1_reg_1207 == 6'd51)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = res_33_reg_1508;
    end else if ((((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd3) & (trunc_ln56_1_reg_1207 == 6'd51)) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (func3_reg_1223 == 3'd3) & (trunc_ln56_1_reg_1207 == 6'd51)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = res_34_reg_1503;
    end else if (((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd3)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd3) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd3))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd3) & (trunc_ln56_1_reg_1207 == 6'd19)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = zext_ln192_fu_1127_p1;
    end else if (((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd2)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd2) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd2))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd2) & (trunc_ln56_1_reg_1207 == 6'd19)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = zext_ln191_fu_1108_p1;
    end else if (((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd7)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd7))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd7) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd7))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd7))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd7) & (trunc_ln56_1_reg_1207 == 6'd19)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = res_28_fu_1112_p2;
    end else if (((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd6)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd6))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd6) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd6))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd6))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd6) & (trunc_ln56_1_reg_1207 == 6'd19)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = res_27_fu_1117_p2;
    end else if (((((((~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd4)) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd4))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd4) & (trunc_ln56_1_reg_1207 == 6'd19))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0) & (func3_reg_1223 == 3'd4))) | (~(trunc_ln56_1_reg_1207 == 6'd19) & ~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd4))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (or_ln14_reg_1362 == 1'd0) & (func3_reg_1223 == 3'd4) & (trunc_ln56_1_reg_1207 == 6'd19)))) begin
        ap_phi_mux_res_17_phi_fu_248_p44 = res_26_fu_1122_p2;
    end else begin
        ap_phi_mux_res_17_phi_fu_248_p44 = ap_phi_reg_pp0_iter1_res_17_reg_244;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln210_fu_806_p2 == 1'd0) & (icmp_ln203_reg_1350 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        mem_address0_local = zext_ln219_fu_812_p1;
    end else if (((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln233_fu_760_p2 == 1'd0) & (icmp_ln226_reg_1331 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        mem_address0_local = zext_ln242_fu_766_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mem_address0_local = zext_ln49_fu_393_p1;
    end else begin
        mem_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln233_fu_760_p2 == 1'd0) & (icmp_ln226_reg_1331 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln210_fu_806_p2 == 1'd0) & (icmp_ln203_reg_1350 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)))) begin
        mem_ce0_local = 1'b1;
    end else begin
        mem_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln233_fu_760_p2 == 1'd0) & (icmp_ln226_reg_1331 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        mem_we0_local = 1'b1;
    end else begin
        mem_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_address0_local = zext_ln297_fu_1152_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        reg_file_address0_local = zext_ln104_fu_547_p1;
    end else begin
        reg_file_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_file_ce0_local = 1'b1;
    end else begin
        reg_file_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        reg_file_ce1_local = 1'b1;
    end else begin
        reg_file_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((((((((((((((((((((((((((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd1)) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd0))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0))) | (~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (trunc_ln56_1_reg_1207 == 6'd19))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 
    == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 == 7'd51) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd1))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd0))) | ((opcode_reg_1199 == 7'd23) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0))) | ((opcode_reg_1199 == 7'd55) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0))) | ((opcode_reg_1199 == 7'd111) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 
    == 3'd7))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd6))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd5))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd4))) | ((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (or_ln233_reg_1411 == 1'd0) & (icmp_ln226_reg_1331 == 1'd1))) | ((opcode_reg_1199 == 7'd103) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0))) | ((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (or_ln210_reg_1415 == 1'd0) & (icmp_ln203_reg_1350 == 1'd1))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 
    == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (icmp_ln144_reg_1354 == 1'd0))) | (~(trunc_ln56_1_reg_1207 == 6'd51) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (trunc_ln56_1_reg_1207 == 6'd19))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) & (func3_reg_1223 == 3'd1))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln296_fu_1147_p2 == 1'd0) & (or_ln14_1_fu_1141_p2 == 1'd0) 
    & (func3_reg_1223 == 3'd0))))) begin
        reg_file_we0_local = 1'b1;
    end else begin
        reg_file_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((~(((ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln40_reg_1190 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_predicate_tran6to8_state6 == 1'b1))) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln40_reg_1190 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_predicate_tran6to8_state6 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign addr_1_fu_651_p0 = reg_file_q1;

assign addr_1_fu_651_p2 = ($signed(addr_1_fu_651_p0) + $signed(ap_phi_mux_imm_phi_fu_211_p12));

assign and_ln180_fu_1054_p2 = (icmp_ln180_1_reg_1376 & grp_fu_333_p2);

assign and_ln188_fu_876_p2 = (icmp_ln188_1_reg_1371 & grp_fu_333_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_144 = ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

always @ (*) begin
    ap_condition_181 = ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

always @ (*) begin
    ap_condition_315 = (~(opcode_reg_1199 == 7'd19) & ~(opcode_reg_1199 == 7'd23) & ~(opcode_reg_1199 == 7'd55) & ~(opcode_reg_1199 == 7'd111) & ~(opcode_reg_1199 == 7'd99) & ~(opcode_reg_1199 == 7'd35) & ~(opcode_reg_1199 == 7'd103) & ~(opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0));
end

always @ (*) begin
    ap_condition_372 = (((opcode_reg_1199 == 7'd23) & (or_ln40_reg_1190 == 1'd0)) | ((opcode_reg_1199 == 7'd55) & (or_ln40_reg_1190 == 1'd0)));
end

always @ (*) begin
    ap_condition_377 = ((((opcode_reg_1199 == 7'd103) & (or_ln40_reg_1190 == 1'd0)) | ((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0))) | ((opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_imm_reg_208 = 'bx;

assign ap_phi_reg_pp0_iter0_res_17_reg_244 = 32'd0;

always @ (*) begin
    ap_predicate_tran6to8_state6 = (((((((((~(opcode_reg_1199 == 7'd51) & ~(opcode_reg_1199 == 7'd19) & ~(opcode_reg_1199 == 7'd23) & ~(opcode_reg_1199 == 7'd55) & ~(opcode_reg_1199 == 7'd111) & ~(opcode_reg_1199 == 7'd99) & ~(opcode_reg_1199 == 7'd35) & ~(opcode_reg_1199 == 7'd103) & ~(opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0)) | (~(func3_reg_1223 == 3'd3) & ~(func3_reg_1223 == 3'd2) & ~(func3_reg_1223 == 3'd1) & ~(func3_reg_1223 == 3'd0) & ~(opcode_reg_1199 == 7'd23) & ~(opcode_reg_1199 == 7'd55) & ~(opcode_reg_1199 == 7'd111) & ~(opcode_reg_1199 == 7'd99) & ~(opcode_reg_1199 == 7'd35) & ~(opcode_reg_1199 == 7'd103) & ~(opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (trunc_ln56_1_reg_1207 == 6'd51))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd3))) | ((opcode_reg_1199 == 7'd99) & (or_ln40_reg_1190 == 1'd0) & (func3_reg_1223 == 3'd2))) | ((opcode_reg_1199 == 7'd35) & (or_ln40_reg_1190 == 1'd0) & (or_ln233_reg_1411 == 1'd1))) | ((opcode_reg_1199 == 7'd35) 
    & (or_ln40_reg_1190 == 1'd0) & (icmp_ln226_reg_1331 == 1'd0))) | ((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (or_ln210_reg_1415 == 1'd1))) | ((opcode_reg_1199 == 7'd3) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln203_reg_1350 == 1'd0))) | (~(func3_reg_1223 == 3'd3) & ~(func3_reg_1223 == 3'd2) & ~(func3_reg_1223 == 3'd1) & ~(func3_reg_1223 == 3'd0) & (opcode_reg_1199 == 7'd19) & (or_ln40_reg_1190 == 1'd0) & (icmp_ln144_reg_1354 == 1'd1) & (trunc_ln56_1_reg_1207 == 6'd51)));
end

assign bimm_fu_613_p6 = {{{{{tmp_5_reg_1259}, {tmp_4_reg_1254}}, {tmp_3_reg_1249}}, {tmp_2_reg_1244}}, {1'd0}};

assign grp_fu_298_p0 = zext_ln152_1_fu_830_p1;

assign grp_fu_298_p1 = grp_fu_298_p10;

assign grp_fu_298_p10 = $unsigned(src1_reg_1295);

assign grp_fu_302_p0 = zext_ln152_1_fu_830_p1;

assign grp_fu_302_p1 = sext_ln151_fu_817_p1;

assign grp_fu_306_p1 = sext_ln151_fu_817_p1;

assign grp_fu_310_p2 = ((func3_reg_1223 == 3'd2) ? 1'b1 : 1'b0);

assign grp_fu_315_p2 = ((func7_reg_1232 == 7'd32) ? 1'b1 : 1'b0);

assign grp_fu_320_p2 = ((src1_reg_1295 < src2_reg_1319) ? 1'b1 : 1'b0);

assign grp_fu_324_p2 = (($signed(src1_reg_1295) < $signed(src2_reg_1319)) ? 1'b1 : 1'b0);

assign grp_fu_328_p2 = ($signed(src1_reg_1295) + $signed(imm_reg_208));

assign grp_fu_333_p2 = ((opcode_reg_1199 == 7'd51) ? 1'b1 : 1'b0);

assign grp_fu_338_p2 = (imm_reg_208 + pc_1_reg_1184);

assign icmp_ln144_fu_681_p2 = ((func7_reg_1232 == 7'd1) ? 1'b1 : 1'b0);

assign icmp_ln14_1_fu_702_p2 = ((func3_reg_1223 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln14_2_fu_1131_p2 = ((opcode_reg_1199 == 7'd99) ? 1'b1 : 1'b0);

assign icmp_ln14_3_fu_1136_p2 = ((opcode_reg_1199 == 7'd35) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_697_p2 = ((func3_reg_1223 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln173_fu_860_p2 = ((opcode_reg_1199 == 7'd19) ? 1'b1 : 1'b0);

assign icmp_ln210_fu_774_p2 = ((trunc_ln208_fu_770_p1 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_800_p2 = ((tmp_9_fu_790_p4 != 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln233_fu_750_p2 = ((trunc_ln231_reg_1335 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_755_p2 = ((tmp_10_reg_1345 != 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln296_fu_1147_p2 = ((rd_reg_1211 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_355_p2 = ((trunc_ln27_fu_351_p1 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_371_p2 = ((tmp_1_fu_361_p4 != 17'd0) ? 1'b1 : 1'b0);

assign immU_fu_643_p3 = {{tmp_reg_1280}, {12'd0}};

assign jimm_fu_628_p6 = {{{{{tmp_5_reg_1259}, {tmp_6_reg_1275}}, {tmp_8_reg_1270}}, {tmp_s_reg_1265}}, {1'd0}};

assign lshr_ln1_fu_780_p4 = {{grp_fu_328_p2[14:2]}};

assign lshr_ln_fu_383_p4 = {{pc_fu_142[14:2]}};

assign mem_address0 = mem_address0_local;

assign mem_ce0 = mem_ce0_local;

assign mem_d0 = src2_reg_1319;

assign mem_we0 = mem_we0_local;

assign next_pc_2_fu_924_p3 = {{tmp_7_fu_914_p4}, {1'd0}};

assign next_pc_3_fu_942_p3 = ((ap_phi_reg_pp0_iter0_take_4_reg_227[0:0] == 1'b1) ? grp_fu_338_p2 : next_pc_4_fu_904_p2);

assign next_pc_4_fu_904_p2 = (pc_1_reg_1184 + 32'd4);

assign op2_1_fu_865_p3 = ((icmp_ln173_fu_860_p2[0:0] == 1'b1) ? imm_reg_208 : src2_reg_1319);

assign opcode_fu_398_p1 = mem_q0[6:0];

assign or_ln14_1_fu_1141_p2 = (icmp_ln14_3_fu_1136_p2 | icmp_ln14_2_fu_1131_p2);

assign or_ln14_fu_707_p2 = (icmp_ln14_fu_697_p2 | icmp_ln14_1_fu_702_p2);

assign or_ln210_fu_806_p2 = (icmp_ln214_fu_800_p2 | icmp_ln210_fu_774_p2);

assign or_ln233_fu_760_p2 = (icmp_ln237_fu_755_p2 | icmp_ln233_fu_750_p2);

assign or_ln40_fu_377_p2 = (icmp_ln44_fu_371_p2 | icmp_ln40_fu_355_p2);

assign reg_file_address0 = reg_file_address0_local;

assign reg_file_address1 = zext_ln103_fu_542_p1;

assign reg_file_ce0 = reg_file_ce0_local;

assign reg_file_ce1 = reg_file_ce1_local;

assign reg_file_d0 = ap_phi_mux_res_17_phi_fu_248_p44;

assign reg_file_we0 = reg_file_we0_local;

assign res_12_fu_855_p2 = src1_reg_1295 << zext_ln127_fu_835_p1;

assign res_13_fu_838_p2 = $signed(src1_reg_1295) >>> zext_ln127_fu_835_p1;

assign res_14_fu_843_p2 = src1_reg_1295 >> zext_ln127_fu_835_p1;

assign res_15_fu_848_p3 = ((icmp_ln134_reg_1366[0:0] == 1'b1) ? res_13_fu_838_p2 : res_14_fu_843_p2);

assign res_16_fu_1080_p2 = ((src1_reg_1295 < op2_1_reg_1456) ? 1'b1 : 1'b0);

assign res_23_fu_1059_p2 = ($signed(src1_reg_1295) - $signed(op2_1_reg_1456));

assign res_24_fu_1063_p2 = ($signed(src1_reg_1295) + $signed(op2_1_reg_1456));

assign res_25_fu_1067_p3 = ((and_ln180_fu_1054_p2[0:0] == 1'b1) ? res_23_fu_1059_p2 : res_24_fu_1063_p2);

assign res_26_fu_1122_p2 = (src1_reg_1295 ^ op2_1_reg_1456);

assign res_27_fu_1117_p2 = (src1_reg_1295 | op2_1_reg_1456);

assign res_28_fu_1112_p2 = (src1_reg_1295 & op2_1_reg_1456);

assign res_29_fu_899_p2 = src1_reg_1295 << zext_ln186_fu_895_p1;

assign res_30_fu_1015_p2 = (($signed(src1_reg_1295) < $signed(op2_1_reg_1456)) ? 1'b1 : 1'b0);

assign res_31_fu_1104_p1 = prod_ss_reg_1497[31:0];

assign res_35_fu_890_p2 = $signed(src1_reg_1295) >>> zext_ln188_fu_881_p1;

assign res_36_fu_885_p2 = src1_reg_1295 >> zext_ln188_fu_881_p1;

assign rs1_fu_414_p3 = {{mem_q0[19:15]}};

assign rs2_fu_422_p3 = {{mem_q0[24:20]}};

assign sext_ln151_fu_817_p1 = src1_reg_1295;

assign sext_ln70_fu_598_p1 = $signed(immI_reg_1239);

assign sext_ln73_fu_608_p1 = $signed(simm_fu_602_p3);

assign sext_ln77_fu_623_p1 = $signed(bimm_fu_613_p6);

assign sext_ln81_fu_638_p1 = $signed(jimm_fu_628_p6);

assign simm_fu_602_p3 = {{func7_reg_1232}, {rd_reg_1211}};

assign take_1_fu_742_p2 = ((src1_reg_1295 != src2_reg_1319) ? 1'b1 : 1'b0);

assign take_3_fu_736_p2 = (grp_fu_324_p2 ^ 1'd1);

assign take_6_fu_730_p2 = (grp_fu_320_p2 ^ 1'd1);

assign take_fu_746_p2 = ((src1_reg_1295 == src2_reg_1319) ? 1'b1 : 1'b0);

assign tmp_1_fu_361_p4 = {{pc_fu_142[31:15]}};

assign tmp_7_fu_914_p4 = {{grp_fu_328_p2[31:1]}};

assign tmp_9_fu_790_p4 = {{grp_fu_328_p2[31:15]}};

assign trunc_ln173_fu_872_p1 = op2_1_fu_865_p3[4:0];

assign trunc_ln208_fu_770_p1 = grp_fu_328_p2[1:0];

assign trunc_ln231_fu_657_p1 = addr_1_fu_651_p2[1:0];

assign trunc_ln27_fu_351_p1 = pc_fu_142[1:0];

assign trunc_ln56_1_fu_402_p1 = mem_q0[5:0];

assign zext_ln103_fu_542_p1 = rs1_fu_414_p3;

assign zext_ln104_fu_547_p1 = rs2_fu_422_p3;

assign zext_ln127_fu_835_p1 = rs2_reg_1218;

assign zext_ln152_1_fu_830_p1 = $unsigned(src2_reg_1319);

assign zext_ln186_fu_895_p1 = trunc_ln173_fu_872_p1;

assign zext_ln188_fu_881_p1 = trunc_ln173_fu_872_p1;

assign zext_ln191_fu_1108_p1 = res_30_reg_1513;

assign zext_ln192_fu_1127_p1 = res_16_reg_1523;

assign zext_ln219_fu_812_p1 = lshr_ln1_fu_780_p4;

assign zext_ln242_fu_766_p1 = lshr_ln2_reg_1340;

assign zext_ln297_fu_1152_p1 = rd_reg_1211;

assign zext_ln49_fu_393_p1 = lshr_ln_fu_383_p4;

endmodule //cpu_cpu_Pipeline_PROGRAM_LOOP
