

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "3"],
		"CDFG" : "cpu",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "imem", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_cpu_Pipeline_PROGRAM_LOOP_fu_189", "Port" : "imem", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "dmem", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_cpu_Pipeline_PROGRAM_LOOP_fu_189", "Port" : "dmem", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "pstrb", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_154", "Parent" : "0", "Child" : ["2"],
		"CDFG" : "cpu_Pipeline_VITIS_LOOP_22_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "reg_file_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "reg_file_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_22_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_154.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cpu_Pipeline_PROGRAM_LOOP_fu_189", "Parent" : "0", "Child" : ["4", "5", "6", "7", "8"],
		"CDFG" : "cpu_Pipeline_PROGRAM_LOOP",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "reg_file_30_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_29_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_28_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_27_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_26_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_25_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "reg_file_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "imem", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "dmem", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "PROGRAM_LOOP", "PipelineType" : "pipeline",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "PreState" : ["ap_ST_fsm_state1"], "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "PostState" : ["ap_ST_fsm_state5", "ap_ST_fsm_state6"]}}]},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cpu_Pipeline_PROGRAM_LOOP_fu_189.mul_32ns_32ns_64_2_1_U32", "Parent" : "3"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cpu_Pipeline_PROGRAM_LOOP_fu_189.mul_32ns_32s_64_2_1_U33", "Parent" : "3"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cpu_Pipeline_PROGRAM_LOOP_fu_189.mul_32s_32s_64_2_1_U34", "Parent" : "3"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cpu_Pipeline_PROGRAM_LOOP_fu_189.sparsemux_65_5_32_1_1_U35", "Parent" : "3"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cpu_Pipeline_PROGRAM_LOOP_fu_189.sparsemux_65_5_32_1_1_U36", "Parent" : "3"}]}
