-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cpu_cpu_Pipeline_PROGRAM_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    reg_file_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    reg_file_ce0 : OUT STD_LOGIC;
    reg_file_we0 : OUT STD_LOGIC;
    reg_file_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    reg_file_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    reg_file_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    reg_file_ce1 : OUT STD_LOGIC;
    reg_file_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mem_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    mem_ce0 : OUT STD_LOGIC;
    mem_we0 : OUT STD_LOGIC;
    mem_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of cpu_cpu_Pipeline_PROGRAM_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv7_67 : STD_LOGIC_VECTOR (6 downto 0) := "1100111";
    constant ap_const_lv7_23 : STD_LOGIC_VECTOR (6 downto 0) := "0100011";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv7_6F : STD_LOGIC_VECTOR (6 downto 0) := "1101111";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv7_17 : STD_LOGIC_VECTOR (6 downto 0) := "0010111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv7_33 : STD_LOGIC_VECTOR (6 downto 0) := "0110011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv7_20 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal pc_1_reg_1203 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln43_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_reg_1209 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal opcode_fu_435_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal opcode_reg_1218 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal trunc_ln59_1_fu_439_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln59_1_reg_1226 : STD_LOGIC_VECTOR (5 downto 0);
    signal rd_reg_1230 : STD_LOGIC_VECTOR (4 downto 0);
    signal rs2_fu_459_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal rs2_reg_1237 : STD_LOGIC_VECTOR (4 downto 0);
    signal func3_fu_467_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal func3_reg_1242 : STD_LOGIC_VECTOR (2 downto 0);
    signal func7_fu_476_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal func7_reg_1246 : STD_LOGIC_VECTOR (6 downto 0);
    signal immI_reg_1252 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_reg_1257 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_reg_1262 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_reg_1267 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1272 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1278 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_8_reg_1283 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1288 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_1293 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln229_reg_1308 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln206_reg_1312 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln147_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln147_reg_1316 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_1_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_1_reg_1320 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln16_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln16_reg_1324 : STD_LOGIC_VECTOR (0 downto 0);
    signal src1_reg_1328 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal next_pc_4_fu_743_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln236_fu_832_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_reg_1341 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln213_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln213_reg_1345 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln154_fu_874_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln155_1_fu_890_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal res_15_fu_931_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_15_reg_1376 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_12_fu_944_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_12_reg_1381 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_1_fu_960_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_1_reg_1386 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_30_fu_972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_30_reg_1393 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln191_fu_983_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln191_reg_1398 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_36_fu_993_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_36_reg_1402 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_35_fu_1004_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_35_reg_1407 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_29_fu_1019_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_29_reg_1412 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln183_reg_1417 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln183_1_reg_1422 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_23_fu_1045_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_23_reg_1427 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_24_fu_1051_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_24_reg_1432 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_16_fu_1062_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_16_reg_1437 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_325_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_reg_1442 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_predicate_tran5to6_state4 : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_imm_phi_fu_214_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_imm_reg_211 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln80_fu_715_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln76_fu_700_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln84_fu_730_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal immU_fu_735_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln73_fu_690_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_take_4_phi_fu_233_p12 : STD_LOGIC_VECTOR (0 downto 0);
    signal take_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_take_4_reg_230 : STD_LOGIC_VECTOR (0 downto 0);
    signal take_1_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal take_3_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal take_6_fu_781_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_res_17_phi_fu_251_p44 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_res_17_reg_247 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_res_17_reg_247 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_25_fu_1139_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_26_fu_1130_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_27_fu_1125_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_28_fu_1120_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln194_fu_1116_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln195_fu_1146_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_31_fu_1111_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln52_fu_430_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln106_fu_580_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln107_fu_585_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln245_fu_838_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln222_fu_864_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln300_fu_1171_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln16_1_fu_1160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln299_fu_1166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pc_fu_144 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal next_pc_2_fu_763_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal next_pc_3_fu_809_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mem_ce0_local : STD_LOGIC;
    signal mem_address0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal mem_we0_local : STD_LOGIC;
    signal reg_file_ce1_local : STD_LOGIC;
    signal reg_file_ce0_local : STD_LOGIC;
    signal reg_file_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal reg_file_we0_local : STD_LOGIC;
    signal grp_fu_302_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_302_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_306_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_306_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_310_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_319_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_330_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_330_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_337_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_337_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_319_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_354_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln29_fu_388_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_398_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln43_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln_fu_420_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal rs1_fu_451_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln16_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal simm_fu_694_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal bimm_fu_705_p6 : STD_LOGIC_VECTOR (12 downto 0);
    signal jimm_fu_720_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_7_fu_753_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal take_1_fu_795_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal take_1_fu_795_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal take_fu_802_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal take_fu_802_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln234_fu_822_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln236_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_344_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln211_fu_848_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln213_fu_852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln154_fu_874_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln154_1_fu_880_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln155_fu_885_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln155_1_fu_890_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_13_fu_919_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln130_fu_916_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_14_fu_925_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_13_fu_919_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_14_fu_925_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_12_fu_944_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln176_fu_955_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal op2_1_fu_960_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_30_fu_972_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln176_fu_968_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal res_36_fu_993_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln191_fu_989_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_35_fu_1004_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_29_fu_1019_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln189_fu_1015_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_23_fu_1045_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_24_fu_1051_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_16_fu_1062_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_302_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_306_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_310_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln183_fu_1135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_3_fu_1155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_2_fu_1150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_exit_tran_regpp0 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_302_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component cpu_mul_32ns_32ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component cpu_mul_32ns_32s_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component cpu_mul_32s_32s_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    mul_32ns_32ns_64_2_1_U2 : component cpu_mul_32ns_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_302_p0,
        din1 => grp_fu_302_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_302_p2);

    mul_32ns_32s_64_2_1_U3 : component cpu_mul_32ns_32s_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_306_p0,
        din1 => grp_fu_306_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_306_p2);

    mul_32s_32s_64_2_1_U4 : component cpu_mul_32s_32s_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln154_1_fu_880_p0,
        din1 => grp_fu_310_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_310_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_exit_tran_regpp0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then
                if ((or_ln43_reg_1209 = ap_const_lv1_1)) then 
                    ap_exit_tran_regpp0(0) <= '1';
                elsif ((ap_predicate_tran5to6_state4 = ap_const_boolean_1)) then 
                    ap_exit_tran_regpp0(0) <= '0';
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_res_17_reg_247_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((((((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7)) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))))) then 
                ap_phi_reg_pp0_iter1_res_17_reg_247 <= ap_const_lv32_0;
            elsif (((opcode_reg_1218 = ap_const_lv7_37) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter1_res_17_reg_247 <= ap_phi_mux_imm_phi_fu_214_p12;
            elsif ((((opcode_reg_1218 = ap_const_lv7_6F) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((opcode_reg_1218 = ap_const_lv7_67) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)))) then 
                ap_phi_reg_pp0_iter1_res_17_reg_247 <= next_pc_4_fu_743_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter1_res_17_reg_247 <= ap_phi_reg_pp0_iter0_res_17_reg_247;
            end if; 
        end if;
    end process;

    pc_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                pc_fu_144 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((((((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7)) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))))) then 
                pc_fu_144 <= next_pc_3_fu_809_p3;
            elsif (((opcode_reg_1218 = ap_const_lv7_6F) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
                pc_fu_144 <= grp_fu_325_p2;
            elsif (((opcode_reg_1218 = ap_const_lv7_67) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
                pc_fu_144 <= next_pc_2_fu_763_p3;
            elsif ((((opcode_reg_1218 = ap_const_lv7_17) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((opcode_reg_1218 = ap_const_lv7_37) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln236_fu_832_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln229_reg_1308 = ap_const_lv1_1)) or ((opcode_reg_1218 = ap_const_lv7_3) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln213_fu_858_p2 = ap_const_lv1_0) and (icmp_ln206_reg_1312 
    = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_fu_983_p2) and (func3_reg_1242 = ap_const_lv3_5)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_fu_983_p2) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_fu_983_p2) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or (not((trunc_ln59_1_reg_1226 
    = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_fu_983_p2) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_fu_983_p2) and (func3_reg_1242 = ap_const_lv3_5))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_fu_983_p2) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) 
    and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_fu_983_p2) and (func3_reg_1242 = ap_const_lv3_5)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_fu_983_p2) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_fu_983_p2) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_fu_983_p2) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) 
    and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_fu_983_p2) and (func3_reg_1242 = ap_const_lv3_5))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_fu_983_p2) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_0)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_0)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) 
    and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_1)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_2)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = 
    ap_const_lv3_2)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_3)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_3)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and 
    (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3)))) or ((ap_const_boolean_0 
    = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) 
    and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 
    = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) 
    and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and 
    (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 
    = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) 
    and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and ((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 
    = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_1) and (icmp_ln16_1_reg_1320 = ap_const_lv1_0)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_1) and (icmp_ln16_1_reg_1320 = ap_const_lv1_0)))) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and 
    (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_1) and (icmp_ln16_1_reg_1320 = ap_const_lv1_1)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_1) and (icmp_ln16_1_reg_1320 = ap_const_lv1_1)))))) then 
                pc_fu_144 <= next_pc_4_fu_743_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                and_ln191_reg_1398 <= and_ln191_fu_983_p2;
                op2_1_reg_1386 <= op2_1_fu_960_p3;
                or_ln213_reg_1345 <= or_ln213_fu_858_p2;
                or_ln236_reg_1341 <= or_ln236_fu_832_p2;
                res_12_reg_1381 <= res_12_fu_944_p2;
                res_15_reg_1376 <= res_15_fu_931_p3;
                res_16_reg_1437 <= res_16_fu_1062_p2;
                res_23_reg_1427 <= res_23_fu_1045_p2;
                res_24_reg_1432 <= res_24_fu_1051_p2;
                res_29_reg_1412 <= res_29_fu_1019_p2;
                res_30_reg_1393 <= res_30_fu_972_p2;
                res_35_reg_1407 <= res_35_fu_1004_p2;
                res_36_reg_1402 <= res_36_fu_993_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                func3_reg_1242 <= mem_q0(14 downto 12);
                func7_reg_1246 <= mem_q0(31 downto 25);
                icmp_ln147_reg_1316 <= icmp_ln147_fu_636_p2;
                icmp_ln16_1_reg_1320 <= icmp_ln16_1_fu_660_p2;
                immI_reg_1252 <= mem_q0(31 downto 20);
                opcode_reg_1218 <= opcode_fu_435_p1;
                or_ln16_reg_1324 <= or_ln16_fu_666_p2;
                rd_reg_1230 <= mem_q0(11 downto 7);
                rs2_reg_1237 <= mem_q0(24 downto 20);
                tmp_2_reg_1257 <= mem_q0(11 downto 8);
                tmp_3_reg_1262 <= mem_q0(30 downto 25);
                tmp_4_reg_1267 <= mem_q0(7 downto 7);
                tmp_5_reg_1272 <= mem_q0(31 downto 31);
                tmp_6_reg_1288 <= mem_q0(19 downto 12);
                tmp_8_reg_1283 <= mem_q0(20 downto 20);
                tmp_reg_1293 <= mem_q0(31 downto 12);
                tmp_s_reg_1278 <= mem_q0(30 downto 21);
                trunc_ln59_1_reg_1226 <= trunc_ln59_1_fu_439_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then
                icmp_ln183_1_reg_1422 <= grp_fu_370_p2;
                icmp_ln183_reg_1417 <= grp_fu_375_p2;
                res_reg_1442 <= grp_fu_325_p2;
                src1_reg_1328 <= reg_file_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then
                icmp_ln206_reg_1312 <= grp_fu_314_p2;
                icmp_ln229_reg_1308 <= grp_fu_314_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                or_ln43_reg_1209 <= or_ln43_fu_414_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                pc_1_reg_1203 <= pc_fu_144;
            end if;
        end if;
    end process;
    ap_exit_tran_regpp0(1) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_exit_tran_regpp0, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_exit_tran_regpp0 = ap_const_lv2_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_exit_tran_regpp0 = ap_const_lv2_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    and_ln183_fu_1135_p2 <= (icmp_ln183_reg_1417 and icmp_ln183_1_reg_1422);
    and_ln191_fu_983_p2 <= (grp_fu_375_p2 and grp_fu_370_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_flush_enable_assign_proc : process(or_ln43_reg_1209, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_predicate_tran5to6_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and ((or_ln43_reg_1209 = ap_const_lv1_1) or (ap_predicate_tran5to6_state4 = ap_const_boolean_1)))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_imm_phi_fu_214_p12_assign_proc : process(or_ln43_reg_1209, opcode_reg_1218, ap_phi_reg_pp0_iter0_imm_reg_211, sext_ln80_fu_715_p1, sext_ln76_fu_700_p1, sext_ln84_fu_730_p1, immU_fu_735_p3, sext_ln73_fu_690_p1)
    begin
        if (((((opcode_reg_1218 = ap_const_lv7_67) and (or_ln43_reg_1209 = ap_const_lv1_0)) or ((opcode_reg_1218 = ap_const_lv7_3) and (or_ln43_reg_1209 = ap_const_lv1_0))) or ((opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0)))) then 
            ap_phi_mux_imm_phi_fu_214_p12 <= sext_ln73_fu_690_p1;
        elsif ((((opcode_reg_1218 = ap_const_lv7_17) and (or_ln43_reg_1209 = ap_const_lv1_0)) or ((opcode_reg_1218 = ap_const_lv7_37) and (or_ln43_reg_1209 = ap_const_lv1_0)))) then 
            ap_phi_mux_imm_phi_fu_214_p12 <= immU_fu_735_p3;
        elsif (((opcode_reg_1218 = ap_const_lv7_6F) and (or_ln43_reg_1209 = ap_const_lv1_0))) then 
            ap_phi_mux_imm_phi_fu_214_p12 <= sext_ln84_fu_730_p1;
        elsif (((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0))) then 
            ap_phi_mux_imm_phi_fu_214_p12 <= sext_ln76_fu_700_p1;
        elsif (((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0))) then 
            ap_phi_mux_imm_phi_fu_214_p12 <= sext_ln80_fu_715_p1;
        elsif ((not((opcode_reg_1218 = ap_const_lv7_13)) and not((opcode_reg_1218 = ap_const_lv7_17)) and not((opcode_reg_1218 = ap_const_lv7_37)) and not((opcode_reg_1218 = ap_const_lv7_6F)) and not((opcode_reg_1218 = ap_const_lv7_63)) and not((opcode_reg_1218 = ap_const_lv7_23)) and not((opcode_reg_1218 = ap_const_lv7_67)) and not((opcode_reg_1218 = ap_const_lv7_3)) and (or_ln43_reg_1209 = ap_const_lv1_0))) then 
            ap_phi_mux_imm_phi_fu_214_p12 <= ap_const_lv32_0;
        else 
            ap_phi_mux_imm_phi_fu_214_p12 <= ap_phi_reg_pp0_iter0_imm_reg_211;
        end if; 
    end process;


    ap_phi_mux_res_17_phi_fu_251_p44_assign_proc : process(mem_q0, or_ln43_reg_1209, opcode_reg_1218, trunc_ln59_1_reg_1226, func3_reg_1242, icmp_ln229_reg_1308, icmp_ln206_reg_1312, icmp_ln147_reg_1316, icmp_ln16_1_reg_1320, or_ln16_reg_1324, or_ln236_reg_1341, or_ln213_reg_1345, res_15_reg_1376, res_12_reg_1381, and_ln191_reg_1398, res_36_reg_1402, res_35_reg_1407, res_29_reg_1412, res_reg_1442, ap_phi_reg_pp0_iter1_res_17_reg_247, res_25_fu_1139_p3, res_26_fu_1130_p2, res_27_fu_1125_p2, res_28_fu_1120_p2, zext_ln194_fu_1116_p1, zext_ln195_fu_1146_p1, res_31_fu_1111_p1, grp_fu_302_p2, grp_fu_306_p2, grp_fu_310_p2)
    begin
        if ((((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_0)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_0)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_31_fu_1111_p1;
        elsif ((((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_1)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_1)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= grp_fu_310_p2(63 downto 32);
        elsif ((((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_2)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_2)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= grp_fu_306_p2(63 downto 32);
        elsif ((((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_3)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1) and (func3_reg_1242 = ap_const_lv3_3)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= grp_fu_302_p2(63 downto 32);
        elsif (((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln236_reg_1341 = ap_const_lv1_0) and (icmp_ln229_reg_1308 = ap_const_lv1_1))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= ap_const_lv32_0;
        elsif (((opcode_reg_1218 = ap_const_lv7_3) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln213_reg_1345 = ap_const_lv1_0) and (icmp_ln206_reg_1312 = ap_const_lv1_1))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= mem_q0;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_reg_1398) and (func3_reg_1242 = ap_const_lv3_5)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_reg_1398) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_reg_1398) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_reg_1398) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) 
    or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_reg_1398) and (func3_reg_1242 = ap_const_lv3_5))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln191_reg_1398) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_36_reg_1402;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_reg_1398) and (func3_reg_1242 = ap_const_lv3_5)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_reg_1398) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_reg_1398) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_reg_1398) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) 
    or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_reg_1398) and (func3_reg_1242 = ap_const_lv3_5))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln191_reg_1398) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_35_reg_1407;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) 
    and (func3_reg_1242 = ap_const_lv3_3))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= zext_ln195_fu_1146_p1;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) 
    and (func3_reg_1242 = ap_const_lv3_2))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= zext_ln194_fu_1116_p1;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) 
    and (func3_reg_1242 = ap_const_lv3_1))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_29_reg_1412;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) 
    and (func3_reg_1242 = ap_const_lv3_7))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_28_fu_1120_p2;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) 
    and (func3_reg_1242 = ap_const_lv3_6))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_27_fu_1125_p2;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) 
    and (func3_reg_1242 = ap_const_lv3_4))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_26_fu_1130_p2;
        elsif (((((((not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0)) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_13)) and not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) 
    and (func3_reg_1242 = ap_const_lv3_0))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_25_fu_1139_p3;
        elsif ((((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_1) and (icmp_ln16_1_reg_1320 = ap_const_lv1_0)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_1) and (icmp_ln16_1_reg_1320 = ap_const_lv1_0)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_15_reg_1376;
        elsif ((((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_1) and (icmp_ln16_1_reg_1320 = ap_const_lv1_1)) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln16_reg_1324 = ap_const_lv1_1) and (icmp_ln16_1_reg_1320 = ap_const_lv1_1)))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_12_reg_1381;
        elsif (((opcode_reg_1218 = ap_const_lv7_17) and (or_ln43_reg_1209 = ap_const_lv1_0))) then 
            ap_phi_mux_res_17_phi_fu_251_p44 <= res_reg_1442;
        else 
            ap_phi_mux_res_17_phi_fu_251_p44 <= ap_phi_reg_pp0_iter1_res_17_reg_247;
        end if; 
    end process;


    ap_phi_mux_take_4_phi_fu_233_p12_assign_proc : process(or_ln43_reg_1209, opcode_reg_1218, func3_reg_1242, take_fu_802_p2, ap_phi_reg_pp0_iter0_take_4_reg_230, take_1_fu_795_p2, grp_fu_337_p2, take_3_fu_788_p2, grp_fu_330_p2, take_6_fu_781_p2)
    begin
        if (((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0))) then
            if ((func3_reg_1242 = ap_const_lv3_7)) then 
                ap_phi_mux_take_4_phi_fu_233_p12 <= take_6_fu_781_p2;
            elsif ((func3_reg_1242 = ap_const_lv3_6)) then 
                ap_phi_mux_take_4_phi_fu_233_p12 <= grp_fu_330_p2;
            elsif ((func3_reg_1242 = ap_const_lv3_5)) then 
                ap_phi_mux_take_4_phi_fu_233_p12 <= take_3_fu_788_p2;
            elsif ((func3_reg_1242 = ap_const_lv3_4)) then 
                ap_phi_mux_take_4_phi_fu_233_p12 <= grp_fu_337_p2;
            elsif ((func3_reg_1242 = ap_const_lv3_1)) then 
                ap_phi_mux_take_4_phi_fu_233_p12 <= take_1_fu_795_p2;
            elsif ((func3_reg_1242 = ap_const_lv3_0)) then 
                ap_phi_mux_take_4_phi_fu_233_p12 <= take_fu_802_p2;
            else 
                ap_phi_mux_take_4_phi_fu_233_p12 <= ap_phi_reg_pp0_iter0_take_4_reg_230;
            end if;
        else 
            ap_phi_mux_take_4_phi_fu_233_p12 <= ap_phi_reg_pp0_iter0_take_4_reg_230;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_imm_reg_211 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_res_17_reg_247 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_take_4_reg_230 <= "X";

    ap_predicate_tran5to6_state4_assign_proc : process(or_ln43_reg_1209, opcode_reg_1218, trunc_ln59_1_reg_1226, func3_reg_1242, icmp_ln229_reg_1308, icmp_ln206_reg_1312, icmp_ln147_reg_1316, or_ln236_fu_832_p2, or_ln213_fu_858_p2)
    begin
                ap_predicate_tran5to6_state4 <= (((((((((not((opcode_reg_1218 = ap_const_lv7_33)) and not((opcode_reg_1218 = ap_const_lv7_13)) and not((opcode_reg_1218 = ap_const_lv7_17)) and not((opcode_reg_1218 = ap_const_lv7_37)) and not((opcode_reg_1218 = ap_const_lv7_6F)) and not((opcode_reg_1218 = ap_const_lv7_63)) and not((opcode_reg_1218 = ap_const_lv7_23)) and not((opcode_reg_1218 = ap_const_lv7_67)) and not((opcode_reg_1218 = ap_const_lv7_3)) and (or_ln43_reg_1209 = ap_const_lv1_0)) or (not((func3_reg_1242 = ap_const_lv3_3)) and not((func3_reg_1242 = ap_const_lv3_2)) and not((func3_reg_1242 = ap_const_lv3_1)) and not((func3_reg_1242 = ap_const_lv3_0)) and not((opcode_reg_1218 = ap_const_lv7_17)) and not((opcode_reg_1218 = ap_const_lv7_37)) and not((opcode_reg_1218 = ap_const_lv7_6F)) and not((opcode_reg_1218 = ap_const_lv7_63)) and not((opcode_reg_1218 = ap_const_lv7_23)) and not((opcode_reg_1218 = ap_const_lv7_67)) and not((opcode_reg_1218 = ap_const_lv7_3)) and (trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and 
    (icmp_ln147_reg_1316 = ap_const_lv1_1))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or ((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln236_fu_832_p2 = ap_const_lv1_1))) or ((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln229_reg_1308 = ap_const_lv1_0))) or ((opcode_reg_1218 = ap_const_lv7_3) and (or_ln43_reg_1209 = ap_const_lv1_0) and (or_ln213_fu_858_p2 = ap_const_lv1_1))) or ((opcode_reg_1218 = ap_const_lv7_3) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln206_reg_1312 = ap_const_lv1_0))) or (not((func3_reg_1242 = ap_const_lv3_3)) and not((func3_reg_1242 = ap_const_lv3_2)) and not((func3_reg_1242 = ap_const_lv3_1)) and not((func3_reg_1242 = ap_const_lv3_0)) and (trunc_ln59_1_reg_1226 = ap_const_lv6_33) and (opcode_reg_1218 = ap_const_lv7_13) 
    and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_1)));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bimm_fu_705_p6 <= ((((tmp_5_reg_1272 & tmp_4_reg_1267) & tmp_3_reg_1262) & tmp_2_reg_1257) & ap_const_lv1_0);
    func3_fu_467_p3 <= mem_q0(14 downto 12);
    func7_fu_476_p3 <= mem_q0(31 downto 25);
    grp_fu_302_p0 <= zext_ln155_1_fu_890_p1(32 - 1 downto 0);
    grp_fu_302_p1 <= grp_fu_302_p10(32 - 1 downto 0);
    grp_fu_302_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln155_fu_885_p0),64));
    grp_fu_306_p0 <= zext_ln155_1_fu_890_p1(32 - 1 downto 0);
    grp_fu_306_p1 <= sext_ln154_fu_874_p1(32 - 1 downto 0);
    grp_fu_310_p1 <= sext_ln154_fu_874_p1(32 - 1 downto 0);
    grp_fu_314_p2 <= "1" when (func3_fu_467_p3 = ap_const_lv3_2) else "0";
    grp_fu_319_p0 <= reg_file_q1;
    grp_fu_319_p2 <= std_logic_vector(signed(grp_fu_319_p0) + signed(ap_phi_mux_imm_phi_fu_214_p12));
    grp_fu_325_p2 <= std_logic_vector(unsigned(ap_phi_mux_imm_phi_fu_214_p12) + unsigned(pc_1_reg_1203));
    grp_fu_330_p0 <= reg_file_q1;
    grp_fu_330_p1 <= reg_file_q0;
    grp_fu_330_p2 <= "1" when (unsigned(grp_fu_330_p0) < unsigned(grp_fu_330_p1)) else "0";
    grp_fu_337_p0 <= reg_file_q1;
    grp_fu_337_p1 <= reg_file_q0;
    grp_fu_337_p2 <= "1" when (signed(grp_fu_337_p0) < signed(grp_fu_337_p1)) else "0";
    grp_fu_344_p4 <= grp_fu_319_p2(17 downto 2);
    grp_fu_354_p4 <= grp_fu_319_p2(31 downto 18);
    grp_fu_364_p2 <= "0" when (grp_fu_354_p4 = ap_const_lv14_0) else "1";
    grp_fu_370_p2 <= "1" when (func7_reg_1246 = ap_const_lv7_20) else "0";
    grp_fu_375_p2 <= "1" when (opcode_reg_1218 = ap_const_lv7_33) else "0";
    icmp_ln147_fu_636_p2 <= "1" when (func7_fu_476_p3 = ap_const_lv7_1) else "0";
    icmp_ln16_1_fu_660_p2 <= "1" when (func3_fu_467_p3 = ap_const_lv3_1) else "0";
    icmp_ln16_2_fu_1150_p2 <= "1" when (opcode_reg_1218 = ap_const_lv7_63) else "0";
    icmp_ln16_3_fu_1155_p2 <= "1" when (opcode_reg_1218 = ap_const_lv7_23) else "0";
    icmp_ln16_fu_654_p2 <= "1" when (func3_fu_467_p3 = ap_const_lv3_5) else "0";
    icmp_ln176_fu_955_p2 <= "1" when (opcode_reg_1218 = ap_const_lv7_13) else "0";
    icmp_ln213_fu_852_p2 <= "0" when (trunc_ln211_fu_848_p1 = ap_const_lv2_0) else "1";
    icmp_ln236_fu_826_p2 <= "0" when (trunc_ln234_fu_822_p1 = ap_const_lv2_0) else "1";
    icmp_ln299_fu_1166_p2 <= "1" when (rd_reg_1230 = ap_const_lv5_0) else "0";
    icmp_ln43_fu_392_p2 <= "0" when (trunc_ln29_fu_388_p1 = ap_const_lv2_0) else "1";
    icmp_ln47_fu_408_p2 <= "0" when (tmp_1_fu_398_p4 = ap_const_lv14_0) else "1";
    immU_fu_735_p3 <= (tmp_reg_1293 & ap_const_lv12_0);
    jimm_fu_720_p6 <= ((((tmp_5_reg_1272 & tmp_6_reg_1288) & tmp_8_reg_1283) & tmp_s_reg_1278) & ap_const_lv1_0);
    lshr_ln_fu_420_p4 <= pc_fu_144(17 downto 2);
    mem_address0 <= mem_address0_local;

    mem_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, or_ln43_reg_1209, ap_enable_reg_pp0_iter0, opcode_reg_1218, icmp_ln229_reg_1308, ap_enable_reg_pp0_iter0_reg, icmp_ln206_reg_1312, ap_CS_fsm_pp0_stage2, or_ln236_fu_832_p2, or_ln213_fu_858_p2, zext_ln52_fu_430_p1, ap_block_pp0_stage0, zext_ln245_fu_838_p1, ap_block_pp0_stage2, zext_ln222_fu_864_p1)
    begin
        if (((opcode_reg_1218 = ap_const_lv7_3) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln213_fu_858_p2 = ap_const_lv1_0) and (icmp_ln206_reg_1312 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            mem_address0_local <= zext_ln222_fu_864_p1(16 - 1 downto 0);
        elsif (((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln236_fu_832_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln229_reg_1308 = ap_const_lv1_1))) then 
            mem_address0_local <= zext_ln245_fu_838_p1(16 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mem_address0_local <= zext_ln52_fu_430_p1(16 - 1 downto 0);
        else 
            mem_address0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    mem_ce0 <= mem_ce0_local;

    mem_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, or_ln43_reg_1209, ap_enable_reg_pp0_iter0, opcode_reg_1218, icmp_ln229_reg_1308, ap_enable_reg_pp0_iter0_reg, icmp_ln206_reg_1312, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, or_ln236_fu_832_p2, or_ln213_fu_858_p2)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln236_fu_832_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln229_reg_1308 = ap_const_lv1_1)) or ((opcode_reg_1218 = ap_const_lv7_3) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln213_fu_858_p2 = ap_const_lv1_0) and (icmp_ln206_reg_1312 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)))) then 
            mem_ce0_local <= ap_const_logic_1;
        else 
            mem_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mem_d0 <= reg_file_q0;
    mem_we0 <= mem_we0_local;

    mem_we0_local_assign_proc : process(or_ln43_reg_1209, opcode_reg_1218, icmp_ln229_reg_1308, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, or_ln236_fu_832_p2)
    begin
        if (((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln236_fu_832_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln229_reg_1308 = ap_const_lv1_1))) then 
            mem_we0_local <= ap_const_logic_1;
        else 
            mem_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    next_pc_2_fu_763_p3 <= (tmp_7_fu_753_p4 & ap_const_lv1_0);
    next_pc_3_fu_809_p3 <= 
        grp_fu_325_p2 when (ap_phi_mux_take_4_phi_fu_233_p12(0) = '1') else 
        next_pc_4_fu_743_p2;
    next_pc_4_fu_743_p2 <= std_logic_vector(unsigned(pc_1_reg_1203) + unsigned(ap_const_lv32_4));
    op2_1_fu_960_p2 <= reg_file_q0;
    op2_1_fu_960_p3 <= 
        ap_phi_mux_imm_phi_fu_214_p12 when (icmp_ln176_fu_955_p2(0) = '1') else 
        op2_1_fu_960_p2;
    opcode_fu_435_p1 <= mem_q0(7 - 1 downto 0);
    or_ln16_1_fu_1160_p2 <= (icmp_ln16_3_fu_1155_p2 or icmp_ln16_2_fu_1150_p2);
    or_ln16_fu_666_p2 <= (icmp_ln16_fu_654_p2 or icmp_ln16_1_fu_660_p2);
    or_ln213_fu_858_p2 <= (icmp_ln213_fu_852_p2 or grp_fu_364_p2);
    or_ln236_fu_832_p2 <= (icmp_ln236_fu_826_p2 or grp_fu_364_p2);
    or_ln43_fu_414_p2 <= (icmp_ln47_fu_408_p2 or icmp_ln43_fu_392_p2);
    reg_file_address0 <= reg_file_address0_local;

    reg_file_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln107_fu_585_p1, zext_ln300_fu_1171_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            reg_file_address0_local <= zext_ln300_fu_1171_p1(5 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            reg_file_address0_local <= zext_ln107_fu_585_p1(5 - 1 downto 0);
        else 
            reg_file_address0_local <= "XXXXX";
        end if; 
    end process;

    reg_file_address1 <= zext_ln106_fu_580_p1(5 - 1 downto 0);
    reg_file_ce0 <= reg_file_ce0_local;

    reg_file_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_enable_reg_pp0_iter0_reg, ap_enable_reg_pp0_iter1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            reg_file_ce0_local <= ap_const_logic_1;
        else 
            reg_file_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_ce1 <= reg_file_ce1_local;

    reg_file_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            reg_file_ce1_local <= ap_const_logic_1;
        else 
            reg_file_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_d0 <= ap_phi_mux_res_17_phi_fu_251_p44;
    reg_file_we0 <= reg_file_we0_local;

    reg_file_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, or_ln43_reg_1209, opcode_reg_1218, trunc_ln59_1_reg_1226, func3_reg_1242, icmp_ln229_reg_1308, icmp_ln206_reg_1312, icmp_ln147_reg_1316, or_ln236_reg_1341, or_ln213_reg_1345, ap_enable_reg_pp0_iter1, or_ln16_1_fu_1160_p2, icmp_ln299_fu_1166_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((((((((((((((((((((((((((opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1)) or ((opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))) or ((opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0))) or 
    ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0))) or ((opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or ((opcode_reg_1218 = ap_const_lv7_33) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_2))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 
    = ap_const_lv3_0))) or ((opcode_reg_1218 = ap_const_lv7_17) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0))) or ((opcode_reg_1218 = ap_const_lv7_37) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0))) or ((opcode_reg_1218 = ap_const_lv7_6F) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_7))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_6))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) 
    and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_5))) or ((opcode_reg_1218 = ap_const_lv7_63) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_4))) or ((opcode_reg_1218 = ap_const_lv7_23) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (or_ln236_reg_1341 = ap_const_lv1_0) and (icmp_ln229_reg_1308 = ap_const_lv1_1))) or ((opcode_reg_1218 = ap_const_lv7_67) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0))) or ((opcode_reg_1218 = ap_const_lv7_3) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (or_ln213_reg_1345 = ap_const_lv1_0) and (icmp_ln206_reg_1312 = ap_const_lv1_1))) or ((opcode_reg_1218 
    = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (icmp_ln147_reg_1316 = ap_const_lv1_0))) or (not((trunc_ln59_1_reg_1226 = ap_const_lv6_33)) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0))) or ((trunc_ln59_1_reg_1226 = ap_const_lv6_13) and (opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0))) or ((opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_3))) or ((opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 
    = ap_const_lv3_2))) or ((opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_1))) or ((opcode_reg_1218 = ap_const_lv7_13) and (or_ln43_reg_1209 = ap_const_lv1_0) and (icmp_ln299_fu_1166_p2 = ap_const_lv1_0) and (or_ln16_1_fu_1160_p2 = ap_const_lv1_0) and (func3_reg_1242 = ap_const_lv3_0))))) then 
            reg_file_we0_local <= ap_const_logic_1;
        else 
            reg_file_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    res_12_fu_944_p0 <= reg_file_q1;
    res_12_fu_944_p2 <= std_logic_vector(shift_left(unsigned(res_12_fu_944_p0),to_integer(unsigned('0' & zext_ln130_fu_916_p1(31-1 downto 0)))));
    res_13_fu_919_p0 <= reg_file_q1;
    res_13_fu_919_p2 <= std_logic_vector(shift_right(signed(res_13_fu_919_p0),to_integer(unsigned('0' & zext_ln130_fu_916_p1(31-1 downto 0)))));
    res_14_fu_925_p0 <= reg_file_q1;
    res_14_fu_925_p2 <= std_logic_vector(shift_right(unsigned(res_14_fu_925_p0),to_integer(unsigned('0' & zext_ln130_fu_916_p1(31-1 downto 0)))));
    res_15_fu_931_p3 <= 
        res_13_fu_919_p2 when (grp_fu_370_p2(0) = '1') else 
        res_14_fu_925_p2;
    res_16_fu_1062_p0 <= reg_file_q1;
    res_16_fu_1062_p2 <= "1" when (unsigned(res_16_fu_1062_p0) < unsigned(op2_1_fu_960_p3)) else "0";
    res_23_fu_1045_p0 <= reg_file_q1;
    res_23_fu_1045_p2 <= std_logic_vector(signed(res_23_fu_1045_p0) - signed(op2_1_fu_960_p3));
    res_24_fu_1051_p0 <= reg_file_q1;
    res_24_fu_1051_p2 <= std_logic_vector(signed(res_24_fu_1051_p0) + signed(op2_1_fu_960_p3));
    res_25_fu_1139_p3 <= 
        res_23_reg_1427 when (and_ln183_fu_1135_p2(0) = '1') else 
        res_24_reg_1432;
    res_26_fu_1130_p2 <= (src1_reg_1328 xor op2_1_reg_1386);
    res_27_fu_1125_p2 <= (src1_reg_1328 or op2_1_reg_1386);
    res_28_fu_1120_p2 <= (src1_reg_1328 and op2_1_reg_1386);
    res_29_fu_1019_p0 <= reg_file_q1;
    res_29_fu_1019_p2 <= std_logic_vector(shift_left(unsigned(res_29_fu_1019_p0),to_integer(unsigned('0' & zext_ln189_fu_1015_p1(31-1 downto 0)))));
    res_30_fu_972_p0 <= reg_file_q1;
    res_30_fu_972_p2 <= "1" when (signed(res_30_fu_972_p0) < signed(op2_1_fu_960_p3)) else "0";
    res_31_fu_1111_p1 <= grp_fu_310_p2(32 - 1 downto 0);
    res_35_fu_1004_p0 <= reg_file_q1;
    res_35_fu_1004_p2 <= std_logic_vector(shift_right(signed(res_35_fu_1004_p0),to_integer(unsigned('0' & zext_ln191_fu_989_p1(31-1 downto 0)))));
    res_36_fu_993_p0 <= reg_file_q1;
    res_36_fu_993_p2 <= std_logic_vector(shift_right(unsigned(res_36_fu_993_p0),to_integer(unsigned('0' & zext_ln191_fu_989_p1(31-1 downto 0)))));
    rs1_fu_451_p3 <= mem_q0(19 downto 15);
    rs2_fu_459_p3 <= mem_q0(24 downto 20);
    sext_ln154_1_fu_880_p0 <= reg_file_q0;
    sext_ln154_fu_874_p0 <= reg_file_q1;
        sext_ln154_fu_874_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln154_fu_874_p0),64));

        sext_ln73_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(immI_reg_1252),32));

        sext_ln76_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(simm_fu_694_p3),32));

        sext_ln80_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bimm_fu_705_p6),32));

        sext_ln84_fu_730_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(jimm_fu_720_p6),32));

    simm_fu_694_p3 <= (func7_reg_1246 & rd_reg_1230);
    take_1_fu_795_p0 <= reg_file_q1;
    take_1_fu_795_p1 <= reg_file_q0;
    take_1_fu_795_p2 <= "0" when (take_1_fu_795_p0 = take_1_fu_795_p1) else "1";
    take_3_fu_788_p2 <= (grp_fu_337_p2 xor ap_const_lv1_1);
    take_6_fu_781_p2 <= (grp_fu_330_p2 xor ap_const_lv1_1);
    take_fu_802_p0 <= reg_file_q1;
    take_fu_802_p1 <= reg_file_q0;
    take_fu_802_p2 <= "1" when (take_fu_802_p0 = take_fu_802_p1) else "0";
    tmp_1_fu_398_p4 <= pc_fu_144(31 downto 18);
    tmp_7_fu_753_p4 <= grp_fu_319_p2(31 downto 1);
    trunc_ln176_fu_968_p1 <= op2_1_fu_960_p3(5 - 1 downto 0);
    trunc_ln211_fu_848_p1 <= grp_fu_319_p2(2 - 1 downto 0);
    trunc_ln234_fu_822_p1 <= grp_fu_319_p2(2 - 1 downto 0);
    trunc_ln29_fu_388_p1 <= pc_fu_144(2 - 1 downto 0);
    trunc_ln59_1_fu_439_p1 <= mem_q0(6 - 1 downto 0);
    zext_ln106_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rs1_fu_451_p3),64));
    zext_ln107_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rs2_fu_459_p3),64));
    zext_ln130_fu_916_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rs2_reg_1237),32));
    zext_ln155_1_fu_890_p0 <= reg_file_q0;
    zext_ln155_1_fu_890_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln155_1_fu_890_p0),64));
    zext_ln155_fu_885_p0 <= reg_file_q1;
    zext_ln189_fu_1015_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln176_fu_968_p1),32));
    zext_ln191_fu_989_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln176_fu_968_p1),32));
    zext_ln194_fu_1116_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_30_reg_1393),32));
    zext_ln195_fu_1146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_16_reg_1437),32));
    zext_ln222_fu_864_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_344_p4),64));
    zext_ln245_fu_838_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_344_p4),64));
    zext_ln300_fu_1171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_reg_1230),64));
    zext_ln52_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_420_p4),64));
end behav;
