---
MainSourceFile:  /home/elfo/Documents/ELEC5803/Prometheus_streaming/Prometheus_streaming/hls/.autopilot/db/softmax_accel_hls.pp.0.cc
Diagnostics:     
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_676_1:  '
    FileOffset:      676
    FilePath:        /home/elfo/Documents/2025.1/Vitis/common/technology/autopilot/etc/ap_int_ref.h
    Replacements:    
      - FilePath:        /home/elfo/Documents/ELEC5803/Prometheus_streaming/Prometheus_streaming/hls/.autopilot/db/softmax_accel_hls.pp.0.cc
        Offset:          280265
        Length:          0
        ReplacementText: 'VITIS_LOOP_676_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_690_1:  '
    FileOffset:      690
    FilePath:        /home/elfo/Documents/2025.1/Vitis/common/technology/autopilot/etc/ap_int_ref.h
    Replacements:    
      - FilePath:        /home/elfo/Documents/ELEC5803/Prometheus_streaming/Prometheus_streaming/hls/.autopilot/db/softmax_accel_hls.pp.0.cc
        Offset:          280731
        Length:          0
        ReplacementText: 'VITIS_LOOP_690_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_704_1:  '
    FileOffset:      704
    FilePath:        /home/elfo/Documents/2025.1/Vitis/common/technology/autopilot/etc/ap_int_ref.h
    Replacements:    
      - FilePath:        /home/elfo/Documents/ELEC5803/Prometheus_streaming/Prometheus_streaming/hls/.autopilot/db/softmax_accel_hls.pp.0.cc
        Offset:          281198
        Length:          0
        ReplacementText: 'VITIS_LOOP_704_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_1248_1:  '
    FileOffset:      1248
    FilePath:        /home/elfo/Documents/2025.1/Vitis/common/technology/autopilot/etc/ap_fixed_base.h
    Replacements:    
      - FilePath:        /home/elfo/Documents/ELEC5803/Prometheus_streaming/Prometheus_streaming/hls/.autopilot/db/softmax_accel_hls.pp.0.cc
        Offset:          576028
        Length:          0
        ReplacementText: 'VITIS_LOOP_1248_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_92_1:  '
    FileOffset:      92
    FilePath:        softmax_accel_hls.cc
    Replacements:    
      - FilePath:        /home/elfo/Documents/ELEC5803/Prometheus_streaming/Prometheus_streaming/hls/.autopilot/db/softmax_accel_hls.pp.0.cc
        Offset:          964871
        Length:          0
        ReplacementText: 'VITIS_LOOP_92_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_247_1:  '
    FileOffset:      247
    FilePath:        softmax_accel_hls.cc
    Replacements:    
      - FilePath:        /home/elfo/Documents/ELEC5803/Prometheus_streaming/Prometheus_streaming/hls/.autopilot/db/softmax_accel_hls.pp.0.cc
        Offset:          968516
        Length:          0
        ReplacementText: 'VITIS_LOOP_247_1: '
  - DiagnosticName:  clang-diagnostic-error
    Message:         'Invalid Directive: for current device, ram_1p + bram is invalid combination for BIND_STORAGE''s option ''type + impl'''
    FileOffset:      280
    FilePath:        softmax_accel_hls.cc
    Replacements:    
  - DiagnosticName:  clang-diagnostic-error
    Message:         'Invalid Directive: for current device, ram_1p + bram is invalid combination for BIND_STORAGE''s option ''type + impl'''
    FileOffset:      281
    FilePath:        softmax_accel_hls.cc
    Replacements:    
...
